# Generated by Django 6.0.5 on 2026-06-01 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0015_certificadocurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamentos_ativados', models.BooleanField(default=True, verbose_name='Pagamentos Ativados')),
                ('gateway_padrao', models.CharField(choices=[('PRONTU', 'Prontu'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], default='PRONTU', max_length=50, verbose_name='Gateway Padrão')),
                ('moeda_padrao', models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar (USD)')], default='AOA', max_length=3, verbose_name='Moeda Padrão')),
                ('tempo_expiracao_link_minutos', models.PositiveIntegerField(default=30, help_text='Quanto tempo o link de pagamento fica válido', verbose_name='Tempo de Expiração do Link (minutos)')),
                ('tempo_confirmacao_automatica_minutos', models.PositiveIntegerField(default=5, help_text='Aguarda este tempo para confirmar pagamento antes de expirar', verbose_name='Tempo para Confirmação Automática (minutos)')),
                ('max_tentativas_pagamento', models.PositiveIntegerField(default=3, verbose_name='Máximo de Tentativas')),
                ('max_tentativas_webhook', models.PositiveIntegerField(default=5, verbose_name='Máximo de Tentativas de Webhook')),
                ('desconto_inscricao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto na Inscrição (%)')),
                ('notificar_admin_pagamento_recebido', models.BooleanField(default=True, verbose_name='Notificar Admin ao Receber Pagamento')),
                ('exigir_verificacao_email', models.BooleanField(default=True, verbose_name='Exigir Verificação de Email')),
                ('exigir_cpf_valido', models.BooleanField(default=False, verbose_name='Exigir CPF/NIF Válido')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configurações de Pagamento',
                'constraints': [models.CheckConstraint(condition=models.Q(('tempo_expiracao_link_minutos__gt', 0)), name='tempo_expiracao_positivo'), models.CheckConstraint(condition=models.Q(('max_tentativas_pagamento__gt', 0)), name='max_tentativas_positivo')],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_pagamento', models.CharField(db_index=True, help_text='ID único do pagamento gerado pelo sistema', max_length=100, unique=True, verbose_name='Referência de Pagamento')),
                ('tipo_pagamento', models.CharField(choices=[('INSCRICAO', 'Inscrição em Curso'), ('PAGAMENTO_CURSO', 'Pagamento do Curso'), ('PARCELAMENTO', 'Parcela do Curso'), ('TAXA_ADMINISTRATIVO', 'Taxa Administrativa'), ('OUTRO', 'Outro')], default='INSCRICAO', max_length=50, verbose_name='Tipo de Pagamento')),
                ('numero_parcela', models.PositiveIntegerField(blank=True, help_text='Se aplicável, indica qual parcela está sendo paga', null=True, verbose_name='Número da Parcela')),
                ('moeda', models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar (USD)')], default='AOA', max_length=3, verbose_name='Moeda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Pagamento')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do Desconto')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Final')),
                ('gateway', models.CharField(choices=[('PRONTU', 'Prontu'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], default='PRONTU', max_length=50, verbose_name='Gateway de Pagamento')),
                ('referencia_gateway', models.CharField(blank=True, db_index=True, help_text='ID da transação fornecido pelo gateway', max_length=200, null=True, verbose_name='Referência do Gateway')),
                ('url_pagamento', models.URLField(blank=True, help_text='URL para redirecionamento do cliente', null=True, verbose_name='URL de Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('REQUESTED', 'Solicitado'), ('PROCESSING', 'Processando'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], db_index=True, default='PENDING', max_length=20, verbose_name='Status do Pagamento')),
                ('url_sucesso', models.URLField(blank=True, help_text='Onde redirecionar após pagamento bem-sucedido', null=True, verbose_name='URL de Sucesso')),
                ('url_cancelamento', models.URLField(blank=True, help_text='Onde redirecionar em caso de cancelamento', null=True, verbose_name='URL de Cancelamento')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON', verbose_name='Metadados')),
                ('resposta_gateway', models.JSONField(blank=True, default=dict, help_text='Resposta completa do gateway (para auditoria)', verbose_name='Resposta do Gateway')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_vencimento', models.DateTimeField(blank=True, help_text='Quando o link de pagamento expira', null=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateTimeField(blank=True, help_text='Quando o pagamento foi confirmado', null=True, verbose_name='Data do Pagamento')),
                ('tentativas_pagamento', models.PositiveIntegerField(default=0, help_text='Número de tentativas de pagamento', verbose_name='Tentativas de Pagamento')),
                ('webhook_processado', models.BooleanField(default=False, help_text='Se o callback do gateway foi processado', verbose_name='Webhook Processado')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='cursos_app.curso', verbose_name='Curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('PENDING', 'Pendente'), ('REQUESTED', 'Solicitado'), ('PROCESSING', 'Processando'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('PENDING', 'Pendente'), ('REQUESTED', 'Solicitado'), ('PROCESSING', 'Processando'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], max_length=20, verbose_name='Status Novo')),
                ('motivo', models.TextField(blank=True, help_text='Motivo da mudança de status', verbose_name='Motivo')),
                ('referencia_gateway', models.CharField(blank=True, help_text='ID da transação do gateway', max_length=200, verbose_name='Referência do Gateway')),
                ('resposta_gateway', models.JSONField(blank=True, default=dict, verbose_name='Resposta do Gateway')),
                ('criado_por', models.CharField(choices=[('SISTEMA', 'Sistema'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual'), ('ADMIN', 'Admin')], default='SISTEMA', max_length=100, verbose_name='Criado Por')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pagamentos.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Históricos de Pagamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TentativaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentativa', models.PositiveIntegerField(verbose_name='Número da Tentativa')),
                ('status_resposta', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('TIMEOUT', 'Timeout'), ('INVALIDO', 'Inválido')], max_length=20, verbose_name='Status da Resposta')),
                ('codigo_erro', models.CharField(blank=True, max_length=50, verbose_name='Código de Erro')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('resposta_gateway', models.JSONField(blank=True, default=dict, verbose_name='Resposta do Gateway')),
                ('tempo_resposta_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (ms)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='pagamentos.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Tentativa de Pagamento',
                'verbose_name_plural': 'Tentativas de Pagamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['usuario', 'status'], name='pagamentos__usuario_847b70_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['curso', 'status'], name='pagamentos__curso_i_40b920_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['referencia_pagamento'], name='pagamentos__referen_6bcd63_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['referencia_gateway'], name='pagamentos__referen_ced929_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['data_criacao'], name='pagamentos__data_cr_7cd7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopagamento',
            index=models.Index(fields=['pagamento', 'data_criacao'], name='pagamentos__pagamen_58c627_idx'),
        ),
    ]
