# Generated by Django 5.2.12 on 2026-05-28 18:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0015_certificadocurso'),
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaopagamento',
            options={'verbose_name': 'Configuração de Pagamento', 'verbose_name_plural': 'Configurações de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='historicopagamento',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Histórico de Pagamento', 'verbose_name_plural': 'Históricos de Pagamento'},
        ),
        migrations.RemoveIndex(
            model_name='pagamento',
            name='pagamentos_pag_status_data_idx',
        ),
        migrations.RenameIndex(
            model_name='pagamento',
            new_name='pagamentos__usuario_847b70_idx',
            old_name='pagamentos_pag_usuario_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pagamento',
            new_name='pagamentos__referen_6bcd63_idx',
            old_name='pagamentos_pag_referencia_idx',
        ),
        migrations.RemoveField(
            model_name='configuracaopagamento',
            name='validar_webhook_signature',
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='exigir_cpf_valido',
            field=models.BooleanField(default=False, verbose_name='Exigir CPF/NIF Válido'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='exigir_verificacao_email',
            field=models.BooleanField(default=True, verbose_name='Exigir Verificação de Email'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='max_tentativas_webhook',
            field=models.PositiveIntegerField(default=5, verbose_name='Máximo de Tentativas de Webhook'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='tempo_confirmacao_automatica_minutos',
            field=models.PositiveIntegerField(default=5, help_text='Aguarda este tempo para confirmar pagamento antes de expirar', verbose_name='Tempo para Confirmação Automática (minutos)'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='desconto_inscricao_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto na Inscrição (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='gateway_padrao',
            field=models.CharField(choices=[('PRONTU', 'Prontu'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], default='PRONTU', max_length=50, verbose_name='Gateway Padrão'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='max_tentativas_pagamento',
            field=models.PositiveIntegerField(default=3, verbose_name='Máximo de Tentativas'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='moeda_padrao',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar (USD)')], default='AOA', max_length=3, verbose_name='Moeda Padrão'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='notificar_admin_pagamento_recebido',
            field=models.BooleanField(default=True, verbose_name='Notificar Admin ao Receber Pagamento'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='pagamentos_ativados',
            field=models.BooleanField(default=True, verbose_name='Pagamentos Ativados'),
        ),
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='tempo_expiracao_link_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Quanto tempo o link de pagamento fica válido', verbose_name='Tempo de Expiração do Link (minutos)'),
        ),
        migrations.AlterField(
            model_name='historicopagamento',
            name='criado_por',
            field=models.CharField(choices=[('SISTEMA', 'Sistema'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual'), ('ADMIN', 'Admin')], default='SISTEMA', max_length=100, verbose_name='Criado Por'),
        ),
        migrations.AlterField(
            model_name='historicopagamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='historicopagamento',
            name='motivo',
            field=models.TextField(blank=True, help_text='Motivo da mudança de status', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historicopagamento',
            name='referencia_gateway',
            field=models.CharField(blank=True, help_text='ID da transação do gateway', max_length=200, verbose_name='Referência do Gateway'),
        ),
        migrations.AlterField(
            model_name='historicopagamento',
            name='resposta_gateway',
            field=models.JSONField(blank=True, default=dict, verbose_name='Resposta do Gateway'),
        ),
        migrations.AlterField(
            model_name='historicopagamento',
            name='status_anterior',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('REQUESTED', 'Solicitado'), ('PROCESSING', 'Processando'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], max_length=20, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='historicopagamento',
            name='status_novo',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('REQUESTED', 'Solicitado'), ('PROCESSING', 'Processando'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], max_length=20, verbose_name='Status Novo'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='cursos_app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, help_text='Quando o pagamento foi confirmado', null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_vencimento',
            field=models.DateTimeField(blank=True, help_text='Quando o link de pagamento expira', null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='gateway',
            field=models.CharField(choices=[('PRONTU', 'Prontu'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], default='PRONTU', max_length=50, verbose_name='Gateway de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='moeda',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar (USD)')], default='AOA', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='numero_parcela',
            field=models.PositiveIntegerField(blank=True, help_text='Se aplicável, indica qual parcela está sendo paga', null=True, verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='referencia_gateway',
            field=models.CharField(blank=True, db_index=True, help_text='ID da transação fornecido pelo gateway', max_length=200, null=True, verbose_name='Referência do Gateway'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='referencia_pagamento',
            field=models.CharField(db_index=True, help_text='ID único do pagamento gerado pelo sistema', max_length=100, unique=True, verbose_name='Referência de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='resposta_gateway',
            field=models.JSONField(blank=True, default=dict, help_text='Resposta completa do gateway (para auditoria)', verbose_name='Resposta do Gateway'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('REQUESTED', 'Solicitado'), ('PROCESSING', 'Processando'), ('ACCEPTED', 'Aceite'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], db_index=True, default='PENDING', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tentativas_pagamento',
            field=models.PositiveIntegerField(default=0, help_text='Número de tentativas de pagamento', verbose_name='Tentativas de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('INSCRICAO', 'Inscrição em Curso'), ('PAGAMENTO_CURSO', 'Pagamento do Curso'), ('PARCELAMENTO', 'Parcela do Curso'), ('TAXA_ADMINISTRATIVO', 'Taxa Administrativa'), ('OUTRO', 'Outro')], default='INSCRICAO', max_length=50, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='url_cancelamento',
            field=models.URLField(blank=True, help_text='Onde redirecionar em caso de cancelamento', null=True, verbose_name='URL de Cancelamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='url_pagamento',
            field=models.URLField(blank=True, help_text='URL para redirecionamento do cliente', null=True, verbose_name='URL de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='url_sucesso',
            field=models.URLField(blank=True, help_text='Onde redirecionar após pagamento bem-sucedido', null=True, verbose_name='URL de Sucesso'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do Desconto'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Final'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='webhook_processado',
            field=models.BooleanField(default=False, help_text='Se o callback do gateway foi processado', verbose_name='Webhook Processado'),
        ),
        migrations.AlterField(
            model_name='tentativapagamento',
            name='codigo_erro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de Erro'),
        ),
        migrations.AlterField(
            model_name='tentativapagamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='tentativapagamento',
            name='mensagem_erro',
            field=models.TextField(blank=True, verbose_name='Mensagem de Erro'),
        ),
        migrations.AlterField(
            model_name='tentativapagamento',
            name='numero_tentativa',
            field=models.PositiveIntegerField(verbose_name='Número da Tentativa'),
        ),
        migrations.AlterField(
            model_name='tentativapagamento',
            name='resposta_gateway',
            field=models.JSONField(blank=True, default=dict, verbose_name='Resposta do Gateway'),
        ),
        migrations.AlterField(
            model_name='tentativapagamento',
            name='status_resposta',
            field=models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('TIMEOUT', 'Timeout'), ('INVALIDO', 'Inválido')], max_length=20, verbose_name='Status da Resposta'),
        ),
        migrations.AlterField(
            model_name='tentativapagamento',
            name='tempo_resposta_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de Resposta (ms)'),
        ),
        migrations.AddIndex(
            model_name='historicopagamento',
            index=models.Index(fields=['pagamento', 'data_criacao'], name='pagamentos__pagamen_58c627_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['curso', 'status'], name='pagamentos__curso_i_40b920_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['referencia_gateway'], name='pagamentos__referen_ced929_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['data_criacao'], name='pagamentos__data_cr_7cd7b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracaopagamento',
            constraint=models.CheckConstraint(condition=models.Q(('tempo_expiracao_link_minutos__gt', 0)), name='tempo_expiracao_positivo'),
        ),
        migrations.AddConstraint(
            model_name='configuracaopagamento',
            constraint=models.CheckConstraint(condition=models.Q(('max_tentativas_pagamento__gt', 0)), name='max_tentativas_positivo'),
        ),
    ]
