# Generated by Django 6.0.5 on 2026-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_add_tempo_confirmacao_automatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('INSCRICAO', 'Inscrição em Curso'), ('INSCRICAO_VIDEO', 'Subscrição Edukangola Play'), ('PAGAMENTO_CURSO', 'Pagamento do Curso'), ('PARCELAMENTO', 'Parcela do Curso'), ('TAXA_ADMINISTRATIVO', 'Taxa Administrativa'), ('OUTRO', 'Outro')], default='INSCRICAO', max_length=50, verbose_name='Tipo de Pagamento'),
        ),
    ]
