# Generated by Django 6.0.5 on 2026-06-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_fix_uuid_pk'),
        ('planos', '0003_plano_permite_gerar_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='planos.plano', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('INSCRICAO', 'Inscrição em Curso'), ('INSCRICAO_VIDEO', 'Subscrição Edukangola Play'), ('PAGAMENTO_CURSO', 'Pagamento do Curso'), ('PARCELAMENTO', 'Parcela do Curso'), ('ASSINATURA_PLANO', 'Subscrição de Plano de Centro'), ('TAXA_ADMINISTRATIVO', 'Taxa Administrativa'), ('OUTRO', 'Outro')], default='INSCRICAO', max_length=50, verbose_name='Tipo de Pagamento'),
        ),
    ]
