# Generated by Django 5.2.4 on 2026-08-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0018_alter_configuracaoplataforma_options_and_more'),
        ('pagamentos', '0007_pagamento_plano_alter_pagamento_tipo_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ex: Agosto/2026', max_length=50, verbose_name='Período de Apuração')),
                ('total_bruto_inscricoes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Faturação Bruta (Kz)')),
                ('percentual_comissao_plataforma', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Comissão Retida (%)')),
                ('valor_comissao_plataforma', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Retido pela EdukAngola (Kz)')),
                ('valor_liquido_centro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganhos Líquidos do Centro (Kz)')),
                ('pago', models.BooleanField(default=False, verbose_name='Repasse Efetuado?')),
                ('comprovativo_repasse', models.FileField(blank=True, null=True, upload_to='comprovativos_financeiros/', verbose_name='Comprovativo bancário de repasse')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Relatório')),
                ('data_pagamento_repasse', models.DateTimeField(blank=True, null=True, verbose_name='Data da Transferência')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_financeiros', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação')),
            ],
            options={
                'verbose_name': 'Finanças & Repasse de Centro',
                'verbose_name_plural': 'Finanças & Repasses de Centros',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
