# Generated by Django 5.2.4 on 2026-08-14 06:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0028_matricula_operacional'),
        ('gestoreduka', '0018_alter_configuracaoplataforma_options_and_more'),
        ('pagamentos', '0008_financeirocentro'),
        ('usuarios', '0015_create_muquissi_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Referência do Recibo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Recebido')),
                ('forma', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('DEPOSITO', 'Depósito'), ('OUTRO', 'Outro')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento')),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='CONFIRMADO', max_length=12, verbose_name='Estado')),
                ('data_recebimento', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data do Recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='usuarios.aluno')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='gestoreduka.centrodeformacao')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='cursos_app.matricula')),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_registados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recebimento do Centro',
                'verbose_name_plural': 'Recebimentos do Centro',
                'ordering': ['-data_recebimento'],
                'indexes': [models.Index(fields=['centro', 'data_recebimento'], name='pagamentos__centro__a4a511_idx'), models.Index(fields=['matricula', 'estado'], name='pagamentos__matricu_c71a47_idx')],
            },
        ),
    ]
