# Generated by Django 5.2.4 on 2026-08-18 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0033_alter_curso_modalidade'),
        ('gestoreduka', '0024_depoimento_consentimento_origem'),
        ('pagamentos', '0009_recebimentos_centro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('INSCRICAO', 'Inscrição em Curso'), ('INSCRICAO_VIDEO', 'Subscrição Edukangola Play'), ('PAGAMENTO_CURSO', 'Pagamento do Curso'), ('PARCELAMENTO', 'Parcela do Curso'), ('ASSINATURA_PLANO', 'Subscrição de Plano de Centro'), ('TAXA_ADMINISTRATIVO', 'Taxa Administrativa'), ('BILHETE_EVENTO', 'Bilhete de Evento'), ('OUTRO', 'Outro')], default='INSCRICAO', max_length=50, verbose_name='Tipo de Pagamento'),
        ),
        migrations.CreateModel(
            name='CupomPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=32, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PERCENTUAL', 'Percentagem'), ('VALOR_FIXO', 'Valor fixo')], default='PERCENTUAL', max_length=16)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('maximo_utilizacoes', models.PositiveIntegerField(blank=True, null=True)),
                ('utilizacoes', models.PositiveIntegerField(default=0)),
                ('maximo_por_aluno', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupoes_promocionais', to='gestoreduka.centrodeformacao')),
                ('cursos', models.ManyToManyField(blank=True, related_name='cupoes_promocionais', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Cupão promocional',
                'verbose_name_plural': 'Cupões promocionais',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='CupomResgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resgates', to='pagamentos.cupompromocional')),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resgate_cupom', to='pagamentos.pagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resgates_cupom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
