# Generated by Django 5.2.4 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pagamentos', '0011_alter_pagamento_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(
                choices=[
                    ('INSCRICAO', 'Inscrição em Curso'),
                    ('INSCRICAO_VIDEO', 'Subscrição Edukangola Play'),
                    ('ASSINATURA_VIDEO', 'Subscrição mensal de cursos em vídeo'),
                    ('PAGAMENTO_CURSO', 'Pagamento do Curso'),
                    ('PARCELAMENTO', 'Parcela do Curso'),
                    ('ASSINATURA_PLANO', 'Subscrição de Plano de Centro'),
                    ('TAXA_ADMINISTRATIVO', 'Taxa Administrativa'),
                    ('BILHETE_EVENTO', 'Bilhete de Evento'),
                    ('PEDIDO_MERCADO', 'Pedido do Mercado Edukangola'),
                    ('OUTRO', 'Outro'),
                ],
                default='INSCRICAO',
                max_length=50,
                verbose_name='Tipo de Pagamento',
            ),
        ),
    ]
