# Generated by Django 5.2.4 on 2026-08-23
from django.db import migrations, models


MOEDAS = [
    ('AOA', 'Kwanza (AOA)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar (USD)'),
    ('MZN', 'Metical moçambicano (MZN)'), ('XOF', 'Franco CFA da África Ocidental (XOF)'),
    ('CVE', 'Escudo cabo-verdiano (CVE)'), ('BRL', 'Real brasileiro (BRL)'),
    ('STN', 'Dobra são-tomense (STN)'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0012_pagamento_assinatura_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaopagamento',
            name='moeda_padrao',
            field=models.CharField(choices=MOEDAS, default='AOA', max_length=3, verbose_name='Moeda Padrão'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='moeda',
            field=models.CharField(choices=MOEDAS, default='AOA', max_length=3, verbose_name='Moeda'),
        ),
    ]
