# Generated by Django 5.2.4 on 2026-08-16 07:26

import django.core.validators
import django.db.models.deletion
import eventos_marketplace.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('resumo', models.CharField(blank=True, max_length=320)),
                ('descricao', models.TextField()),
                ('imagem_capa', models.ImageField(blank=True, upload_to='eventos/capas/')),
                ('categoria', models.CharField(default='Tecnologia', max_length=100)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=12)),
                ('data_inicio', models.DateTimeField(db_index=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=220)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('url_online', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de aprovação'), ('PUBLICADO', 'Publicado'), ('ESGOTADO', 'Esgotado'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=14)),
                ('destaque', models.BooleanField(db_index=True, default=False)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento do marketplace',
                'verbose_name_plural': 'Eventos do marketplace',
                'ordering': ['-destaque', 'data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OrganizadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome público')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo', models.CharField(choices=[('COMUNIDADE', 'Comunidade / Grupo'), ('EMPRESA', 'Empresa'), ('INSTITUICAO', 'Instituição'), ('OUTRO', 'Outro')], default='COMUNIDADE', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logotipo', models.ImageField(blank=True, upload_to='eventos/organizadores/')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado pela Edukangola')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organizador de evento',
                'verbose_name_plural': 'Organizadores de eventos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LoteBilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do lote')),
                ('descricao', models.CharField(blank=True, max_length=240)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moeda', models.CharField(default='AOA', max_length=3)),
                ('quantidade_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantidade_vendida', models.PositiveIntegerField(default=0)),
                ('inicio_vendas', models.DateTimeField(blank=True, null=True)),
                ('fim_vendas', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='eventos_marketplace.eventomarketplace')),
            ],
            options={
                'verbose_name': 'Lote de bilhetes',
                'verbose_name_plural': 'Lotes de bilhetes',
                'ordering': ['ordem', 'preco'],
            },
        ),
        migrations.AddField(
            model_name='eventomarketplace',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos_marketplace.organizadorevento'),
        ),
        migrations.CreateModel(
            name='PedidoBilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(default=eventos_marketplace.models.gerar_referencia_pedido, max_length=80, unique=True)),
                ('nome_comprador', models.CharField(max_length=160)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('telefone_comprador', models.CharField(blank=True, max_length=30)),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_organizador', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moeda', models.CharField(default='AOA', max_length=3)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado'), ('REEMBOLSADO', 'Reembolsado')], db_index=True, default='PENDENTE', max_length=14)),
                ('referencia_pagamento', models.CharField(blank=True, db_index=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='eventos_marketplace.eventomarketplace')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='eventos_marketplace.lotebilhete')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_bilhetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de bilhete',
                'verbose_name_plural': 'Pedidos de bilhetes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_participante', models.CharField(max_length=160)),
                ('email_participante', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('VALIDO', 'Válido'), ('UTILIZADO', 'Utilizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='VALIDO', max_length=12)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('utilizado_em', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bilhetes', to='eventos_marketplace.lotebilhete')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes', to='eventos_marketplace.pedidobilhete')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': 'Bilhetes',
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.AddIndex(
            model_name='eventomarketplace',
            index=models.Index(fields=['status', 'data_inicio'], name='eventos_mar_status_b5f41e_idx'),
        ),
    ]
