# Generated by Django 5.2.4 on 2026-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotebilhete',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Um benefício por linha.', verbose_name='Benefícios'),
        ),
        migrations.AddField(
            model_name='lotebilhete',
            name='cor_primaria',
            field=models.CharField(default='#6D28D9', help_text='Hexadecimal, por exemplo #6D28D9.', max_length=7, verbose_name='Cor principal'),
        ),
        migrations.AddField(
            model_name='lotebilhete',
            name='cor_secundaria',
            field=models.CharField(default='#EEF2FF', help_text='Hexadecimal, por exemplo #EEF2FF.', max_length=7, verbose_name='Cor secundária'),
        ),
        migrations.AddField(
            model_name='lotebilhete',
            name='imagem_ingresso',
            field=models.ImageField(blank=True, upload_to='eventos/ingressos/', verbose_name='Imagem do ingresso'),
        ),
        migrations.AddField(
            model_name='lotebilhete',
            name='regras',
            field=models.TextField(blank=True, help_text='Regras específicas deste lote, um item por linha.', verbose_name='Regras'),
        ),
        migrations.AddField(
            model_name='lotebilhete',
            name='texto_ingresso',
            field=models.CharField(blank=True, help_text='Texto curto apresentado no ingresso digital.', max_length=180, verbose_name='Texto do ingresso'),
        ),
    ]
