# Generated by Django 5.2.4 on 2025-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria de Imagens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
