# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria de Imagens',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SobreNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('missao', models.TextField(blank=True, null=True)),
                ('visao', models.TextField(blank=True, null=True)),
                ('valores', models.TextField(blank=True, null=True)),
                ('imagem_destaque', models.ImageField(blank=True, null=True, upload_to='sobre_nos/')),
                ('video_explicacao', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])])),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
