# Generated by Django 5.2.4 on 2026-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Contacto',
                'verbose_name_plural': 'Mensagens de Contacto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='sobrenos',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contacto'),
        ),
        migrations.AddField(
            model_name='sobrenos',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='sobrenos',
            name='mapa_iframe',
            field=models.TextField(blank=True, help_text='Cole aqui o código de incorporação do Google Maps', null=True, verbose_name='Iframe do Google Maps'),
        ),
        migrations.AddField(
            model_name='sobrenos',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
