# Generated by Django 5.2.4 on 2025-09-18 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('missao', models.TextField(blank=True, null=True)),
                ('visao', models.TextField(blank=True, null=True)),
                ('valores', models.TextField(blank=True, null=True)),
                ('imagem_destaque', models.ImageField(blank=True, null=True, upload_to='sobre_nos/')),
                ('video_explicacao', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])])),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
