# Generated by Django 5.2.4 on 2026-05-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mensagemcontato_sobrenos_email_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem_fundo', models.ImageField(upload_to='publicidades/', verbose_name='Imagem de Fundo')),
                ('url_destino', models.URLField(blank=True, null=True, verbose_name='URL de Destino')),
                ('texto_botao', models.CharField(blank=True, default='Saiba Mais', max_length=50, verbose_name='Texto do Botão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publicidade',
                'verbose_name_plural': 'Publicidades',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
