# Generated by Django 5.2.4 on 2026-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publicidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(help_text='Ex: Mobile App, Site Parceiro, etc.', max_length=150, unique=True, verbose_name='Nome do Cliente / Site')),
                ('chave', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Chave de API')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chave de API de Cliente',
                'verbose_name_plural': 'Chaves de API de Clientes',
            },
        ),
    ]
