# Generated by Django 5.2.4 on 2026-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clienteapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidade',
            name='posicao',
            field=models.CharField(choices=[('HERO_BOLSA', 'Hero Banner Principal (Bolsas)'), ('EMPRESAS', 'Banner Formação para Empresas'), ('GERAL', 'Geral / Outros')], db_index=True, default='GERAL', max_length=20, verbose_name='Posição no Site'),
        ),
        migrations.AddField(
            model_name='publicidade',
            name='subtitulo',
            field=models.TextField(blank=True, null=True, verbose_name='Subtítulo / Descrição Curta'),
        ),
        migrations.AddField(
            model_name='publicidade',
            name='tag_label',
            field=models.CharField(blank=True, help_text='Ex: Publicidade · Jovem Digital', max_length=100, null=True, verbose_name='Etiqueta / Tag'),
        ),
        migrations.AlterField(
            model_name='publicidade',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='publicidade',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='publicidades/', verbose_name='Imagem de Fundo / Banner'),
        ),
    ]
