# Generated by Django 5.2.4 on 2026-08-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicidade_posicao_publicidade_subtitulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_index=True, max_length=120, verbose_name='Categoria')),
                ('pergunta', models.CharField(max_length=420, verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('idioma', models.CharField(choices=[('pt', 'Português'), ('en', 'English'), ('fr', 'Français'), ('zh', '中文')], db_index=True, default='pt', max_length=8, verbose_name='Idioma')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('publicada', models.BooleanField(db_index=True, default=False, verbose_name='Publicada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ('idioma', 'categoria', 'ordem', 'id'),
                'constraints': [models.UniqueConstraint(fields=('idioma', 'categoria', 'pergunta'), name='core_faq_idioma_categoria_pergunta_unica')],
            },
        ),
    ]
