# Generated by Django 5.2.4 on 2026-08-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perguntafrequente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoNotificacaoOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True, verbose_name='ID do evento')),
                ('event_type', models.CharField(db_index=True, max_length=80, verbose_name='Tipo do evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Dados do evento')),
                ('occurred_at', models.DateTimeField(verbose_name='Ocorrido em')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Último erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento de notificação pendente',
                'verbose_name_plural': 'Eventos de notificação pendentes',
                'ordering': ('publicado_em', 'criado_em'),
                'indexes': [models.Index(fields=['publicado_em', 'criado_em'], name='core_outbox_pending_idx')],
            },
        ),
    ]
