# Generated by Django 5.2.4 on 2026-08-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventonotificacaooutbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True, verbose_name='Data')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Feriado ou data relevante',
                'verbose_name_plural': 'Feriados e datas relevantes',
                'ordering': ('data',),
            },
        ),
    ]
