import { ArrowRight, ChevronLeft, ChevronRight, Megaphone, Pause, Play } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { backendUrl } from "../lib/backend-url";
import { useI18n } from "../lib/i18n";
import "./campaign-carousel.css";

const copy = {
  pt: [["Campanha Edukangola", "A formação certa começa com uma turma que cabe na sua rotina.", "Explore cursos publicados por centros de formação e compare datas, horários, vagas e condições antes de avançar.", "Ver turmas abertas"], ["Para centros de formação", "Dê visibilidade aos seus cursos e organize as inscrições num só lugar.", "Publique formações, abra turmas e acompanhe as candidaturas dos alunos com o GestorEduka.", "Conhecer o GestorEduka"], ["Espaço para parceiros", "A sua organização pode chegar a alunos que procuram novas oportunidades.", "Espaço para campanhas educativas, bolsas, empregabilidade ou parceiros da plataforma.", "Falar sobre parceria"]],
  en: [["Edukangola campaign", "The right training starts with a class that fits your routine.", "Explore courses published by training centres and compare dates, timetables, vacancies and conditions before continuing.", "View open classes"], ["For training centres", "Give your courses visibility and organise enrolments in one place.", "Publish training, open classes and follow student applications with GestorEduka.", "Discover GestorEduka"], ["Partner space", "Your organisation can reach students looking for new opportunities.", "Space for educational campaigns, scholarships, employability or platform partners.", "Discuss a partnership"]],
  fr: [["Campagne Edukangola", "La bonne formation commence avec un groupe adapté à votre rythme.", "Explorez les cours publiés par les centres et comparez dates, horaires, places et conditions avant de continuer.", "Voir les groupes ouverts"], ["Pour les centres de formation", "Donnez de la visibilité à vos cours et organisez les inscriptions au même endroit.", "Publiez des formations, ouvrez des groupes et suivez les candidatures avec GestorEduka.", "Découvrir GestorEduka"], ["Espace partenaires", "Votre organisation peut toucher des étudiants à la recherche de nouvelles opportunités.", "Espace pour les campagnes éducatives, bourses, emploi ou partenaires de la plateforme.", "Parler d’un partenariat"]],
  zh: [["Edukangola 活动", "合适的培训从适合您日常安排的班级开始。", "探索培训中心发布的课程，并在继续前比较日期、时间、名额和条件。", "查看开放班级"], ["培训中心服务", "让您的课程获得曝光，并在一个地方管理报名。", "使用 GestorEduka 发布培训、开设班级并跟进学生申请。", "了解 GestorEduka"], ["合作伙伴空间", "您的机构可以接触正在寻找新机会的学生。", "用于教育活动、奖学金、就业或平台合作伙伴的展示空间。", "洽谈合作"]],
};

export default function CampaignCarousel({ onNavigate }) {
  const { language, t } = useI18n();
  const [active, setActive] = useState(0); const [paused, setPaused] = useState(false);
  const campaigns = useMemo(() => copy[language].map((item, index) => ({ tag: item[0], title: item[1], text: item[2], action: item[3], href: index === 0 ? "/cursos?turma=aberta" : index === 1 ? backendUrl("/gestoreduka/") : backendUrl("/contato/"), type: index === 0 ? "internal" : "external", tone: ["lavender", "gold", "sky"][index], symbol: `0${index + 1}`, partner: index === 2 })), [language]);
  const activeCampaign = campaigns[active]; const previous = campaigns[(active - 1 + campaigns.length) % campaigns.length]; const next = campaigns[(active + 1) % campaigns.length]; const reducedMotion = useRef(typeof window !== "undefined" && window.matchMedia("(prefers-reduced-motion: reduce)").matches);
  useEffect(() => { if (paused || reducedMotion.current) return undefined; const timer = window.setInterval(() => setActive((current) => (current + 1) % campaigns.length), 6500); return () => window.clearInterval(timer); }, [paused, campaigns.length]);
  const advance = (direction) => setActive((current) => (current + direction + campaigns.length) % campaigns.length);
  const activateLink = (event) => { if (activeCampaign.type !== "internal" || event.metaKey || event.ctrlKey || event.shiftKey) return; event.preventDefault(); onNavigate(activeCampaign.href); };
  return <section className="campaign-section" aria-label={t("home.eyebrow")}><div className="campaign-rail" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}><button className={`campaign-peek ${previous.tone}`} onClick={() => advance(-1)} aria-label={t("catalog.previous")}><span>{previous.tag}</span><b>{previous.symbol}</b><ChevronLeft size={18} /></button><article className={`campaign-card ${activeCampaign.tone}`}><div className="campaign-content"><span className="campaign-tag">{activeCampaign.partner && <Megaphone size={13} />}{activeCampaign.tag}</span><h2>{activeCampaign.title}</h2><p>{activeCampaign.text}</p><a href={activeCampaign.href} onClick={activateLink}>{activeCampaign.action} <ArrowRight size={17} /></a></div><div className="campaign-art" aria-hidden="true"><span className="campaign-orb orb-one" /><span className="campaign-orb orb-two" /><span className="campaign-orb orb-three" /><strong>{activeCampaign.symbol}</strong><i /></div></article><button className={`campaign-peek ${next.tone}`} onClick={() => advance(1)} aria-label={t("catalog.next")}><span>{next.tag}</span><b>{next.symbol}</b><ChevronRight size={18} /></button></div><div className="campaign-controls"><div className="campaign-dots" aria-label={t("home.eyebrow")}>{campaigns.map((campaign, index) => <button key={campaign.symbol} className={index === active ? "active" : ""} onClick={() => setActive(index)} aria-label={campaign.tag} aria-current={index === active ? "true" : undefined} />)}</div><button className="campaign-pause" onClick={() => setPaused((value) => !value)} aria-label={paused ? "Play" : "Pause"}>{paused ? <Play size={14} /> : <Pause size={14} />}{paused ? "Play" : "Pause"}</button></div></section>;
}
