import { ArrowRight, ChevronLeft, ChevronRight, Megaphone, Pause, Play } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { backendUrl } from "../lib/backend-url";
import { useI18n } from "../lib/i18n";
import "./campaign-carousel.css";

const copy = {
  pt: [["Cursos Edukangola", "Encontre o curso que pode mudar o seu próximo passo.", "Explore competências em tecnologia, negócios, idiomas, saúde e muito mais.", "Explorar cursos"], ["Aprenda ao seu ritmo", "Vídeo-cursos para aprender onde e quando quiser.", "Conheça cursos em vídeo e avance no seu tempo.", "Ver vídeo-cursos"], ["Construa a sua carreira", "Comece hoje as competências que quer usar amanhã.", "Descubra áreas de aprendizagem para a carreira que quer construir.", "Explorar carreiras"]],
  en: [["Edukangola courses", "Find the course that can change your next step.", "Explore skills in technology, business, languages, health and more.", "Explore courses"], ["Learn at your pace", "Video courses to learn where and when you want.", "Discover video courses and progress on your own time.", "View video courses"], ["Build your career", "Start today with the skills you want to use tomorrow.", "Discover learning areas for the career you want to build.", "Explore careers"]],
  fr: [["Cours Edukangola", "Trouvez le cours qui peut changer votre prochaine étape.", "Explorez des compétences en technologie, affaires, langues, santé et plus encore.", "Explorer les cours"], ["Apprenez à votre rythme", "Des cours vidéo pour apprendre où et quand vous le souhaitez.", "Découvrez des cours vidéo et avancez à votre rythme.", "Voir les cours vidéo"], ["Construisez votre carrière", "Commencez aujourd’hui les compétences que vous utiliserez demain.", "Découvrez les domaines d’apprentissage pour la carrière que vous voulez construire.", "Explorer les carrières"]],
  zh: [["Edukangola 课程", "找到能够改变您下一步的课程。", "探索科技、商业、语言、健康等领域的技能。", "探索课程"], ["按自己的节奏学习", "随时随地学习的视频课程。", "发现视频课程，按自己的节奏进步。", "查看视频课程"], ["构建您的职业生涯", "从今天开始学习您明天想使用的技能。", "探索适合您职业目标的学习领域。", "探索职业方向"]],
};

export default function CampaignCarousel({ onNavigate }) {
  const { language, t } = useI18n();
  const [active, setActive] = useState(0); const [paused, setPaused] = useState(false);
  const campaigns = useMemo(() => copy[language].map((item, index) => ({ tag: item[0], title: item[1], text: item[2], action: item[3], href: index === 1 ? "/cursos?tipo=video" : "/cursos", type: "internal", tone: ["lavender", "gold", "sky"][index], symbol: `0${index + 1}`, partner: false })), [language]);
  const activeCampaign = campaigns[active]; const previous = campaigns[(active - 1 + campaigns.length) % campaigns.length]; const next = campaigns[(active + 1) % campaigns.length]; const reducedMotion = useRef(typeof window !== "undefined" && window.matchMedia("(prefers-reduced-motion: reduce)").matches);
  useEffect(() => { if (paused || reducedMotion.current) return undefined; const timer = window.setInterval(() => setActive((current) => (current + 1) % campaigns.length), 6500); return () => window.clearInterval(timer); }, [paused, campaigns.length]);
  const advance = (direction) => setActive((current) => (current + direction + campaigns.length) % campaigns.length);
  const activateLink = (event) => { if (activeCampaign.type !== "internal" || event.metaKey || event.ctrlKey || event.shiftKey) return; event.preventDefault(); onNavigate(activeCampaign.href); };
  return <section className="campaign-section" aria-label={t("home.eyebrow")}><div className="campaign-rail" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}><button className={`campaign-peek ${previous.tone}`} onClick={() => advance(-1)} aria-label={t("catalog.previous")}><span>{previous.tag}</span><b>{previous.symbol}</b><ChevronLeft size={18} /></button><article className={`campaign-card ${activeCampaign.tone}`}><div className="campaign-content"><span className="campaign-tag">{activeCampaign.partner && <Megaphone size={13} />}{activeCampaign.tag}</span><h2>{activeCampaign.title}</h2><p>{activeCampaign.text}</p><a href={activeCampaign.href} onClick={activateLink}>{activeCampaign.action} <ArrowRight size={17} /></a></div><div className="campaign-art" aria-hidden="true"><span className="campaign-orb orb-one" /><span className="campaign-orb orb-two" /><span className="campaign-orb orb-three" /><strong>{activeCampaign.symbol}</strong><i /></div></article><button className={`campaign-peek ${next.tone}`} onClick={() => advance(1)} aria-label={t("catalog.next")}><span>{next.tag}</span><b>{next.symbol}</b><ChevronRight size={18} /></button></div><div className="campaign-controls"><div className="campaign-dots" aria-label={t("home.eyebrow")}>{campaigns.map((campaign, index) => <button key={campaign.symbol} className={index === active ? "active" : ""} onClick={() => setActive(index)} aria-label={campaign.tag} aria-current={index === active ? "true" : undefined} />)}</div><button className="campaign-pause" onClick={() => setPaused((value) => !value)} aria-label={paused ? "Play" : "Pause"}>{paused ? <Play size={14} /> : <Pause size={14} />}{paused ? "Play" : "Pause"}</button></div></section>;
}
