import { RotateCcw, Search, SlidersHorizontal, X } from "lucide-react";
import { useI18n } from "../lib/i18n";
import "./catalog-filters.css";

function SelectFilter({ label, value, onChange, options, allLabel }) { return <label className="filter-select"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">{allLabel}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }

export default function CatalogFilters({ filters, options, resultCount, totalCount, onChange, onReset }) {
  const { t } = useI18n();
  const activeCount = [filters.tipo, filters.categoria, filters.modalidade, filters.provincia, filters.pagamento, filters.turma].filter(Boolean).length;
  const showClassFilters = filters.tipo !== "video";
  return <section className="catalog-filter-deck" aria-label={t("filters.title")}><div className="catalog-filter-summary"><div><span className="eyebrow muted"><SlidersHorizontal size={14} /> {t("filters.eyebrow")}</span><strong>{t("filters.title")}</strong><small>{resultCount} {t("catalog.of")} {totalCount} {t("filters.class").toLowerCase()}</small></div><button className="reset-filter" onClick={onReset} disabled={!activeCount && !filters.q}><RotateCcw size={15} /> {t("filters.clear")}</button></div><div className="filter-search"><Search size={18} /><input value={filters.q} onChange={(event) => onChange("q", event.target.value)} placeholder={t("filters.search")} aria-label={t("filters.search")} />{filters.q && <button aria-label={t("filters.clear")} onClick={() => onChange("q", "")}><X size={16} /></button>}</div><div className="filter-group"><span className="filter-group-label">{t("filters.area")}</span><div className="filter-category-row" aria-label={t("filters.area")}><button className={!filters.categoria ? "selected" : ""} onClick={() => onChange("categoria", "")}>{t("filters.allAreas")}</button>{options.categorias.map((categoria) => <button className={filters.categoria === categoria ? "selected" : ""} key={categoria} onClick={() => onChange("categoria", categoria)}>{categoria}</button>)}</div></div><div className="filter-controls-row"><SelectFilter label={t("filters.product")} value={filters.tipo} onChange={(value) => onChange("tipo", value)} options={[{ value: "formacao", label: t("filters.class") }, { value: "video", label: t("filters.video") }]} allLabel={t("filters.all")} />{showClassFilters && <SelectFilter label={t("filters.province")} value={filters.provincia} onChange={(value) => onChange("provincia", value)} options={options.provincias.map((item) => ({ value: item, label: item }))} allLabel={t("filters.allF")} />}<SelectFilter label={t("filters.payment")} value={filters.pagamento} onChange={(value) => onChange("pagamento", value)} options={[{ value: "gratuito", label: t("filters.free") }, { value: "sem-pagamento-agora", label: t("filters.noneNow") }, { value: "com-pagamento-agora", label: t("filters.payNow") }]} allLabel={t("filters.all")} />{showClassFilters && <label className="filter-checkbox"><input type="checkbox" checked={filters.turma === "aberta"} onChange={(event) => onChange("turma", event.target.checked ? "aberta" : "")} /><span>{t("filters.openClass")}</span></label>}</div></section>;
}
