import { Building2, Pencil, Plus, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import ManagerBranchCoursesModal from "./ManagerBranchCoursesModal";

const blank = { nome: "", endereco: "", telefone: "", email: "", whatsapp: "", latitude: "", longitude: "", senha: "", ativo: true };
const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

function BranchForm({ item, onClose, onSaved }) {
  const [values, setValues] = useState(item ? { ...blank, ...item, senha: "" } : blank); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (field, value) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(item ? `/backend/gestoreduka/api/react/filiais/${item.id}/` : "/backend/gestoreduka/api/react/filiais/", { method: item ? "PATCH" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar a filial."); onSaved(payload.filial); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">{item ? "Editar filial" : "Nova filial"}</span><h2>{item ? item.nome : "Criar filial"}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><div className="manager-form-grid"><label><span>Nome</span><input required value={values.nome} onChange={(event) => update("nome", event.target.value)} /></label><label><span>E-mail institucional</span><input required type="email" value={values.email} onChange={(event) => update("email", event.target.value)} /></label><label className="wide"><span>Endereço</span><input required value={values.endereco} onChange={(event) => update("endereco", event.target.value)} /></label><label><span>Telefone</span><input required value={values.telefone} onChange={(event) => update("telefone", event.target.value)} /></label><label><span>WhatsApp</span><input value={values.whatsapp} onChange={(event) => update("whatsapp", event.target.value)} /></label><label><span>Latitude</span><input type="number" step="any" value={values.latitude} onChange={(event) => update("latitude", event.target.value)} /></label><label><span>Longitude</span><input type="number" step="any" value={values.longitude} onChange={(event) => update("longitude", event.target.value)} /></label><label className="wide"><span>{item ? "Nova palavra-passe do gestor (opcional)" : "Palavra-passe inicial do gestor"}</span><input required={!item} minLength="8" type="password" value={values.senha} onChange={(event) => update("senha", event.target.value)} /></label></div>{item && <div className="manager-checks"><label><input type="checkbox" checked={values.ativo} onChange={(event) => update("ativo", event.target.checked)} />Filial activa</label></div>}{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : item ? "Guardar alterações" : "Criar filial"}</button></footer></form></div>;
}

export default function ManagerBranchesPanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [modal, setModal] = useState(null); const [coursesBranch, setCoursesBranch] = useState(null);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/filiais/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar as filiais."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const remove = async (item) => { if (!window.confirm(`Remover a filial “${item.nome}” e a respectiva conta de gestor?`)) return; try { const response = await fetch(`/backend/gestoreduka/api/react/filiais/${item.id}/`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível remover a filial."); load(); } catch (reason) { setError(reason.message); } };
  if (error && !data) return <section id="filiais" className="manager-courses manager-branches"><h2>Filiais</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="filiais" className="manager-courses manager-branches"><p>A preparar as filiais…</p></section>;
  return <section id="filiais" className="manager-courses manager-branches"><div><span className="manager-eyebrow">Expansão do centro</span><h2>Filiais</h2></div><button className="manager-create-course" onClick={() => setModal("new")}><Plus size={15}/> Criar filial</button>{error && <p className="manager-form-error">{error}</p>}<div className="manager-course-list">{data.filiais.length ? data.filiais.map((item) => <article key={item.id}><div><strong>{item.nome}</strong><span>{item.endereco} · {item.gestor_email}</span></div><span className={item.ativo ? "published" : "draft"}>{item.ativo ? "Activa" : "Inactiva"}</span><button onClick={() => setCoursesBranch(item)}>Cursos</button><button onClick={() => setModal(item)} aria-label={`Editar ${item.nome}`}><Pencil size={16}/></button><button className="manager-course-delete" onClick={() => remove(item)} aria-label={`Remover ${item.nome}`}><Trash2 size={16}/></button></article>) : <p className="manager-empty-state"><Building2 size={16}/> Não existem filiais registadas.</p>}</div>{modal && <BranchForm item={modal === "new" ? null : modal} onClose={() => setModal(null)} onSaved={() => { setModal(null); load(); }} />}{coursesBranch && <ManagerBranchCoursesModal branch={coursesBranch} onClose={() => setCoursesBranch(null)} onSaved={() => { setCoursesBranch(null); load(); }} />}</section>;
}
