import { MessageCircle, Send } from "lucide-react";
import { useEffect, useState } from "react";
import { authRequest } from "../lib/auth-api";
import { backendUrl } from "../lib/backend-url";
import "./manager-chat-panel.css";

export default function ManagerChatPanel() {
  const [conversations, setConversations] = useState(null); const [selected, setSelected] = useState(() => Number(new URLSearchParams(window.location.search).get("conversa")) || null); const [detail, setDetail] = useState(null); const [text, setText] = useState(""); const [error, setError] = useState(""); const [sending, setSending] = useState(false); const [unreadTotal, setUnreadTotal] = useState(0);
  const loadList = async () => { try { const response = await fetch(backendUrl("/gestoreduka/api/react/conversas/"), { credentials: "include", cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar as conversas."); setConversations(payload.conversas); setUnreadTotal(payload.total_nao_lidas || 0); setSelected((current) => current && payload.conversas.some((item) => item.id === current) ? current : (payload.conversas[0]?.id || null)); } catch (reason) { setError(reason.message); } };
  const loadConversation = async (id) => { if (!id) return; try { const response = await fetch(backendUrl(`/gestoreduka/api/react/conversas/${id}/`), { credentials: "include" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar a conversa."); setDetail(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { loadList(); const polling = window.setInterval(loadList, 15000); return () => window.clearInterval(polling); }, []); useEffect(() => { if (!selected) return undefined; loadConversation(selected); const polling = window.setInterval(() => loadConversation(selected), 15000); return () => window.clearInterval(polling); }, [selected]);
  const send = async (event) => { event.preventDefault(); if (!text.trim() || !selected) return; setSending(true); setError(""); try { await authRequest(`/gestoreduka/api/react/conversas/${selected}/mensagens/`, { mensagem: text }); setText(""); await loadConversation(selected); await loadList(); } catch (reason) { setError(reason.message); } finally { setSending(false); } };
  if (error && !conversations) return <section id="chat" className="manager-courses manager-chat"><h2>Mensagens</h2><p className="manager-form-error">{error}</p></section>;
  if (!conversations) return <section id="chat" className="manager-courses manager-chat"><p>A preparar conversas…</p></section>;
  return <section id="chat" className="manager-courses manager-chat"><header className="manager-chat-heading"><div><span className="manager-eyebrow">Atendimento</span><h2>Conversas com alunos</h2><p>Responda a dúvidas e acompanhe os pedidos dos alunos num espaço de atendimento directo.</p></div><div><MessageCircle size={17}/><strong>{conversations.length}</strong><span>{unreadTotal ? `${unreadTotal} por ler` : "conversas activas"}</span></div></header><div className="manager-chat-layout"><aside className="manager-chat-sidebar"><header><strong>Conversas recentes</strong><span>{unreadTotal || conversations.length}</span></header>{conversations.length ? conversations.map((item) => <button className={selected === item.id ? "active" : ""} key={item.id} onClick={() => setSelected(item.id)}><span className="manager-chat-avatar">{item.aluno.charAt(0)}</span><div><strong>{item.aluno}</strong><span>{item.ultima_mensagem || "Sem mensagens"}</span></div>{item.nao_lidas > 0 && <b className="manager-chat-unread">{item.nao_lidas}</b>}</button>) : <p className="manager-empty-state">Ainda não existem conversas activas.</p>}</aside><div className="manager-chat-thread">{detail ? <><header className="manager-chat-thread-header"><span className="manager-chat-avatar">{detail.conversa.aluno.charAt(0)}</span><div><strong>{detail.conversa.aluno}</strong><span>Conversa com o centro · actualiza automaticamente</span></div></header><div className="manager-chat-messages">{detail.mensagens.map((message) => <article key={message.id} className={message.autor === "CENTRO" ? "from-center" : "from-student"}><p>{message.texto}</p><small>{message.autor === "CENTRO" ? "Centro · " : "Aluno · "}{new Date(message.data).toLocaleString("pt-AO")}</small></article>)}</div><form className="manager-chat-composer" onSubmit={send}><input placeholder="Escreva uma resposta ao aluno…" value={text} onChange={(event) => setText(event.target.value)} /><button className="primary" disabled={sending} aria-label="Enviar mensagem"><Send size={16}/><span>{sending ? "A enviar…" : "Enviar"}</span></button></form></> : <p className="manager-empty-state"><MessageCircle size={18}/> Selecione uma conversa para responder.</p>}</div></div>{error && <p className="manager-form-error">{error}</p>}</section>;
}
