import { ImagePlus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

export default function ManagerGalleryPanel() {
  const [gallery, setGallery] = useState(null); const [category, setCategory] = useState("OUTRO"); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/perfil/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar a galeria."); setGallery(payload.galeria); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const upload = async (file) => { if (!file) return; setUploading(true); setError(""); const body = new FormData(); body.append("imagem", file); body.append("categoria", category); try { const response = await fetch("/backend/gestoreduka/api/react/perfil/galeria/", { method: "POST", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() }, body }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível adicionar a imagem."); setGallery((current) => [...current, payload.imagem]); } catch (reason) { setError(reason.message); } finally { setUploading(false); } };
  const remove = async (image) => { if (!window.confirm("Remover esta imagem da galeria pública?")) return; setError(""); try { const response = await fetch(`/backend/gestoreduka/api/react/perfil/galeria/${image.id}/`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível remover a imagem."); setGallery((current) => current.filter((item) => item.id !== image.id)); } catch (reason) { setError(reason.message); } };
  if (error && !gallery) return <section id="galeria" className="manager-courses manager-gallery"><h2>Galeria pública</h2><p className="manager-form-error">{error}</p><button onClick={() => { setError(""); load(); }}>Tentar novamente</button></section>;
  if (!gallery) return <section id="galeria" className="manager-courses manager-gallery"><p>A preparar a galeria…</p></section>;
  return <section id="galeria" className="manager-courses manager-gallery"><div><span className="manager-eyebrow">Presença pública</span><h2>Galeria do centro</h2></div><div className="manager-gallery-toolbar"><label><span>Categoria</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="SALAS">Salas de aula</option><option value="LABS">Laboratórios</option><option value="EVENTOS">Eventos</option><option value="OUTRO">Outro</option></select></label><label className="manager-gallery-upload"><ImagePlus size={16}/>{uploading ? "A enviar…" : "Adicionar imagem"}<input type="file" accept="image/*" disabled={uploading} onChange={(event) => upload(event.target.files?.[0])}/></label></div>{error && <p className="manager-form-error">{error}</p>}<div className="manager-gallery-grid">{gallery.length ? gallery.map((image) => <article key={image.id}><img src={image.url} alt={image.titulo || "Imagem da galeria"}/><button onClick={() => remove(image)} aria-label="Remover imagem"><Trash2 size={15}/></button></article>) : <p className="manager-empty-state">Ainda não existem imagens na galeria pública.</p>}</div></section>;
}
