import { CalendarDays, Pencil, Plus, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";

const blank = { titulo: "", descricao: "", data_inicio: "", data_fim: "", local: "", tipo: "", link_inscricao: "", destaque: false };
const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";
const localInput = (value) => value ? new Date(value).toISOString().slice(0, 16) : "";

function EventForm({ types, item, onClose, onSaved }) {
  const [values, setValues] = useState(item ? { ...blank, ...item, data_inicio: localInput(item.data_inicio), data_fim: localInput(item.data_fim) } : blank); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (field, value) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(item ? `/backend/gestoreduka/api/react/eventos/${item.id}/` : "/backend/gestoreduka/api/react/eventos/", { method: item ? "PATCH" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar o evento."); onSaved(payload.evento); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">{item ? "Editar evento" : "Novo evento"}</span><h2>{item ? item.titulo : "Criar evento"}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><div className="manager-form-grid"><label className="wide"><span>Título</span><input required value={values.titulo} onChange={(event) => update("titulo", event.target.value)} /></label><label className="wide"><span>Descrição</span><textarea required rows="4" value={values.descricao} onChange={(event) => update("descricao", event.target.value)} /></label><label><span>Tipo</span><select required value={values.tipo} onChange={(event) => update("tipo", event.target.value)}><option value="">Selecionar tipo</option>{types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><label><span>Local</span><input required value={values.local} onChange={(event) => update("local", event.target.value)} /></label><label><span>Início</span><input required type="datetime-local" value={values.data_inicio} onChange={(event) => update("data_inicio", event.target.value)} /></label><label><span>Fim</span><input type="datetime-local" value={values.data_fim} onChange={(event) => update("data_fim", event.target.value)} /></label><label className="wide"><span>Ligação de inscrição</span><input type="url" value={values.link_inscricao} onChange={(event) => update("link_inscricao", event.target.value)} /></label></div><div className="manager-checks"><label><input type="checkbox" checked={values.destaque} onChange={(event) => update("destaque", event.target.checked)} />Destacar este evento</label></div>{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : "Guardar evento"}</button></footer></form></div>;
}

export default function ManagerEventsPanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [modal, setModal] = useState(null);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/eventos/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os eventos."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const remove = async (item) => { if (!window.confirm(`Remover o evento “${item.titulo}”?`)) return; try { const response = await fetch(`/backend/gestoreduka/api/react/eventos/${item.id}/`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível remover o evento."); load(); } catch (reason) { setError(reason.message); } };
  if (error && !data) return <section id="eventos" className="manager-courses manager-events"><h2>Eventos</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="eventos" className="manager-courses manager-events"><p>A preparar eventos…</p></section>;
  return <section id="eventos" className="manager-courses manager-events"><div><span className="manager-eyebrow">Agenda do centro</span><h2>Eventos</h2></div><button className="manager-create-course" onClick={() => setModal("new")}><Plus size={15}/> Criar evento</button>{error && <p className="manager-form-error">{error}</p>}<div className="manager-course-list">{data.eventos.length ? data.eventos.map((item) => <article key={item.id}><div><strong>{item.titulo}</strong><span><CalendarDays size={13}/> {new Date(item.data_inicio).toLocaleDateString("pt-AO")} · {item.local}</span></div><span className={item.destaque ? "published" : "draft"}>{item.tipo}</span><button onClick={() => setModal(item)} aria-label={`Editar ${item.titulo}`}><Pencil size={16}/></button><button className="manager-course-delete" onClick={() => remove(item)} aria-label={`Remover ${item.titulo}`}><Trash2 size={16}/></button></article>) : <p className="manager-empty-state">Ainda não existem eventos publicados por este centro.</p>}</div>{modal && <EventForm types={data.tipos} item={modal === "new" ? null : modal} onClose={() => setModal(null)} onSaved={() => { setModal(null); load(); }} />}</section>;
}
