import { useMemo, useState } from "react";
import { X } from "lucide-react";

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";
const initial = { nome: "", email: "", curso_id: "", turma_id: "", origem: "PRESENCIAL", forma_pagamento: "DINHEIRO", valor_acordado: "", desconto: "0", pagamento_confirmado: false };

export default function ManagerManualEnrollmentForm({ metadata, onClose, onSaved }) {
  const [values, setValues] = useState(initial); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const classes = useMemo(() => metadata.turmas.filter((item) => String(item.curso_id) === values.curso_id), [metadata.turmas, values.curso_id]);
  const update = (field, value) => setValues((current) => ({ ...current, [field]: value }));
  const selectCourse = (courseId) => { const course = metadata.cursos.find((item) => String(item.id) === courseId); setValues((current) => ({ ...current, curso_id: courseId, turma_id: "", valor_acordado: course ? current.valor_acordado : "" })); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/backend/gestoreduka/api/react/inscricoes/manual/", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível criar a matrícula presencial."); onSaved(payload); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">Atendimento presencial</span><h2>Nova matrícula</h2></div><button type="button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header><div className="manager-form-grid"><label><span>Nome completo</span><input required value={values.nome} onChange={(event) => update("nome", event.target.value)} /></label><label><span>E-mail do aluno</span><input required type="email" value={values.email} onChange={(event) => update("email", event.target.value)} /></label><label><span>Curso</span><select required value={values.curso_id} onChange={(event) => selectCourse(event.target.value)}><option value="">Selecionar curso</option>{metadata.cursos.map((item) => <option key={item.id} value={item.id}>{item.titulo}</option>)}</select></label><label><span>Turma disponível</span><select required disabled={!values.curso_id} value={values.turma_id} onChange={(event) => update("turma_id", event.target.value)}><option value="">Selecionar turma</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.nome} · {item.vagas_disponiveis} vagas</option>)}</select></label><label><span>Origem</span><select value={values.origem} onChange={(event) => update("origem", event.target.value)}>{metadata.origens_matricula.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label><span>Forma de pagamento</span><select value={values.forma_pagamento} onChange={(event) => update("forma_pagamento", event.target.value)}>{metadata.formas_pagamento.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label><span>Valor acordado (Kz)</span><input required min="0" step="0.001" type="number" value={values.valor_acordado} onChange={(event) => update("valor_acordado", event.target.value)} /></label><label><span>Desconto (Kz)</span><input min="0" step="0.001" type="number" value={values.desconto} onChange={(event) => update("desconto", event.target.value)} /></label></div><div className="manager-checks"><label><input type="checkbox" checked={values.pagamento_confirmado} onChange={(event) => update("pagamento_confirmado", event.target.checked)} />Pagamento confirmado no atendimento</label></div>{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : "Criar matrícula"}</button></footer></form></div>;
}
