import { BookOpenCheck, CheckCircle2, ChevronRight, FileText, GraduationCap, Mail, Search, UserRound, UsersRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import "./manager-students-panel.css";

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=").slice(1).join("=") || "";
const initials = (name = "") => name.split(" ").filter(Boolean).slice(0, 2).map((word) => word[0]).join("").toUpperCase() || "A";
const recordTone = (state = "") => state.toLowerCase().replaceAll(" ", "-");

function Dossier({ detail, onClose, onChangeRecord }) {
  const enrollments = detail.inscricoes || [];
  const records = detail.matriculas || [];
  const activeRecords = records.filter((item) => item.estado === "ATIVA").length;
  return <div className="manager-dossier-overlay" role="dialog" aria-modal="true" aria-label={`Dossiê de ${detail.aluno.nome}`}><section className="manager-dossier">
    <header className="manager-dossier-hero"><div className="manager-dossier-profile"><span>{initials(detail.aluno.nome)}</span><div><p>Dossiê académico</p><h2>{detail.aluno.nome}</h2><small><Mail size={13} /> {detail.aluno.email || "E-mail não disponível"}</small></div></div><button type="button" className="manager-dossier-close" onClick={onClose} aria-label="Fechar dossiê"><X size={19}/></button></header>
    <div className="manager-dossier-metrics"><article><BookOpenCheck size={17}/><div><strong>{enrollments.length}</strong><span>Inscrições</span></div></article><article><GraduationCap size={17}/><div><strong>{records.length}</strong><span>Matrículas</span></div></article><article><CheckCircle2 size={17}/><div><strong>{activeRecords}</strong><span>Activas</span></div></article></div>
    <div className="manager-dossier-content"><section className="manager-dossier-section"><div className="manager-dossier-heading"><div><span>Pedidos de inscrição</span><h3>Histórico de admissões</h3></div><small>{enrollments.length} registos</small></div>{enrollments.length ? <div className="manager-dossier-timeline">{enrollments.map((item) => <article key={`i-${item.id}`}><i><FileText size={14}/></i><div><strong>{item.curso}</strong><span>Inscrição <b className={`manager-dossier-status ${recordTone(item.status)}`}>{item.status}</b>{item.turma ? ` · ${item.turma}` : " · Sem turma"}</span></div></article>)}</div> : <div className="manager-dossier-empty"><FileText size={20}/><p>Este aluno ainda não tem pedidos de inscrição neste centro.</p></div>}</section>
      <section className="manager-dossier-section"><div className="manager-dossier-heading"><div><span>Registo académico</span><h3>Matrículas e percurso</h3></div><small>{records.length} registos</small></div>{records.length ? <div className="manager-dossier-records">{records.map((item) => <article key={`m-${item.id}`}><div className="manager-dossier-record-copy"><span className={`manager-dossier-course-icon ${recordTone(item.estado)}`}><GraduationCap size={16}/></span><div><strong>{item.curso}</strong><p>{item.codigo} <b>·</b> {item.turma || "Turma ainda não atribuída"}</p></div></div><div className="manager-dossier-record-actions"><span className={`manager-dossier-status ${recordTone(item.estado)}`}>{item.estado}</span><div>{item.estado === "ATIVA" && <button type="button" onClick={() => onChangeRecord(item, "suspender")}>Suspender</button>}{item.estado === "SUSPENSA" && <button type="button" onClick={() => onChangeRecord(item, "reativar")}>Reactivar</button>}{item.estado === "ATIVA" && <button type="button" onClick={() => onChangeRecord(item, "concluir")}>Concluir</button>}{item.estado !== "CANCELADA" && <button type="button" className="danger" onClick={() => onChangeRecord(item, "cancelar")}>Cancelar</button>}</div></div></article>)}</div> : <div className="manager-dossier-empty"><GraduationCap size={20}/><p>Ainda não existem matrículas activas ou históricas deste aluno.</p></div>}</section>
    </div>
  </section></div>;
}

export default function ManagerStudentsPanel() {
  const [query, setQuery] = useState("");
  const [students, setStudents] = useState(null);
  const [detail, setDetail] = useState(null);
  const [error, setError] = useState("");
  const load = async (value = "") => { try { const response = await fetch(`/backend/gestoreduka/api/react/alunos/?q=${encodeURIComponent(value)}`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os alunos."); setStudents(payload.alunos); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const open = async (student) => { setError(""); try { const response = await fetch(`/backend/gestoreduka/api/react/alunos/${student.id}/`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível abrir o dossiê."); setDetail(payload); } catch (reason) { setError(reason.message); } };
  const changeRecord = async (record, action) => { if (action === "cancelar" && !window.confirm(`Cancelar a matrícula ${record.codigo}?`)) return; try { const response = await fetch(`/backend/gestoreduka/api/react/matriculas/${record.id}/`, { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify({ action }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível actualizar a matrícula."); open(detail.aluno); } catch (reason) { setError(reason.message); } };
  if (error && !students) return <section className="manager-students-panel manager-students-feedback"><h2>Alunos e dossiês</h2><p className="manager-form-error">{error}</p><button onClick={() => { setError(""); load(); }}>Tentar novamente</button></section>;
  if (!students) return <section className="manager-students-panel manager-students-feedback"><p>A preparar o acompanhamento académico…</p></section>;
  return <section className="manager-students-panel"><header className="manager-students-hero"><div><span className="manager-eyebrow">Acompanhamento académico</span><h2>Alunos e dossiês</h2><p>Pesquise cada aluno e acompanhe inscrições, matrículas e o percurso no centro.</p></div><span className="manager-students-total"><UsersRound size={17}/><b>{students.length}</b> {students.length === 1 ? "aluno" : "alunos"}</span></header><form className="manager-students-search" onSubmit={(event) => { event.preventDefault(); load(query); }}><Search size={18}/><input placeholder="Pesquisar por nome ou e-mail" value={query} onChange={(event) => setQuery(event.target.value)} /><button className="primary">Pesquisar</button></form>{error && <p className="manager-form-error manager-students-error">{error}</p>}<div className="manager-students-list">{students.map((student) => <article key={student.id}><span className="manager-student-avatar">{initials(student.nome)}</span><div className="manager-student-copy"><strong>{student.nome}</strong><span><Mail size={13}/>{student.email || "E-mail não disponível"}</span></div><button type="button" onClick={() => open(student)}>Abrir dossiê <ChevronRight size={15}/></button></article>)}{!students.length && <div className="manager-students-empty"><UserRound size={25}/><strong>Nenhum aluno encontrado</strong><p>{query ? "Tente outro nome ou e-mail." : "Os alunos com inscrição ou matrícula no centro aparecerão nesta área."}</p></div>}</div>{detail && <Dossier detail={detail} onClose={() => setDetail(null)} onChangeRecord={changeRecord} />}</section>;
}
