import { CalendarDays, MapPin, Pencil, Plus, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import "./manager-opportunities.css";

const blank = { titulo: "", descricao: "", data_inicio: "", data_fim: "", local: "", tipo: "", link_inscricao: "", destaque: false };
const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";
const localInput = (value) => value ? new Date(value).toISOString().slice(0, 16) : "";

function EventForm({ types, item, onClose, onSaved, independente }) {
  const [values, setValues] = useState(item ? { ...blank, ...item, data_inicio: localInput(item.data_inicio), data_fim: localInput(item.data_fim) } : blank); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (field, value) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const base = independente ? "/backend/gestoreduka/api/react/eventos-independente/" : "/backend/gestoreduka/api/react/eventos/"; const url = item ? `${base}${item.id}/` : base; const response = await fetch(url, { method: item ? "PATCH" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar o evento."); onSaved(payload.evento); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">{item ? "Editar evento" : "Novo evento"}</span><h2>{item ? item.titulo : "Criar evento"}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><div className="manager-form-grid"><label className="wide"><span>Título</span><input required value={values.titulo} onChange={(event) => update("titulo", event.target.value)} /></label><label className="wide"><span>Descrição</span><textarea required rows="4" value={values.descricao} onChange={(event) => update("descricao", event.target.value)} /></label><label><span>Tipo</span><select required value={values.tipo} onChange={(event) => update("tipo", event.target.value)}><option value="">Selecionar tipo</option>{types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><label><span>Local</span><input required value={values.local} onChange={(event) => update("local", event.target.value)} /></label><label><span>Início</span><input required type="datetime-local" value={values.data_inicio} onChange={(event) => update("data_inicio", event.target.value)} /></label><label><span>Fim</span><input type="datetime-local" value={values.data_fim} onChange={(event) => update("data_fim", event.target.value)} /></label><label className="wide"><span>Ligação de inscrição</span><input type="url" value={values.link_inscricao} onChange={(event) => update("link_inscricao", event.target.value)} /></label></div><div className="manager-checks"><label><input type="checkbox" checked={values.destaque} onChange={(event) => update("destaque", event.target.checked)} />Destacar este evento</label></div>{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : "Guardar evento"}</button></footer></form></div>;
}

export default function ManagerEventsPanel({ independente = false }) {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [modal, setModal] = useState(null);
  const apiUrl = independente ? "/backend/gestoreduka/api/react/eventos-independente/" : "/backend/gestoreduka/api/react/eventos/";
  const load = async () => { try { const response = await fetch(apiUrl, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os eventos."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const remove = async (item) => { if (!window.confirm(`Remover o evento "${item.titulo}"?`)) return; try { const response = await fetch(`${apiUrl}${item.id}/`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível remover o evento."); load(); } catch (reason) { setError(reason.message); } };
  if (error && !data) return <section id="eventos" className="manager-courses manager-events"><h2>Eventos</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="eventos" className="manager-courses manager-events"><p>A preparar eventos…</p></section>;
  const eyebrowLabel = independente ? "Eventos da organização" : "Agenda do centro";
  const emptyLabel = independente ? "Ainda não existem eventos publicados por esta organização." : "Ainda não existem eventos publicados por este centro.";
  return <section id="eventos" className="manager-courses manager-events"><header className="manager-opportunities-heading"><div><span className="manager-eyebrow">{eyebrowLabel}</span><h2>Eventos</h2><p>Organize encontros, aulas abertas e actividades que aproximam a comunidade.</p></div><span>{data.eventos.length} na agenda</span></header><button className="manager-create-course" onClick={() => setModal("new")}><Plus size={15}/> Criar evento</button>{error && <p className="manager-form-error">{error}</p>}<div className="manager-event-grid">{data.eventos.length ? data.eventos.map((item) => { const dataInicio = new Date(item.data_inicio); return <article key={item.id} className="manager-event-card"><div className="manager-event-date"><strong>{String(dataInicio.getDate()).padStart(2, "0")}</strong><span>{dataInicio.toLocaleDateString("pt-AO", { month: "short" }).replace(".", "")}</span></div><div className="manager-event-copy"><div><small>{item.tipo.replaceAll("_", " ")}</small><h3>{item.titulo}</h3></div><p><MapPin size={13}/>{item.local}</p><span><CalendarDays size={13}/>{dataInicio.toLocaleDateString("pt-AO", { weekday: "long", day: "numeric", month: "long" })}</span></div><div className="manager-event-actions"><span className={item.destaque ? "is-featured" : ""}>{item.destaque ? "Destaque" : "Agenda"}</span><div><button onClick={() => setModal(item)} aria-label={`Editar ${item.titulo}`}><Pencil size={16}/></button><button className="manager-course-delete" onClick={() => remove(item)} aria-label={`Remover ${item.titulo}`}><Trash2 size={16}/></button></div></div></article>; }) : <p className="manager-empty-state">{emptyLabel}</p>}</div>{modal && <EventForm types={data.tipos} item={modal === "new" ? null : modal} onClose={() => setModal(null)} onSaved={() => { setModal(null); load(); }} independente={independente} />}</section>;
}
