import { Pencil, Plus, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import ManagerAnnouncementsPanel from "./ManagerAnnouncementsPanel";
import ManagerBranchesPanel from "./ManagerBranchesPanel";
import ManagerChatPanel from "./ManagerChatPanel";
import ManagerEventsPanel from "./ManagerEventsPanel";
import ManagerFinancePanel from "./ManagerFinancePanel";
import ManagerVideoCoursesPanel from "./ManagerVideoCoursesPanel";

const blank = { nome: "", email: "", titulo: "", biografia: "", area_especializacao: "", ativo: true };
const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

function InstructorForm({ meta, item, onClose, onSaved }) {
  const [values, setValues] = useState(item ? { ...blank, ...item } : blank); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (field, value) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(item ? `/backend/gestoreduka/api/react/formadores/${item.id}/` : "/backend/gestoreduka/api/react/formadores/", { method: item ? "PATCH" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar o formador."); onSaved(payload.instrutor); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">{item ? "Editar formador" : "Novo formador"}</span><h2>{item ? item.nome : "Adicionar formador"}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><div className="manager-form-grid"><label><span>Nome completo</span><input required value={values.nome} onChange={(event) => update("nome", event.target.value)} /></label><label><span>E-mail</span><input required type="email" value={values.email} onChange={(event) => update("email", event.target.value)} /></label><label><span>Título profissional</span><input value={values.titulo} onChange={(event) => update("titulo", event.target.value)} /></label><label><span>Área de especialização</span><select required value={values.area_especializacao} onChange={(event) => update("area_especializacao", event.target.value)}><option value="">Selecionar área</option>{meta.areas.map((area) => <option key={area.value} value={area.value}>{area.label}</option>)}</select></label><label className="wide"><span>Biografia</span><textarea required rows="4" value={values.biografia} onChange={(event) => update("biografia", event.target.value)} /></label></div>{item && <div className="manager-checks"><label><input type="checkbox" checked={values.ativo} onChange={(event) => update("ativo", event.target.checked)} />Formador activo</label></div>}{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : item ? "Guardar alterações" : "Criar formador"}</button></footer></form></div>;
}

export default function ManagerInstructorsPanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [modal, setModal] = useState(null);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/formadores/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os formadores."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  if (error && !data) return <section id="formadores" className="manager-courses manager-instructors"><h2>Formadores</h2><p className="manager-form-error">{error}</p><button onClick={() => { setError(""); load(); }}>Tentar novamente</button></section>;
  if (!data) return <section id="formadores" className="manager-courses manager-instructors"><p>A preparar os formadores…</p></section>;
  return <><section id="formadores" className="manager-courses manager-instructors"><div><span className="manager-eyebrow">Equipa pedagógica</span><h2>Formadores</h2></div><button className="manager-create-course" onClick={() => setModal("new")}><Plus size={15}/> Adicionar</button>{error && <p className="manager-form-error">{error}</p>}<div className="manager-course-list">{data.instrutores.length ? data.instrutores.map((item) => <article key={item.id}><div><strong>{item.nome}</strong><span>{item.titulo || item.area_especializacao}</span></div><span className={item.ativo ? "published" : "draft"}>{item.ativo ? "Activo" : "Inactivo"}</span><button onClick={() => setModal(item)} aria-label={`Editar ${item.nome}`}><Pencil size={16}/></button></article>) : <p className="manager-empty-state"><UserRound size={16}/> Ainda não existem formadores associados ao centro.</p>}</div>{modal && <InstructorForm meta={data} item={modal === "new" ? null : modal} onClose={() => setModal(null)} onSaved={() => { setModal(null); load(); }} />}</section><ManagerBranchesPanel /><ManagerVideoCoursesPanel /><ManagerEventsPanel /><ManagerFinancePanel /><ManagerChatPanel /><ManagerAnnouncementsPanel /></>;
}
