import { Award, Check, Clock3, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const labels = { P: "Pendente", A: "Aceite", N: "Negada", C: "Cancelada" };
const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

export default function ManagerEnrollmentsPanel() {
  const [data, setData] = useState(null); const [filter, setFilter] = useState(""); const [error, setError] = useState(""); const [updating, setUpdating] = useState(null);
  const load = async () => { try { const response = await fetch(`/backend/gestoreduka/api/react/inscricoes/${filter ? `?status=${filter}` : ""}`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar as inscrições."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, [filter]);
  const update = async (item, status) => { setUpdating(item.id); try { const response = await fetch(`/backend/gestoreduka/api/react/inscricoes/${item.id}/`, { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify({ status }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível actualizar a inscrição."); await load(); } catch (reason) { setError(reason.message); } finally { setUpdating(null); } };
  const issueCertificate = async (item) => { setUpdating(item.id); setError(""); try { const response = await fetch(`/backend/gestoreduka/api/react/inscricoes/${item.id}/certificado/`, { method: "POST", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível emitir o certificado."); setError(`Certificado ${payload.criado ? "emitido" : "já existente"}: ${payload.certificado.codigo_verificacao}.`); } catch (reason) { setError(reason.message); } finally { setUpdating(null); } };
  const metrics = useMemo(() => data ? [["Total", data.metricas.total], ["Pendentes", data.metricas.pendentes], ["Aceites", data.metricas.aceites], ["Negadas", data.metricas.negadas]] : [], [data]);
  if (error && !data) return <section id="inscricoes" className="manager-courses manager-enrollments"><h2>Inscrições</h2><p className="manager-form-error">{error}</p><button onClick={() => { setError(""); load(); }}>Tentar novamente</button></section>;
  if (!data) return <section id="inscricoes" className="manager-courses manager-enrollments"><p>A preparar inscrições…</p></section>;
  return <section id="inscricoes" className="manager-courses manager-enrollments"><div><span className="manager-eyebrow">Admissões</span><h2>Inscrições e alunos</h2></div><div className="manager-enrollment-metrics">{metrics.map(([label, value]) => <article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><div className="manager-enrollment-toolbar"><label><span>Estado</span><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Todas as inscrições</option>{data.escolhas.status.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{data.permissoes.inscricao_manual ? <span className="manager-permission-note">O plano permite matrícula presencial.</span> : <span className="manager-permission-note">A matrícula presencial não está disponível no plano actual.</span>}</div>{error && <p className="manager-form-error">{error}</p>}<div className="manager-enrollment-list">{data.inscricoes.length ? data.inscricoes.map((item) => <article key={item.id}><div><strong>{item.aluno}</strong><span>{item.curso} · {item.turma}</span><small>{item.codigo || "Sem código"} · {item.tipo}</small></div><span className={`manager-enrollment-status is-${item.status}`}>{labels[item.status]}</span><span className="manager-enrollment-payment">{Number(item.valor_pago).toLocaleString("pt-AO")} Kz</span><div className="manager-enrollment-actions">{item.status === "P" && <><button disabled={updating === item.id} onClick={() => update(item, "A")}><Check size={15}/> Aceitar</button><button className="reject" disabled={updating === item.id} onClick={() => update(item, "N")}><X size={15}/> Recusar</button></>}{item.status === "A" && <button disabled={updating === item.id} onClick={() => issueCertificate(item)}><Award size={15}/> Certificado</button>}{item.status !== "P" && item.status !== "A" && <span><Clock3 size={14}/> {labels[item.status]}</span>}</div></article>) : <p className="manager-empty-state">Não existem inscrições com este estado.</p>}</div></section>;
}
