import { MessageCircle, Send } from "lucide-react";
import { useEffect, useState } from "react";

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

export default function ManagerChatPanel() {
  const [conversations, setConversations] = useState(null); const [selected, setSelected] = useState(null); const [detail, setDetail] = useState(null); const [text, setText] = useState(""); const [error, setError] = useState(""); const [sending, setSending] = useState(false);
  const loadList = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/conversas/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar as conversas."); setConversations(payload.conversas); if (!selected && payload.conversas[0]) setSelected(payload.conversas[0].id); } catch (reason) { setError(reason.message); } };
  const loadConversation = async (id) => { if (!id) return; try { const response = await fetch(`/backend/gestoreduka/api/react/conversas/${id}/`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar a conversa."); setDetail(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { loadList(); }, []); useEffect(() => { loadConversation(selected); }, [selected]);
  const send = async (event) => { event.preventDefault(); if (!text.trim() || !selected) return; setSending(true); setError(""); try { const response = await fetch(`/backend/gestoreduka/api/react/conversas/${selected}/mensagens/`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify({ mensagem: text }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível enviar a mensagem."); setText(""); await loadConversation(selected); await loadList(); } catch (reason) { setError(reason.message); } finally { setSending(false); } };
  if (error && !conversations) return <section id="chat" className="manager-courses manager-chat"><h2>Mensagens</h2><p className="manager-form-error">{error}</p></section>;
  if (!conversations) return <section id="chat" className="manager-courses manager-chat"><p>A preparar conversas…</p></section>;
  return <section id="chat" className="manager-courses manager-chat"><div><span className="manager-eyebrow">Atendimento</span><h2>Conversas com alunos</h2></div><div className="manager-chat-layout"><aside>{conversations.length ? conversations.map((item) => <button className={selected === item.id ? "active" : ""} key={item.id} onClick={() => setSelected(item.id)}><strong>{item.aluno}</strong><span>{item.ultima_mensagem || "Sem mensagens"}</span></button>) : <p className="manager-empty-state">Ainda não existem conversas activas.</p>}</aside><div className="manager-chat-thread">{detail ? <><header><strong>{detail.conversa.aluno}</strong></header><div className="manager-chat-messages">{detail.mensagens.map((message) => <article key={message.id} className={message.autor === "CENTRO" ? "from-center" : "from-student"}><p>{message.texto}</p><small>{new Date(message.data).toLocaleString("pt-AO")}</small></article>)}</div><form onSubmit={send}><input placeholder="Escreva uma mensagem…" value={text} onChange={(event) => setText(event.target.value)} /><button className="primary" disabled={sending}><Send size={16}/>{sending ? "A enviar…" : "Enviar"}</button></form></> : <p className="manager-empty-state"><MessageCircle size={18}/> Selecione uma conversa para responder.</p>}</div></div>{error && <p className="manager-form-error">{error}</p>}</section>;
}
