import { Film, ListVideo, Pencil, Plus, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import "./manager-video-library.css";

const blankCourse = { titulo: "", descricao: "", categoria: "", is_pago: false, preco: "0", destaque: false };
const blankLesson = { titulo: "", video_url: "", descricao: "", ordem: "0" };
const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

function CourseForm({ categories, course, onClose, onSaved }) {
  const [values, setValues] = useState(course ? { ...blankCourse, ...course, categoria: String(course.categoria_id), preco: course.preco } : blankCourse); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (field, value) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(course ? `/backend/gestoreduka/api/react/cursos-video/${course.id}/` : "/backend/gestoreduka/api/react/cursos-video/", { method: course ? "PATCH" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar o curso em vídeo."); onSaved(payload.curso); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">{course ? "Editar curso em vídeo" : "Novo curso em vídeo"}</span><h2>{course ? course.titulo : "Criar curso em vídeo"}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><div className="manager-form-grid"><label className="wide"><span>Título</span><input required value={values.titulo} onChange={(event) => update("titulo", event.target.value)} /></label><label className="wide"><span>Descrição</span><textarea required rows="4" value={values.descricao} onChange={(event) => update("descricao", event.target.value)} /></label><label><span>Categoria</span><select required value={values.categoria} onChange={(event) => update("categoria", event.target.value)}><option value="">Selecionar categoria</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label><span>Preço (Kz)</span><input disabled={!values.is_pago} min="0" step="0.01" type="number" value={values.preco} onChange={(event) => update("preco", event.target.value)} /></label></div><div className="manager-checks"><label><input type="checkbox" checked={values.is_pago} onChange={(event) => update("is_pago", event.target.checked)} />Curso pago</label><label><input type="checkbox" checked={values.destaque} onChange={(event) => update("destaque", event.target.checked)} />Destacar no catálogo</label></div>{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : "Guardar curso"}</button></footer></form></div>;
}

function LessonsModal({ course, onClose, onChanged }) {
  const [data, setData] = useState(null); const [values, setValues] = useState(blankLesson); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { try { const response = await fetch(`/backend/gestoreduka/api/react/cursos-video/${course.id}/`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar as aulas."); setData(payload.curso); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, [course.id]);
  const add = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`/backend/gestoreduka/api/react/cursos-video/${course.id}/aulas/`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar a aula."); setValues(blankLesson); await load(); onChanged(); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  const remove = async (lesson) => { if (!window.confirm(`Remover a aula “${lesson.titulo}”?`)) return; try { const response = await fetch(`/backend/gestoreduka/api/react/aulas-video/${lesson.id}/`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível remover a aula."); await load(); onChanged(); } catch (reason) { setError(reason.message); } };
  return <div className="manager-modal"><section className="manager-records-modal"><header><div><span className="manager-eyebrow">Conteúdo pedagógico</span><h2>{course.titulo}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header>{error && <p className="manager-form-error">{error}</p>}<div className="manager-record-list">{data ? data.aulas.length ? data.aulas.map((lesson) => <article key={lesson.id}><strong>{lesson.ordem}. {lesson.titulo}</strong><span>{lesson.video_url}</span><button onClick={() => remove(lesson)}><Trash2 size={15}/></button></article>) : <p className="manager-empty-state">Este curso ainda não possui aulas.</p> : <p>A preparar as aulas…</p>}</div><form onSubmit={add} className="manager-lesson-form"><input required placeholder="Título da aula" value={values.titulo} onChange={(event) => setValues((current) => ({ ...current, titulo: event.target.value }))}/><input required type="url" placeholder="Ligação do vídeo" value={values.video_url} onChange={(event) => setValues((current) => ({ ...current, video_url: event.target.value }))}/><input min="0" type="number" placeholder="Ordem" value={values.ordem} onChange={(event) => setValues((current) => ({ ...current, ordem: event.target.value }))}/><button className="primary" disabled={saving}>{saving ? "A adicionar…" : "Adicionar aula"}</button></form></section></div>;
}

export default function ManagerVideoCoursesPanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [form, setForm] = useState(null); const [lessons, setLessons] = useState(null);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/cursos-video/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os cursos em vídeo."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const remove = async (course) => { if (!window.confirm(`Remover o curso em vídeo “${course.titulo}” e as suas aulas?`)) return; try { const response = await fetch(`/backend/gestoreduka/api/react/cursos-video/${course.id}/`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível remover o curso em vídeo."); load(); } catch (reason) { setError(reason.message); } };
  if (error && !data) return <section id="video" className="manager-courses manager-video"><h2>Cursos em vídeo</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="video" className="manager-courses manager-video"><p>A preparar cursos em vídeo…</p></section>;
  return <section id="video" className="manager-courses manager-video"><div className="manager-video-heading"><div><span className="manager-eyebrow">Biblioteca streaming</span><h2>Cursos em vídeo</h2><p>Apresente formações digitais, aulas e progresso dos alunos numa biblioteca clara e pronta para gerir.</p></div></div><button className="manager-create-course" onClick={() => setForm("new")}><Plus size={15}/> Criar curso</button>{error && <p className="manager-form-error">{error}</p>}<div className="manager-video-grid">{data.cursos.length ? data.cursos.map((course) => <article key={course.id} className="manager-video-card"><div className="manager-video-cover">{course.capa_url ? <img src={course.capa_url} alt=""/> : <Film size={25}/>}<span>{course.destaque ? "Em destaque" : course.categoria}</span></div><div className="manager-video-card-copy"><div><small>{course.categoria}</small><h3>{course.titulo}</h3><p>{course.descricao}</p></div><div className="manager-video-meta"><span>{course.total_aulas} aulas</span><span>{course.total_inscritos} alunos</span><strong>{course.is_pago ? `${Number(course.preco).toLocaleString("pt-AO")} Kz` : "Gratuito"}</strong></div><div className="manager-video-actions"><button className="manager-video-lessons" onClick={() => setLessons(course)}><ListVideo size={16}/> Aulas</button><button onClick={() => setForm(course)} aria-label={`Editar ${course.titulo}`}><Pencil size={16}/></button><button className="manager-course-delete" onClick={() => remove(course)} aria-label={`Remover ${course.titulo}`}><Trash2 size={16}/></button></div></div></article>) : <p className="manager-empty-state"><Film size={16}/> Ainda não existem cursos em vídeo publicados pelo centro.</p>}</div>{form && <CourseForm categories={data.categorias} course={form === "new" ? null : form} onClose={() => setForm(null)} onSaved={() => { setForm(null); load(); }} />}{lessons && <LessonsModal course={lessons} onClose={() => setLessons(null)} onChanged={load} />}</section>;
}
