import { Megaphone, Pencil, Plus, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";

const blank = { titulo: "", conteudo: "", importante: false, ativo: true };
const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

function AnnouncementForm({ item, onClose, onSaved }) {
  const [values, setValues] = useState(item ? { ...blank, ...item } : blank); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = (field, value) => setValues((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(item ? `/backend/gestoreduka/api/react/anuncios/${item.id}/` : "/backend/gestoreduka/api/react/anuncios/", { method: item ? "PATCH" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar o comunicado."); onSaved(payload.anuncio); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">Comunicado institucional</span><h2>{item ? "Editar comunicado" : "Novo comunicado"}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header><div className="manager-form-grid"><label className="wide"><span>Título</span><input required value={values.titulo} onChange={(event) => update("titulo", event.target.value)} /></label><label className="wide"><span>Conteúdo</span><textarea required rows="6" value={values.conteudo} onChange={(event) => update("conteudo", event.target.value)} /></label></div><div className="manager-checks"><label><input type="checkbox" checked={values.importante} onChange={(event) => update("importante", event.target.checked)} />Marcar como importante</label><label><input type="checkbox" checked={values.ativo} onChange={(event) => update("ativo", event.target.checked)} />Comunicado activo</label></div>{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : "Publicar comunicado"}</button></footer></form></div>;
}

export default function ManagerAnnouncementsPanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [modal, setModal] = useState(null);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/anuncios/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os comunicados."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const remove = async (item) => { if (!window.confirm(`Remover o comunicado “${item.titulo}”?`)) return; try { const response = await fetch(`/backend/gestoreduka/api/react/anuncios/${item.id}/`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível remover o comunicado."); load(); } catch (reason) { setError(reason.message); } };
  if (error && !data) return <section id="anuncios" className="manager-courses manager-announcements"><h2>Comunicados</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="anuncios" className="manager-courses manager-announcements"><p>A preparar comunicados…</p></section>;
  return <section id="anuncios" className="manager-courses manager-announcements"><div><span className="manager-eyebrow">Comunicação com seguidores</span><h2>Comunicados</h2></div><button className="manager-create-course" onClick={() => setModal("new")}><Plus size={15}/> Publicar</button>{error && <p className="manager-form-error">{error}</p>}<div className="manager-course-list">{data.anuncios.length ? data.anuncios.map((item) => <article key={item.id}><div><strong>{item.titulo}</strong><span>{item.conteudo.slice(0, 120)}{item.conteudo.length > 120 ? "…" : ""}</span></div><span className={item.ativo ? "published" : "draft"}>{item.importante ? "Importante" : item.ativo ? "Publicado" : "Inactivo"}</span><button onClick={() => setModal(item)} aria-label={`Editar ${item.titulo}`}><Pencil size={16}/></button><button className="manager-course-delete" onClick={() => remove(item)} aria-label={`Remover ${item.titulo}`}><Trash2 size={16}/></button></article>) : <p className="manager-empty-state"><Megaphone size={16}/> Ainda não existem comunicados institucionais.</p>}</div>{modal && <AnnouncementForm item={modal === "new" ? null : modal} onClose={() => setModal(null)} onSaved={() => { setModal(null); load(); }} />}</section>;
}
