import { ImagePlus, Save, Upload } from "lucide-react";
import { useEffect, useState } from "react";

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

export default function ManagerProfilePanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState("");
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/perfil/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar o perfil institucional."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const update = (group, field, value) => setData((current) => ({ ...current, [group]: { ...current[group], [field]: value } }));
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/backend/gestoreduka/api/react/perfil/", { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify({ centro: data.centro, perfil: data.perfil }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar o perfil institucional."); setData(payload); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  const upload = async (field, file) => { if (!file) return; setUploading(field); setError(""); const body = new FormData(); body.append("campo", field); body.append("ficheiro", file); try { const response = await fetch("/backend/gestoreduka/api/react/perfil/media/", { method: "POST", credentials: "same-origin", headers: { "X-CSRFToken": csrfToken() }, body }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível enviar a imagem."); setData((current) => ({ ...current, perfil: { ...current.perfil, [`${field}_url`]: payload.url } })); } catch (reason) { setError(reason.message); } finally { setUploading(""); } };
  if (error && !data) return <section id="perfil" className="manager-courses manager-profile"><h2>Perfil institucional</h2><p className="manager-form-error">{error}</p><button onClick={() => { setError(""); load(); }}>Tentar novamente</button></section>;
  if (!data) return <section id="perfil" className="manager-courses manager-profile"><p>A preparar o perfil institucional…</p></section>;
  const field = (group, name, label, type = "text") => <label><span>{label}</span><input type={type} value={data[group][name] || ""} onChange={(event) => update(group, name, event.target.value)} /></label>;
  return <section id="perfil" className="manager-courses manager-profile"><div><span className="manager-eyebrow">Presença pública</span><h2>Perfil institucional</h2></div><form onSubmit={save}><div className="manager-profile-media"><label className="manager-profile-asset"><span>{data.perfil.banner_url ? <img src={data.perfil.banner_url} alt="Banner actual"/> : <ImagePlus size={24}/>}</span><b>Imagem de capa</b><small>{uploading === "banner" ? "A enviar…" : "PNG, JPG ou WebP · até 5 MB"}</small><input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={(event) => upload("banner", event.target.files?.[0])} /></label><label className="manager-profile-asset is-logo"><span>{data.perfil.imagem_url ? <img src={data.perfil.imagem_url} alt="Logótipo actual"/> : <Upload size={20}/>}</span><b>Logótipo</b><small>{uploading === "imagem" ? "A enviar…" : "PNG, JPG ou WebP · até 5 MB"}</small><input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={(event) => upload("imagem", event.target.files?.[0])} /></label></div><div className="manager-form-grid">{field("centro", "nome", "Nome do centro")}{field("centro", "email", "E-mail institucional", "email")}{field("centro", "telefone", "Telefone")}{field("centro", "site", "Website", "url")}<label><span>País</span><select value={data.centro.pais} onChange={(event) => update("centro", "pais", event.target.value)}>{[["AO", "Angola"],["PT", "Portugal"],["BR", "Brasil"],["CV", "Cabo Verde"],["MZ", "Moçambique"],["ST", "São Tomé e Príncipe"],["GW", "Guiné-Bissau"],["TL", "Timor-Leste"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{field("centro", "provincia", "Província / região")}{field("centro", "cidade", "Cidade")}{field("centro", "endereco", "Endereço")}<label className="wide"><span>Apresentação</span><textarea rows="4" value={data.perfil.descricao} onChange={(event) => update("perfil", "descricao", event.target.value)} /></label><label><span>Tipo de centro</span><input value={data.perfil.tipo} onChange={(event) => update("perfil", "tipo", event.target.value)} /></label><label><span>Modalidade</span><select value={data.perfil.modalidade} onChange={(event) => update("perfil", "modalidade", event.target.value)}>{["Presencial", "Online", "Híbrido"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide"><span>Missão</span><textarea rows="3" value={data.perfil.missao} onChange={(event) => update("perfil", "missao", event.target.value)} /></label><label className="wide"><span>Visão</span><textarea rows="3" value={data.perfil.visao} onChange={(event) => update("perfil", "visao", event.target.value)} /></label></div>{error && <p className="manager-form-error">{error}</p>}<footer><p>{data.galeria.length} imagens na galeria pública.</p><button className="primary" disabled={saving}><Save size={16}/> {saving ? "A guardar…" : "Guardar perfil"}</button></footer></form></section>;
}
