import { X } from "lucide-react";
import { useEffect, useState } from "react";

const initial = { titulo:"", descricao:"", descricao_curta:"", categoria:"", nivel:"", idioma:"", duracao:"", moeda:"AOA", modalidade:"PRESENCIAL", carga_horaria:"", preco:"0", preco_inscricao:"0", mensalidade:"0", tipo_cobranca_inscricao:"APENAS_TAXA", documento_requerido:"NENHUM", certificado:false, is_gratuito:false, publicado:false, destaque:false, permite_parcelamento:false, max_parcelas:"1", preco_promocional:"", data_inicio_promocao:"", data_fim_promocao:"", instrutores:[] };
export default function ManagerCourseForm({ courseId, onClose, onCreated, onUpdated }) {
  const [meta, setMeta] = useState(null), [values, setValues] = useState(initial), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { const load = async () => { try { const metaResponse = await fetch("/backend/gestoreduka/api/react/cursos/", { credentials:"same-origin" }); const metadata = await metaResponse.json(); if (!metaResponse.ok) throw new Error(metadata.detail || "Não foi possível preparar o formulário."); if (courseId) { const courseResponse = await fetch(`/backend/gestoreduka/api/react/cursos/${courseId}/`, { credentials:"same-origin" }); const coursePayload = await courseResponse.json(); if (!courseResponse.ok) throw new Error(coursePayload.detail || "Não foi possível carregar o curso."); const { turmas, ...courseValues } = coursePayload.curso; setValues({ ...initial, ...courseValues, instrutores: courseValues.instrutores.map(String) }); } setMeta(metadata); } catch (reason) { setError(reason.message || "Não foi possível preparar o formulário."); } }; load(); }, [courseId]);
  const update = (name, value) => setValues((current) => ({ ...current, [name]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); const token = document.cookie.split(";").map((p) => p.trim()).find((p) => p.startsWith("csrftoken="))?.split("=")[1] || ""; try { let response; if (courseId) { response = await fetch(`/backend/gestoreduka/api/react/cursos/${courseId}/`, { method:"PATCH", credentials:"same-origin", headers:{ "Content-Type":"application/json", "X-CSRFToken":token }, body:JSON.stringify(values) }); } else { const body = new FormData(); Object.entries(values).forEach(([key, value]) => { if (Array.isArray(value)) value.forEach((item) => body.append(key, item)); else if (typeof value === "boolean") { if (value) body.append(key, "on"); } else body.append(key, value); }); response = await fetch("/backend/gestoreduka/api/react/cursos/", { method:"POST", credentials:"same-origin", headers:{ "X-CSRFToken":token }, body }); } const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || (courseId ? "Não foi possível actualizar o curso." : "Não foi possível criar o curso.")); if (courseId) onUpdated(payload.curso); else onCreated(payload.curso); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  const select = (name, label) => <label><span>{label}</span><select value={values[name]} onChange={(event) => update(name, event.target.value)} required><option value="">Selecionar</option>{(meta?.escolhas?.[name] || []).map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>;
  const editing = Boolean(courseId);
  return <div className="manager-modal"><form onSubmit={submit}><header><div><span className="manager-eyebrow">{editing ? "Editar curso" : "Novo curso"}</span><h2>{editing ? "Actualizar formação presencial" : "Criar formação presencial"}</h2></div><button type="button" onClick={onClose}><X size={18}/></button></header>{!meta ? <p>A preparar campos…</p> : <><div className="manager-form-grid"><label className="wide"><span>Título</span><input required value={values.titulo} onChange={(e)=>update("titulo",e.target.value)} /></label><label className="wide"><span>Descrição curta</span><input required maxLength="300" value={values.descricao_curta} onChange={(e)=>update("descricao_curta",e.target.value)} /></label><label className="wide"><span>Descrição detalhada</span><textarea required rows="4" value={values.descricao} onChange={(e)=>update("descricao",e.target.value)} /></label><label><span>Categoria</span><select required value={values.categoria} onChange={(e)=>update("categoria",e.target.value)}><option value="">Selecionar</option>{meta.categorias.map((item)=><option key={item.id} value={item.id}>{item.nome}</option>)}</select></label>{select("nivel","Nível")}{select("idioma","Idioma")}{select("duracao","Duração")}{select("modalidade","Modalidade")}<label><span>Carga horária</span><input required min="1" type="number" value={values.carga_horaria} onChange={(e)=>update("carga_horaria",e.target.value)} /></label><label><span>Preço</span><input required min="0" step="0.001" type="number" value={values.preco} onChange={(e)=>update("preco",e.target.value)} /></label><label><span>Taxa de inscrição</span><input min="0" step="0.001" type="number" value={values.preco_inscricao} onChange={(e)=>update("preco_inscricao",e.target.value)} /></label><label><span>Formadores</span><select multiple value={values.instrutores} onChange={(e)=>update("instrutores",[...e.target.selectedOptions].map((o)=>o.value))}>{meta.instrutores.map((item)=><option key={item.id} value={item.id}>{item.nome}</option>)}</select></label></div><div className="manager-checks">{[["certificado","Emite certificado"],["is_gratuito","Curso gratuito"],["destaque","Destacar no catálogo"],["publicado","Publicar já"]].map(([key,label])=><label key={key}><input type="checkbox" checked={values[key]} onChange={(e)=>update(key,e.target.checked)}/>{label}</label>)}</div>{error && <p className="manager-form-error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "A guardar…" : editing ? "Guardar alterações" : "Criar curso"}</button></footer></>}</form></div>;
}
