import { CheckCircle2, EyeOff, MessageSquareReply, Star } from "lucide-react";
import { useEffect, useState } from "react";
import "./manager-comments-panel.css";

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

export default function ManagerCommentsPanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [drafts, setDrafts] = useState({}); const [saving, setSaving] = useState(null);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/comentarios/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os comentários."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const save = async (item, values) => { setSaving(item.id); setError(""); try { const response = await fetch(`/backend/gestoreduka/api/react/comentarios/${item.id}/`, { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível actualizar o comentário."); await load(); } catch (reason) { setError(reason.message); } finally { setSaving(null); } };
  if (error && !data) return <section id="comentarios" className="manager-courses manager-comments"><h2>Comentários</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="comentarios" className="manager-courses manager-comments"><p>A preparar comentários…</p></section>;
  return <section id="comentarios" className="manager-courses manager-comments"><header className="manager-comments-heading"><div><span className="manager-eyebrow">Qualidade e comunidade</span><h2>Comentários dos alunos</h2><p>Leia o retorno dos alunos, responda com contexto e controle a visibilidade no catálogo público.</p></div><div className="manager-comments-summary"><strong>{data.comentarios.length}</strong><span>feedbacks recebidos</span></div></header>{error && <p className="manager-form-error">{error}</p>}<div className="manager-comment-grid">{data.comentarios.length ? data.comentarios.map((item) => <article key={item.id} className="manager-comment-card"><header><span className="manager-comment-avatar">{item.aluno.charAt(0)}</span><div><strong>{item.aluno}</strong><span>{item.curso}</span><small><span className="manager-comment-stars">{Array.from({ length: item.avaliacao }).map((_, index) => <Star key={index} size={12} fill="currentColor"/>)}</span>{new Date(item.data).toLocaleDateString("pt-AO")}</small></div><span className={item.aprovado ? "manager-comment-status is-visible" : "manager-comment-status is-hidden"}>{item.aprovado ? "Visível" : "Oculto"}</span></header><p className="manager-comment-text">{item.texto}</p>{item.resposta ? <div className="manager-comment-reply"><CheckCircle2 size={16}/><div><small>Resposta do centro</small><p>{item.resposta}</p></div></div> : <label className="manager-comment-composer"><span>Responder ao aluno</span><textarea rows="3" placeholder="Escreva uma resposta útil e profissional…" value={drafts[item.id] || ""} onChange={(event) => setDrafts((current) => ({ ...current, [item.id]: event.target.value }))}/></label>}<footer className="manager-comment-actions">{!item.resposta && <button className="primary" disabled={saving === item.id || !(drafts[item.id] || "").trim()} onClick={() => save(item, { resposta: drafts[item.id] })}><MessageSquareReply size={15}/>{saving === item.id ? "A enviar…" : "Enviar resposta"}</button>}<button className={item.aprovado ? "secondary" : "approve"} disabled={saving === item.id} onClick={() => save(item, { aprovado: !item.aprovado })}>{item.aprovado ? <><EyeOff size={15}/>Ocultar do catálogo</> : <><CheckCircle2 size={15}/>Aprovar comentário</>}</button></footer></article>) : <p className="manager-empty-state">Ainda não existem comentários nos cursos deste centro.</p>}</div></section>;
}
