import { Search, UserRound } from "lucide-react";
import { useEffect, useState } from "react";

export default function ManagerStudentsPanel() {
  const [query, setQuery] = useState(""); const [students, setStudents] = useState(null); const [detail, setDetail] = useState(null); const [error, setError] = useState("");
  const load = async (value = "") => { try { const response = await fetch(`/backend/gestoreduka/api/react/alunos/?q=${encodeURIComponent(value)}`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os alunos."); setStudents(payload.alunos); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const open = async (student) => { try { const response = await fetch(`/backend/gestoreduka/api/react/alunos/${student.id}/`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível abrir o dossiê."); setDetail(payload); } catch (reason) { setError(reason.message); } };
  if (error && !students) return <section id="alunos" className="manager-courses"><h2>Alunos</h2><p className="manager-form-error">{error}</p></section>;
  if (!students) return <section id="alunos" className="manager-courses"><p>A preparar alunos…</p></section>;
  return <section id="alunos" className="manager-courses"><div><span className="manager-eyebrow">Acompanhamento académico</span><h2>Alunos e dossiês</h2></div><form className="manager-lesson-form" onSubmit={(event) => { event.preventDefault(); load(query); }}><input placeholder="Pesquisar por nome ou e-mail" value={query} onChange={(event) => setQuery(event.target.value)} /><button className="primary"><Search size={15}/>Pesquisar</button></form>{error && <p className="manager-form-error">{error}</p>}<div className="manager-course-list">{students.map((student) => <article key={student.id}><div><strong>{student.nome}</strong><span>{student.email}</span></div><button onClick={() => open(student)}>Ver dossiê</button></article>)}{!students.length && <p className="manager-empty-state"><UserRound size={16}/> Não foram encontrados alunos.</p>}</div>{detail && <div className="manager-modal"><section className="manager-records-modal"><header><div><span className="manager-eyebrow">Dossiê académico</span><h2>{detail.aluno.nome}</h2></div><button onClick={() => setDetail(null)}>Fechar</button></header><div className="manager-record-list">{detail.inscricoes.map((item) => <article key={`i-${item.id}`}><strong>{item.curso}</strong><span>Inscrição · {item.status} · {item.turma || "Sem turma"}</span></article>)}{detail.matriculas.map((item) => <article key={`m-${item.id}`}><strong>{item.curso}</strong><span>Matrícula · {item.turma || "Sem turma"}</span></article>)}</div></section></div>}</section>;
}
