import { MessageSquareReply, Star } from "lucide-react";
import { useEffect, useState } from "react";

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || "";

export default function ManagerCommentsPanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [drafts, setDrafts] = useState({}); const [saving, setSaving] = useState(null);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/comentarios/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os comentários."); setData(payload); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const save = async (item, values) => { setSaving(item.id); setError(""); try { const response = await fetch(`/backend/gestoreduka/api/react/comentarios/${item.id}/`, { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(values) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível actualizar o comentário."); await load(); } catch (reason) { setError(reason.message); } finally { setSaving(null); } };
  if (error && !data) return <section id="comentarios" className="manager-courses manager-comments"><h2>Comentários</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="comentarios" className="manager-courses manager-comments"><p>A preparar comentários…</p></section>;
  return <section id="comentarios" className="manager-courses manager-comments"><div><span className="manager-eyebrow">Qualidade e comunidade</span><h2>Comentários dos alunos</h2></div>{error && <p className="manager-form-error">{error}</p>}<div className="manager-record-list">{data.comentarios.length ? data.comentarios.map((item) => <article key={item.id}><div><strong>{item.aluno} · {item.curso}</strong><span>{Array.from({ length: item.avaliacao }).map((_, index) => <Star key={index} size={13} fill="currentColor"/>)} · {new Date(item.data).toLocaleDateString("pt-AO")}</span><p>{item.texto}</p>{item.resposta ? <p><b>Resposta do centro:</b> {item.resposta}</p> : <textarea rows="2" placeholder="Responder ao aluno…" value={drafts[item.id] || ""} onChange={(event) => setDrafts((current) => ({ ...current, [item.id]: event.target.value }))}/>}</div><div className="manager-comment-actions">{!item.resposta && <button className="primary" disabled={saving === item.id || !(drafts[item.id] || "").trim()} onClick={() => save(item, { resposta: drafts[item.id] })}><MessageSquareReply size={15}/>{saving === item.id ? "A enviar…" : "Responder"}</button>}<button disabled={saving === item.id} onClick={() => save(item, { aprovado: !item.aprovado })}>{item.aprovado ? "Ocultar" : "Aprovar"}</button></div></article>) : <p className="manager-empty-state">Ainda não existem comentários nos cursos deste centro.</p>}</div></section>;
}
