import { Banknote, CheckCircle2, CircleAlert, CreditCard, Landmark, ReceiptText, ShieldCheck, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";

const money = (value, currency = "AOA") => new Intl.NumberFormat("pt-AO", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value || 0));

const csrfToken = () => document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=").slice(1).join("=") || "";

export default function ManagerFinancePanel() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [finance, setFinance] = useState(null); const [saving, setSaving] = useState(false);
  const load = async () => { try { const response = await fetch("/backend/gestoreduka/api/react/financeiro/", { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível carregar os dados financeiros."); setData(payload); setFinance(payload.configuracao_financeira); } catch (reason) { setError(reason.message); } };
  useEffect(() => { load(); }, []);
  const saveFinance = async (event) => { event.preventDefault(); if (!finance) return; setSaving(true); setError(""); try { const response = await fetch("/backend/gestoreduka/api/react/financeiro/", { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify({ moeda_cobranca: finance.moeda_cobranca }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Não foi possível guardar a configuração financeira."); setFinance(payload.configuracao_financeira); await load(); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  if (error && !data) return <section id="financeiro" className="manager-courses manager-finance"><h2>Financeiro</h2><p className="manager-form-error">{error}</p></section>;
  if (!data) return <section id="financeiro" className="manager-courses manager-finance"><p>A preparar movimentos financeiros…</p></section>;
  const currency = finance?.moeda_cobranca || "AOA";
  const cards = [[WalletCards, "Receita total", data.metricas.total], [CreditCard, "Plataforma", data.metricas.plataforma], [Banknote, "Presencial", data.metricas.presencial], [ReceiptText, "Movimentos", data.metricas.quantidade_movimentos]];
  return <section id="financeiro" className="manager-courses manager-finance"><div><span className="manager-eyebrow">Acompanhamento financeiro</span><h2>Receitas, movimentos e moeda</h2></div><div className="manager-enrollment-metrics">{cards.map(([Icon, label, value]) => <article key={label}><Icon size={15}/><small>{label}</small><strong>{label === "Movimentos" ? value : money(value, currency)}</strong></article>)}</div>{finance && <form className="manager-finance-settings" onSubmit={saveFinance}><div className="manager-finance-settings-intro"><span className="manager-finance-icon"><Landmark size={20}/></span><div><span className="manager-eyebrow">Financeiro e moeda</span><h3>Moeda de cobrança do centro</h3><p>{finance.mensagem}</p></div></div><div className="manager-finance-settings-grid"><label>País de operação<input value={finance.pais_nome} disabled /></label><label>Moeda de cobrança<select value={finance.moeda_cobranca} onChange={(event) => setFinance((current) => ({ ...current, moeda_cobranca: event.target.value }))}>{finance.moedas_disponiveis.map((option) => <option value={option.codigo} key={option.codigo}>{option.nome}</option>)}</select></label><label>Gateway<input value={finance.gateway === "PENDENTE" ? "A definir pela Edukangola" : finance.gateway} disabled /></label><label>Conta de liquidação<input value={finance.conta_liquidacao_configurada ? "Dados bancários completos" : "Dados bancários por completar no perfil"} disabled /></label></div><div className="manager-finance-status"><span className={finance.pode_cobrar ? "is-active" : "is-pending"}>{finance.pode_cobrar ? <CheckCircle2 size={16}/> : <CircleAlert size={16}/>} {finance.estado_label}</span><p><ShieldCheck size={16}/> Apenas a Edukangola activa cobranças depois de validar o gateway e a conta de liquidação.</p></div><button className="manager-finance-save" disabled={saving}>{saving ? "A guardar…" : "Guardar para validação"}</button></form>}{error && <p className="manager-form-error">{error}</p>}<div className="manager-enrollment-list">{data.movimentos.length ? data.movimentos.map((item, index) => <article key={`${item.referencia}-${index}`}><div><strong>{item.aluno}</strong><span>{item.curso} · {item.referencia}</span></div><span className={item.tipo === "PRESENCIAL" ? "published" : "draft"}>{item.tipo}</span><span className="manager-enrollment-payment">{money(item.valor, currency)}</span><span>{new Date(item.data).toLocaleDateString("pt-AO")}</span></article>) : <p className="manager-empty-state">Ainda não existem movimentos financeiros confirmados.</p>}</div>{data.por_filial.length > 0 && <div className="manager-finance-branches"><strong>Receita por filial</strong>{data.por_filial.map((item) => <span key={item.id}>{item.nome}: {money(item.valor, currency)}</span>)}</div>}</section>;
}
