# Generated by Django 5.2.4 on 2026-08-16 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('biografia', models.TextField(blank=True)),
                ('pais', models.CharField(blank=True, default='Angola', max_length=80)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='biblioteca/autores/')),
                ('em_destaque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=260)),
                ('editora', models.CharField(blank=True, default='Edukangola', max_length=180)),
                ('sinopse', models.TextField()),
                ('descricao_curta', models.CharField(blank=True, max_length=260)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='biblioteca/capas/')),
                ('categoria', models.CharField(db_index=True, max_length=100)),
                ('temas', models.CharField(blank=True, help_text='Separar temas por vírgulas.', max_length=260)),
                ('idioma', models.CharField(default='pt', max_length=12)),
                ('paginas', models.PositiveIntegerField(default=0)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('DIGITAL', 'Leitura digital'), ('AUDIO', 'Audiolivro'), ('AMBOS', 'Leitura e áudio')], default='DIGITAL', max_length=12)),
                ('conteudo_leitura', models.TextField(blank=True, help_text='Texto autorizado para leitura no navegador.')),
                ('excerto', models.TextField(blank=True)),
                ('narrador', models.CharField(blank=True, max_length=180)),
                ('direitos_confirmados', models.BooleanField(default=False, help_text='Confirma que a Edukangola pode distribuir esta obra.')),
                ('gratuito', models.BooleanField(default=True)),
                ('em_destaque', models.BooleanField(default=False)),
                ('selecao_semana', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado')], db_index=True, default='RASCUNHO', max_length=12)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='biblioteca.autor')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ('-selecao_semana', '-em_destaque', '-publicado_em', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='CapituloAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('duracao_segundos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('audio', models.FileField(blank=True, null=True, upload_to='biblioteca/audio/')),
                ('descricao', models.TextField(blank=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos_audio', to='biblioteca.livro')),
            ],
            options={
                'verbose_name': 'Capítulo de áudio',
                'verbose_name_plural': 'Capítulos de áudio',
                'ordering': ('ordem', 'id'),
                'constraints': [models.UniqueConstraint(fields=('livro', 'ordem'), name='biblioteca_capitulo_ordem_unica')],
            },
        ),
        migrations.CreateModel(
            name='BibliotecaPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardado', models.BooleanField(default=True)),
                ('progresso_leitura', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('progresso_audio_segundos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_pessoal', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_biblioteca', to='biblioteca.livro')),
            ],
            options={
                'verbose_name': 'Livro na biblioteca pessoal',
                'verbose_name_plural': 'Biblioteca pessoal',
                'ordering': ('-ultima_atividade',),
                'constraints': [models.UniqueConstraint(fields=('usuario', 'livro'), name='biblioteca_usuario_livro_unico')],
            },
        ),
    ]
