# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('cursos_app', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_autoria_aluno', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='autor',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_autoria_instrutor', to='cursos_app.instrutor'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_avaliacoes', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='autor',
            name='biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_autoria_biblioteca', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_carrinho', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_emprestimos', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='estoquebiblioteca',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_favoritos', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='historicoleitura',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_historico_leitura', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='biblioteca.carrinho'),
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='biblioteca.autor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='biblioteca_proprietaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categorias',
            field=models.ManyToManyField(related_name='livros', to='biblioteca.categorialivro'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='historicoleitura',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_leitura', to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='estoquebiblioteca',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_bibliotecas', to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_notificacoes', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='perfilbiblioteca',
            name='biblioteca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_reservas', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='biblioteca.livro'),
        ),
        migrations.AddField(
            model_name='venda',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_compras', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='venda',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='biblioteca.biblioteca'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='biblioteca.venda'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'livro')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('aluno', 'livro')},
        ),
        migrations.AlterUniqueTogether(
            name='estoquebiblioteca',
            unique_together={('biblioteca', 'livro')},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('aluno', 'livro')},
        ),
    ]
