# Generated by Django 5.2.4 on 2026-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa_url',
            field=models.URLField(blank=True, help_text='URL de uma capa editorial quando não for carregada no servidor.'),
        ),
    ]
