# Generated by Django 5.2.4 on 2026-08-16 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_livro_capa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotecapessoal',
            name='pagina_leitura',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
