# Generated by Django 5.2.7 on 2025-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_categoria_categorialivro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorialivro',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Livro', 'verbose_name_plural': 'Categorias de LIvros'},
        ),
        migrations.AddField(
            model_name='categorialivro',
            name='imagem',
            field=models.ImageField(default=1, upload_to='categoria de Livros/'),
            preserve_default=False,
        ),
    ]
