# Generated by Django 5.2.4 on 2026-02-08 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='email',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='senha',
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Registro'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='tipo',
            field=models.CharField(choices=[('PUBLICA', 'Pública'), ('ESCOLAR', 'Escolar'), ('UNIVERSITARIA', 'Universitária'), ('ESPECIALIZADA', 'Especializada'), ('COMUNITARIA', 'Comunitária')], default='PUBLICA', max_length=50, verbose_name='Tipo de Biblioteca'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
