# Generated by Django 5.2.4 on 2026-05-04 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0013_alter_curso_preco'),
        ('usuarios', '0011_perfilaluno_interesses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Instituição')),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('ESTADO', 'Estado/Governo'), ('ONG', 'ONG/Fundação'), ('INDIVIDUAL', 'Individual')], default='EMPRESA', max_length=20, verbose_name='Tipo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/', verbose_name='Logo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Missão Social')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('ativo', models.BooleanField(default=True)),
                ('data_parceria', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='CandidaturaBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='Por que você precisa desta bolsa?')),
                ('renda_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Renda Familiar Estimada')),
                ('documento_comprovativo', models.FileField(blank=True, null=True, upload_to='bolsas/comprovantes/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('feedback_admin', models.TextField(blank=True, verbose_name='Feedback da Administração')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_bolsa', to='usuarios.aluno')),
                ('curso_pretendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Candidatura à Bolsa',
                'verbose_name_plural': 'Candidaturas às Bolsas',
                'ordering': ['-data_candidatura'],
            },
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Porcentagem da Bolsa')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('SUSPENSA', 'Suspensa')], default='ATIVA', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='usuarios.aluno')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolsas_vinculadas', to='cursos_app.curso')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas_concedidas', to='bolsas.patrocinador')),
            ],
            options={
                'verbose_name': 'Bolsa de Estudo',
                'verbose_name_plural': 'Bolsas de Estudo',
            },
        ),
    ]
