# Generated by Django 5.2.4 on 2026-05-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0012_instrutor_titulo_instrutor_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrutorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Candidatura de Instrutor',
                'verbose_name_plural': 'Candidaturas de Instrutores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cursos_app.instrutor',),
        ),
    ]
