# Generated by Django 5.2.4 on 2026-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoHibridaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_alunos', models.FloatField(default=0.0, verbose_name='Média de Avaliações (Alunos)')),
                ('taxa_conclusao', models.FloatField(default=0.0, verbose_name='Taxa de Conclusão (%)')),
                ('frequencia_media', models.FloatField(default=0.0, verbose_name='Frequência Média (%)')),
                ('score_confianca', models.FloatField(default=0.0, verbose_name='Score de Confiança')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avaliação Híbrida de Centro',
                'verbose_name_plural': 'Avaliações Híbridas de Centros',
            },
        ),
        migrations.CreateModel(
            name='FeedbackExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('moderado', models.BooleanField(default=False)),
                ('util', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feedback Moderado',
                'verbose_name_plural': 'Feedbacks Moderados',
            },
        ),
    ]
