# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('gestoreduka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaohibridacentro',
            name='centro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_hibrida', to='gestoreduka.centrodeformacao'),
        ),
    ]
