# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0002_initial'),
        ('cursos_app', '0002_initial'),
        ('gestoreduka', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackexterno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='feedbackexterno',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='feedbackexterno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos_app.curso'),
        ),
    ]
