# Generated by Django 5.2.4 on 2026-02-08 14:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_initial'),
        ('cursos_app', '0007_prerequisitocurso_publicoalvocurso'),
        ('cursovideoapp', '0003_alter_curso_video_categoria_and_more'),
        ('usuarios', '0004_alter_centroseguimento_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=1000, verbose_name='Comentário')),
                ('avaliacao', models.IntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('status_aluno', models.CharField(choices=[('INS', 'Inscrito'), ('COM', 'Concluído'), ('AND', 'Em Andamento')], default='AND', max_length=3, verbose_name='Status do Aluno')),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Comentário')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('resposta', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Resposta')),
                ('resposta_data', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('denuncias', models.PositiveIntegerField(default=0, verbose_name='Denúncias')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.aluno')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos_app.curso')),
                ('curso_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursovideoapp.curso_video')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_comentario'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('curso__isnull', False)), fields=('aluno', 'curso'), name='unique_aluno_curso_comentario'), models.UniqueConstraint(condition=models.Q(('curso_video__isnull', False)), fields=('aluno', 'curso_video'), name='unique_aluno_curso_video_comentario')],
            },
        ),
    ]
