# Generated by Django 5.2.4 on 2026-04-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-data_comentario'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.RemoveConstraint(
            model_name='comentario',
            name='unique_aluno_curso_comentario',
        ),
        migrations.RemoveConstraint(
            model_name='comentario',
            name='unique_aluno_curso_video_comentario',
        ),
    ]
