# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('resumo', models.CharField(blank=True, help_text='Breve descrição que aparecerá nas listagens', max_length=300, verbose_name='Resumo')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='posts/capas/', verbose_name='Imagem de Capa')),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('aprovado', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='blog.comentario')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.post')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReacaoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Curtir 👍'), ('love', 'Amei ❤️'), ('laugh', 'Haha 😂'), ('surprised', 'Uau 😮'), ('sad', 'Triste 😢'), ('angry', 'Bravo 😡')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='blog.comentario')),
            ],
        ),
    ]
