# Generated by Django 5.2.4 on 2026-03-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('usuarios', '0004_alter_centroseguimento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comentarios', to='usuarios.aluno'),
        ),
    ]
