# Generated by Django 5.2.4 on 2025-08-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
