# Generated by Django 5.2.4 on 2025-08-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_autor_delete_autor'),
        ('usuarios', '0002_centroseguimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='blog.comentario'),
        ),
        migrations.CreateModel(
            name='ReacaoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Curtir 👍'), ('love', 'Amei ❤️'), ('laugh', 'Haha 😂'), ('surprised', 'Uau 😮'), ('sad', 'Triste 😢'), ('angry', 'Bravo 😡')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='blog.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
            ],
            options={
                'unique_together': {('comentario', 'usuario', 'tipo')},
            },
        ),
    ]
