# Generated by Django 5.2.4 on 2026-08-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentario_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duracao_video',
            field=models.CharField(blank=True, max_length=20, verbose_name='Duração do vídeo'),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo_conteudo',
            field=models.CharField(choices=[('artigo', 'Artigo'), ('video', 'Notícia em vídeo')], default='artigo', max_length=12, verbose_name='Tipo de conteúdo'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL pública do vídeo, por exemplo YouTube ou Vimeo.', verbose_name='URL do vídeo'),
        ),
    ]
