# Generated by Django 5.2.4 on 2026-08-21 07:49

import django.core.validators
import django.db.models.deletion
import mercado.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=220)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria do Mercado',
                'verbose_name_plural': 'Categorias do Mercado',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LojaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('logotipo', models.ImageField(blank=True, upload_to='mercado/lojas/')),
                ('email_operacional', models.EmailField(blank=True, max_length=254)),
                ('telefone_operacional', models.CharField(blank=True, max_length=30)),
                ('endereco_recolha', models.CharField(max_length=220)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(default='Luanda', max_length=100)),
                ('provincia', models.CharField(default='Luanda', max_length=100)),
                ('politica_garantia', models.TextField(blank=True)),
                ('verificada', models.BooleanField(db_index=True, default=False)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loja parceira',
                'verbose_name_plural': 'Lojas parceiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(default=mercado.models.gerar_referencia_pedido_mercado, max_length=80, unique=True)),
                ('nome_comprador', models.CharField(max_length=160)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('telefone_comprador', models.CharField(max_length=30)),
                ('endereco_entrega', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(default='Luanda', max_length=100)),
                ('provincia', models.CharField(default='Luanda', max_length=100)),
                ('referencia_endereco', models.CharField(blank=True, max_length=200)),
                ('observacao_comprador', models.CharField(blank=True, max_length=300)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moeda', models.CharField(default='AOA', max_length=3)),
                ('status', models.CharField(choices=[('A_VALIDAR', 'A validar disponibilidade'), ('AGUARDA_PAGAMENTO', 'A aguardar pagamento'), ('PAGO_RECOLHA', 'Pago — a recolher'), ('PREPARAR_ENTREGA', 'Em preparação para entrega'), ('EM_ENTREGA', 'Em entrega'), ('ENTREGUE', 'Entregue'), ('OCORRENCIA', 'Com ocorrência'), ('CANCELADO', 'Cancelado'), ('REEMBOLSO_PENDENTE', 'Reembolso pendente'), ('REEMBOLSADO', 'Reembolsado')], db_index=True, default='A_VALIDAR', max_length=24)),
                ('referencia_pagamento', models.CharField(blank=True, db_index=True, max_length=100)),
                ('codigo_entrega', models.CharField(default=mercado.models.gerar_codigo_entrega, max_length=12)),
                ('disponibilidade_confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('pagamento_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('recolhido_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('comprovativo_recolha', models.FileField(blank=True, upload_to='mercado/recolhas/')),
                ('comprovativo_entrega', models.FileField(blank=True, upload_to='mercado/entregas/')),
                ('notas_admin', models.TextField(blank=True)),
                ('motivo_ocorrencia', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_mercado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido do Mercado',
                'verbose_name_plural': 'Pedidos do Mercado',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('resumo', models.CharField(max_length=260)),
                ('descricao', models.TextField()),
                ('imagem_principal', models.ImageField(blank=True, upload_to='mercado/produtos/')),
                ('imagens', models.JSONField(blank=True, default=list, help_text='URLs adicionais de imagens do produto.')),
                ('especificacoes', models.JSONField(blank=True, default=dict, help_text='Características técnicas apresentadas ao comprador.')),
                ('condicao', models.CharField(choices=[('NOVO', 'Novo'), ('RECONDICIONADO', 'Recondicionado')], default='NOVO', max_length=20)),
                ('garantia', models.CharField(blank=True, max_length=180)),
                ('custo_aquisicao', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('moeda', models.CharField(default='AOA', max_length=3)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('disponibilidade_confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('prazo_entrega_dias', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('INDISPONIVEL', 'Indisponível'), ('ARQUIVADO', 'Arquivado')], db_index=True, default='RASCUNHO', max_length=16)),
                ('destaque', models.BooleanField(db_index=True, default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='mercado.categoriamercado')),
                ('disponibilidade_confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_mercado_confirmados', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='mercado.lojaparceira')),
            ],
            options={
                'verbose_name': 'Produto do Mercado',
                'verbose_name_plural': 'Produtos do Mercado',
                'ordering': ['-destaque', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='mercado.pedidomercado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedidos', to='mercado.produtomercado')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedidomercado',
            index=models.Index(fields=['status', 'criado_em'], name='mercado_ped_status_81cfeb_idx'),
        ),
        migrations.AddIndex(
            model_name='produtomercado',
            index=models.Index(fields=['status', 'destaque'], name='mercado_pro_status_ed6cfd_idx'),
        ),
    ]
