# Generated by Django 5.2.4 on 2026-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomercado',
            name='estafeta_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedidomercado',
            name='estafeta_telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pedidomercado',
            name='previsao_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
