# Generated by Django 5.2.4 on 2026-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_categorias_iniciais_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomercado',
            name='imagem_url_publica',
            field=models.CharField(blank=True, help_text='URL pública de imagem quando o ficheiro não é enviado ao servidor.', max_length=500),
        ),
    ]
