# Generated by Django 5.2.4 on 2026-08-21 09:48

import mercado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_reserva_automatica_de_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomercado',
            name='reserva_expira_em',
            field=models.DateTimeField(blank=True, db_index=True, default=mercado.models.gerar_expiracao_reserva, null=True),
        ),
    ]
