# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cursos_app', '0002_initial'),
        ('gestoreduka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('RECUPERACAO', 'Recuperação de Senha')], max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('GESTOR', 'Gestor de Centro'), ('BIBLIOTECA', 'Bibliotecário'), ('ESCOLA', 'Escola'), ('EMPRESA', 'Empresa')], default='ALUNO', max_length=20, verbose_name='Tipo de Usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('codigo_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de registro')),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('PUBLICA', 'Pública'), ('ESCOLAR', 'escolar'), ('UNVERSITARIA', 'universitaria'), ('ESPECIALIZADA', 'especializada'), ('COMUNITARIA', 'comunitaria')], max_length=50, verbose_name='Tipo de Biblioteca')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('experiencia_anos', models.IntegerField(default=0, verbose_name='Anos de Experiência')),
                ('nif', models.CharField(max_length=18, unique=True, verbose_name='NIF')),
                ('ramo_atuacao', models.CharField(choices=[('TECNOLOGIA_INFORMACAO', 'tecnologia de informacao'), ('NEGOCIO', 'negocio'), ('LINGUAS', 'linguas'), ('ESPECIALIZADA', 'especializada'), ('CIENCIAS', 'ciencias'), ('ARTES', 'artes'), ('ENGENHARIA', 'engenharia'), ('SAUDE', 'saude'), ('OUTRO', 'outro')], max_length=100, verbose_name='Ramo de Atuação')),
                ('numero_funcionarios', models.IntegerField(verbose_name='Número de Funcionários')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Escola')),
                ('codigo_escola', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Código INEP')),
                ('tipo', models.CharField(choices=[('PUBLICA', 'Pública'), ('PARTICULAR', 'Particular'), ('COMUNITARIA', 'Comunitária')], max_length=20, verbose_name='Tipo de Escola')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'db_table': 'escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfil_alunos/', verbose_name='Imagem de Perfil')),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização (Fallback)')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Perfil do Aluno',
                'verbose_name_plural': 'Perfis dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='CentroSeguimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Seguimento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_seguidos', to='usuarios.aluno', verbose_name='Aluno')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação')),
            ],
            options={
                'verbose_name': 'Seguimento de Centro',
                'verbose_name_plural': 'Seguimentos de Centros',
                'unique_together': {('aluno', 'centro')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=1000, verbose_name='Comentário')),
                ('avaliacao', models.IntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('status_aluno', models.CharField(choices=[('INS', 'Inscrito'), ('COM', 'Concluído'), ('AND', 'Em Andamento')], default='AND', max_length=3, verbose_name='Status do Aluno')),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Comentário')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovado', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('resposta', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Resposta')),
                ('resposta_data', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('denuncias', models.PositiveIntegerField(default=0, verbose_name='Denúncias')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_comentario'],
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
