# Generated by Django 5.2.4 on 2026-02-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0006_delete_galeria'),
        ('cursovideoapp', '0003_alter_curso_video_categoria_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comentario',
            name='curso_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursovideoapp.curso_video'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos_app.curso'),
        ),
    ]
