# Generated by Django 5.2 on 2025-04-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCentroDeFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='centros/', verbose_name='Imagem ou Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='centros/banners/', verbose_name='Imagem de Capa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Centro')),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Híbrido', 'Híbrido')], default='Presencial', max_length=20, verbose_name='Modalidade')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('destaque', models.BooleanField(default=False, verbose_name='Centro em Destaque')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('centro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='usuarios.centrodeformacao')),
            ],
        ),
    ]
