# Generated by Django 5.2.4 on 2025-08-04 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0002_areaformacao_certificacao_depoimento_diferencial_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroSeguimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Seguimento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_seguidos', to='usuarios.aluno', verbose_name='Aluno')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação')),
            ],
            options={
                'verbose_name': 'Seguimento de Centro',
                'verbose_name_plural': 'Seguimentos de Centros',
                'unique_together': {('aluno', 'centro')},
            },
        ),
    ]
