# Generated by Django 5.2.4 on 2025-09-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_centroseguimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
