# Generated by Django 5.2.4 on 2026-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0006_delete_galeria'),
        ('cursovideoapp', '0003_alter_curso_video_categoria_and_more'),
        ('usuarios', '0002_alter_comentario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comentario',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', False)), fields=('aluno', 'curso'), name='unique_aluno_curso_comentario'),
        ),
        migrations.AddConstraint(
            model_name='comentario',
            constraint=models.UniqueConstraint(condition=models.Q(('curso_video__isnull', False)), fields=('aluno', 'curso_video'), name='unique_aluno_curso_video_comentario'),
        ),
    ]
