# Generated by Django 5.2 on 2025-04-19 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfil_alunos/', verbose_name='Imagem de Perfil')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Perfil do Aluno',
                'verbose_name_plural': 'Perfis dos Alunos',
            },
        ),
    ]
