# Generated by Django 5.2.4 on 2026-02-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_comentario_unique_aluno_curso_comentario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centroseguimento',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='comentario',
            name='unique_aluno_curso_comentario',
        ),
        migrations.RemoveConstraint(
            model_name='comentario',
            name='unique_aluno_curso_video_comentario',
        ),
        migrations.RemoveField(
            model_name='centroseguimento',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='centroseguimento',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='curso_video',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
        migrations.DeleteModel(
            name='CentroSeguimento',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
