# Generated by Django 5.2.7 on 2025-11-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='senha',
            field=models.CharField(default='temporaria123', max_length=128, verbose_name='Senha'),
        ),
    ]
