# Generated by Django 5.2 on 2025-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='dono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dono do Centro'),
        ),
    ]
