# Generated by Django 5.2.4 on 2026-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_centroseguimento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('GESTOR', 'Gestor de Centro Principal'), ('GESTOR_FILIAL', 'Gestor de Filial'), ('BIBLIOTECA', 'Bibliotecário'), ('ESCOLA', 'Escola'), ('EMPRESA', 'Empresa')], default='ALUNO', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
