# Generated by Django 5.2.7 on 2025-11-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_aluno_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='senha',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
    ]
