# Generated by Django 5.2.4 on 2026-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('GESTOR', 'Gestor de Centro Principal'), ('GESTOR_FILIAL', 'Gestor de Filial'), ('ESCOLA', 'Escola')], default='ALUNO', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
