# Generated by Django 5.2 on 2025-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfilcentrodeformacao_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='video_apresentacao',
            field=models.FileField(blank=True, null=True, upload_to='centros videos/', verbose_name='Vídeo de Apresentação'),
        ),
    ]
