# Generated by Django 5.2.4 on 2026-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='bilhete_frente',
            field=models.FileField(blank=True, null=True, upload_to='documentos/bilhetes/', verbose_name='BI Frente'),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='bilhete_verso',
            field=models.FileField(blank=True, null=True, upload_to='documentos/bilhetes/', verbose_name='BI Verso'),
        ),
    ]
