# Generated by Django 6.0 on 2026-01-12 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_aluno_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Localização Geográfica'),
        ),
    ]
