# Generated by Django 5.2.4 on 2026-04-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilaluno_bilhete_frente_perfilaluno_bilhete_verso'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link (opcional)')),
                ('tipo', models.CharField(choices=[('CURSO', 'Novo Curso'), ('EVENTO', 'Novo Evento'), ('ANUNCIO', 'Anúncio Institucional'), ('CHAT', 'Nova Mensagem'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Notificação do Aluno',
                'verbose_name_plural': 'Notificações dos Alunos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
