# Generated by Django 5.2.4 on 2026-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('GESTOR', 'Gestor de Centro Principal'), ('GESTOR_FILIAL', 'Gestor de Filial'), ('INSTRUTOR', 'Instrutor da Plataforma')], default='ALUNO', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
    ]
