# Generated by Django 5.2.4 on 2026-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0012_instrutor_titulo_instrutor_usuario_and_more'),
        ('usuarios', '0010_alter_usuario_tipo_usuario_delete_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='interesses',
            field=models.ManyToManyField(blank=True, related_name='alunos_interessados', to='cursos_app.categoria'),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='nivel_conhecimento',
            field=models.CharField(choices=[('B', 'Básico - Estou a começar agora'), ('I', 'Intermédio - Já tenho alguma base'), ('A', 'Avançado - Quero aprofundar conhecimentos')], default='B', max_length=1, verbose_name='Nível de Conhecimento'),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='onboarding_completo',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completo'),
        ),
    ]
