# Generated by Django 5.2.4 on 2026-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_perfilaluno_interesses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaoaluno',
            name='tipo',
            field=models.CharField(choices=[('CURSO', 'Novo Curso'), ('EVENTO', 'Novo Evento'), ('ANUNCIO', 'Anúncio Institucional'), ('CHAT', 'Nova Mensagem'), ('CARREIRA', 'Carreira e Vagas'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20),
        ),
    ]
