# Generated by Django 5.2.4 on 2026-05-15 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_notificacaoaluno_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_cadastro',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='notificacaoaluno',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacaoaluno',
            name='lida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('GESTOR', 'Gestor de Centro Principal'), ('GESTOR_FILIAL', 'Gestor de Filial'), ('INSTRUTOR', 'Instrutor da Plataforma')], db_index=True, default='ALUNO', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
