# Generated by Django 5.2.4 on 2026-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_aluno_ativo_alter_aluno_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='foto_de_capa',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_capa/', verbose_name='Foto de Capa'),
        ),
    ]
