# Generated by Django 5.2.4 on 2026-08-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0033_alter_curso_modalidade'),
        ('usuarios', '0015_create_muquissi_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidades', models.JSONField(blank=True, default=list)),
                ('objectivos', models.JSONField(blank=True, default=list)),
                ('disponibilidades', models.JSONField(blank=True, default=list)),
                ('provincias', models.JSONField(blank=True, default=list)),
                ('faixa_preco', models.CharField(choices=[('QUALQUER', 'Qualquer valor'), ('GRATUITOS', 'Apenas gratuitos'), ('ATE_25000', 'Até 25 000 Kz'), ('ATE_50000', 'Até 50 000 Kz')], default='QUALQUER', max_length=20)),
                ('quer_certificado', models.BooleanField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_aprendizagem', to='usuarios.aluno')),
                ('categorias', models.ManyToManyField(blank=True, related_name='preferencias_aprendizagem', to='cursos_app.categoria')),
            ],
            options={
                'verbose_name': 'Preferência de aprendizagem',
                'verbose_name_plural': 'Preferências de aprendizagem',
            },
        ),
    ]
