# Generated by Django 5.2.4 on 2026-08-17 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_preferenciaaprendizagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_na_plataforma', models.BooleanField(default=True, verbose_name='Notificações na plataforma')),
                ('receber_por_email', models.BooleanField(default=True, verbose_name='Resumo por e-mail')),
                ('novos_cursos', models.BooleanField(default=True, verbose_name='Novos cursos')),
                ('novas_turmas', models.BooleanField(default=True, verbose_name='Novas turmas')),
                ('novos_livros', models.BooleanField(default=True, verbose_name='Novos livros')),
                ('novos_eventos', models.BooleanField(default=True, verbose_name='Novos eventos')),
                ('atualizacoes_aprendizagem', models.BooleanField(default=True, verbose_name='Lembretes de aprendizagem')),
                ('calendario_e_feriados', models.BooleanField(default=True, verbose_name='Calendário e feriados')),
                ('resumo_semanal', models.BooleanField(default=True, verbose_name='Resumo semanal')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Preferência de notificação',
                'verbose_name_plural': 'Preferências de notificações',
            },
        ),
    ]
