# Generated by Django 5.2.4 on 2026-08-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_preferencianotificacaoaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoverificacao',
            name='tipo',
            field=models.CharField(choices=[('CADASTRO', 'Cadastro'), ('RECUPERACAO', 'Recuperação de Senha'), ('FORMADOR', 'Candidatura de Formador')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='CandidaturaFormador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_profissional', models.CharField(max_length=100)),
                ('area_especializacao', models.CharField(choices=[('TECNOLOGIA_INFORMACAO', 'Tecnologia de Informação'), ('NEGOCIO', 'Negócio'), ('LINGUAS', 'Línguas'), ('ESPECIALIZADA', 'Especializada'), ('CIENCIAS', 'Ciências'), ('ARTES', 'Artes'), ('ENGENHARIA', 'Engenharia'), ('SAUDE', 'Saúde'), ('OUTRO', 'Outro')], max_length=100)),
                ('biografia', models.TextField()),
                ('proposta_curso', models.TextField()),
                ('teste_aprovado', models.BooleanField(default=False)),
                ('pontuacao_teste', models.PositiveSmallIntegerField(default=0)),
                ('codigo_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDENTE_ANALISE', 'Pendente de análise'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], db_index=True, default='PENDENTE_ANALISE', max_length=24)),
                ('observacao_equipa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidatura_formador', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Candidatura de formador',
                'verbose_name_plural': 'Candidaturas de formadores',
                'ordering': ['-criado_em'],
            },
        ),
    ]
