# Generated by Django 5.2.4 on 2026-08-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_codigoverificacao_tipo_candidaturaformador'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencianotificacaoaluno',
            name='receber_push',
            field=models.BooleanField(default=False, verbose_name='Notificações no dispositivo'),
        ),
        migrations.CreateModel(
            name='SubscricaoWebPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('chave_p256dh', models.CharField(max_length=255)),
                ('chave_auth', models.CharField(max_length=255)),
                ('agente', models.CharField(blank=True, max_length=300)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ultimo_envio_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_falha_em', models.DateTimeField(blank=True, null=True)),
                ('falhas_consecutivas', models.PositiveSmallIntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscricoes_web_push', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Subscrição Web Push',
                'verbose_name_plural': 'Subscrições Web Push',
                'indexes': [models.Index(fields=['aluno', 'ativa'], name='usuarios_su_aluno_i_fa091e_idx')],
            },
        ),
    ]
