# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Área')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Área de Estágio',
                'verbose_name_plural': 'Áreas de Estágio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Benefício')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Benefício do Estágio',
                'verbose_name_plural': 'Benefícios do Estágio',
            },
        ),
        migrations.CreateModel(
            name='InscricaoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='estagios/curriculos/', verbose_name='Currículo')),
                ('carta_motivacao', models.TextField(verbose_name='Carta de Motivação')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status da Inscrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Inscrição de Estágio',
                'verbose_name_plural': 'Inscrições de Estágio',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Estágio')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(verbose_name='Descrição Completa')),
                ('resumo', models.TextField(max_length=200, verbose_name='Resumo')),
                ('tipo_remuneracao', models.CharField(choices=[('remunerado', 'Remunerado'), ('bolsa_auxilio', 'Bolsa Auxílio'), ('nao_remunerado', 'Não Remunerado'), ('beneficios', 'Apenas Benefícios')], default='bolsa_auxilio', max_length=20, verbose_name='Tipo de Remuneração')),
                ('valor_remuneracao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Remuneração')),
                ('beneficios', models.TextField(blank=True, verbose_name='Benefícios Oferecidos')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('hibrido', 'Híbrido'), ('remoto', 'Remoto')], default='presencial', max_length=20, verbose_name='Modalidade')),
                ('duracao_meses', models.IntegerField(choices=[(3, '3 Meses'), (4, '4 Meses'), (5, '5 Meses'), (6, '6 Meses'), (8, '8 Meses'), (12, '12 Meses')], default=6, verbose_name='Duração (meses)')),
                ('carga_horaria_semanal', models.IntegerField(default=30, verbose_name='Carga Horária Semanal (horas)')),
                ('vagas_disponiveis', models.IntegerField(default=1, verbose_name='Vagas Disponíveis')),
                ('vagas_preenchidas', models.IntegerField(default=0, verbose_name='Vagas Preenchidas')),
                ('local_trabalho', models.CharField(max_length=255, verbose_name='Local de Trabalho')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('provincia', models.CharField(max_length=100, verbose_name='Província')),
                ('requisitos', models.TextField(verbose_name='Requisitos')),
                ('competencias_desejadas', models.TextField(blank=True, verbose_name='Competências Desejadas')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('data_limite_inscricao', models.DateField(verbose_name='Data Limite para Inscrições')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Em Deste')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='estagios/imagens/', verbose_name='Imagem Principal')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estagio.areaestagio', verbose_name='Área do Estágio')),
            ],
            options={
                'verbose_name': 'Estágio',
                'verbose_name_plural': 'Estágios',
                'ordering': ['-data_publicacao', '-destaque'],
            },
        ),
    ]
