# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estagio', '0001_initial'),
        ('gestoreduka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='centro_formacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação'),
        ),
        migrations.AddField(
            model_name='beneficioestagio',
            name='estagio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_estagio', to='estagio.estagio', verbose_name='Estágio'),
        ),
    ]
