# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estagio', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaoestagio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_estagio', to='usuarios.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='inscricaoestagio',
            name='estagio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='estagio.estagio', verbose_name='Estágio'),
        ),
        migrations.AlterUniqueTogether(
            name='inscricaoestagio',
            unique_together={('estagio', 'aluno')},
        ),
    ]
