# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='cursos/aulas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])])),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('duracao_segundos', models.PositiveIntegerField(default=0, help_text='Duração em segundos')),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('requer_conclusao_anterior', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('tempo_assistido', models.PositiveIntegerField(default=0, help_text='Tempo assistido em segundos')),
                ('data_ultimo_acesso', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('instrutor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='cursos/capas/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('destaque', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursovideoapp.categoria')),
            ],
        ),
    ]
