# Generated by Django 5.2.4 on 2026-01-31 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursovideoapp.curso_video'),
        ),
        migrations.AddField(
            model_name='curso_video',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='progressoaula',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='progressoaula',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursovideoapp.aula'),
        ),
        migrations.AlterUniqueTogether(
            name='progressoaula',
            unique_together={('aluno', 'aula')},
        ),
        migrations.CreateModel(
            name='FavoritoCursoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_video', to='usuarios.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='cursovideoapp.curso_video')),
            ],
            options={
                'verbose_name': 'Favorito Curso Vídeo',
                'verbose_name_plural': 'Favoritos Cursos Vídeo',
                'ordering': ['-data_adicao'],
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
