# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursovideoapp', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso_video',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursovideoapp.curso_video'),
        ),
        migrations.AddField(
            model_name='progressoaula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='progressoaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursovideoapp.aula'),
        ),
        migrations.AlterUniqueTogether(
            name='progressoaula',
            unique_together={('aluno', 'aula')},
        ),
    ]
