# Generated by Django 5.2.4 on 2025-08-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Curso_video',
        ),
    ]
