# Generated by Django 5.2.4 on 2025-08-29 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0002_rename_curso_curso_video'),
        ('usuarios', '0002_centroseguimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='duracao_segundos',
            field=models.PositiveIntegerField(default=0, help_text='Duração em segundos'),
        ),
        migrations.AddField(
            model_name='aula',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso_video',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='video',
            field=models.FileField(upload_to='cursos/aulas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.CreateModel(
            name='ProgressoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('tempo_assistido', models.PositiveIntegerField(default=0, help_text='Tempo assistido em segundos')),
                ('data_ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursovideoapp.aula')),
            ],
            options={
                'unique_together': {('aluno', 'aula')},
            },
        ),
    ]
