# Generated by Django 5.2.4 on 2026-02-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0006_delete_galeria'),
        ('cursovideoapp', '0002_aula_curso_curso_video_inscritos_progressoaula_aluno_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso_video',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_video', to='cursos_app.categoria'),
        ),
        migrations.AlterField(
            model_name='curso_video',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos_video', to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='curso_video',
            name='instrutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_video', to='cursos_app.instrutor'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
