# Generated by Django 5.2.4 on 2025-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0003_aula_duracao_segundos_aula_visualizacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='requer_conclusao_anterior',
            field=models.BooleanField(default=True),
        ),
    ]
