# Generated by Django 5.2.4 on 2026-03-19 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0003_alter_curso_video_categoria_and_more'),
        ('usuarios', '0004_alter_centroseguimento_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('codigo_verificacao', models.CharField(blank=True, max_length=20, unique=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='usuarios.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_emitidos', to='cursovideoapp.curso_video')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
