# Generated by Django 5.2.4 on 2026-04-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0004_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='video',
        ),
        migrations.AddField(
            model_name='aula',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link do YouTube, Vimeo ou ficheiro de vídeo externo', max_length=500, null=True, verbose_name='URL do Vídeo'),
        ),
    ]
