# Generated by Django 5.2.4 on 2025-09-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0004_aula_requer_conclusao_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso_video',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
