# Generated by Django 5.2.4 on 2026-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0005_remove_aula_video_aula_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso_video',
            name='is_pago',
            field=models.BooleanField(default=False, verbose_name='Curso Pago?'),
        ),
        migrations.AddField(
            model_name='curso_video',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço (KZ)'),
        ),
    ]
