# Generated by Django 5.2.4 on 2026-05-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0006_curso_video_is_pago_curso_video_preco'),
        ('usuarios', '0008_notificacaoaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Nota')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_video', to='usuarios.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_alunos', to='cursovideoapp.aula')),
            ],
            options={
                'verbose_name': 'Nota de Aula',
                'verbose_name_plural': 'Notas de Aula',
                'unique_together': {('aluno', 'aula')},
            },
        ),
    ]
