# Generated by Django 5.2.4 on 2026-05-01 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0007_notaaula'),
        ('usuarios', '0008_notificacaoaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Dúvida ou Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_aulas', to='usuarios.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursovideoapp.aula')),
            ],
            options={
                'verbose_name': 'Comentário de Aula',
                'verbose_name_plural': 'Comentários de Aula',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
