# Generated by Django 5.2.4 on 2026-05-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0011_curso_video_preview_file'),
        ('cursovideoapp', '0008_comentarioaula'),
        ('usuarios', '0008_notificacaoaluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarioaula',
            options={'ordering': ['data_criacao'], 'verbose_name': 'Comentário de Aula', 'verbose_name_plural': 'Comentários de Aula'},
        ),
        migrations.AddField(
            model_name='comentarioaula',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_aulas', to='cursos_app.instrutor'),
        ),
        migrations.AddField(
            model_name='comentarioaula',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cursovideoapp.comentarioaula'),
        ),
        migrations.AlterField(
            model_name='comentarioaula',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_aulas', to='usuarios.aluno'),
        ),
    ]
