# Generated by Django 5.2.4 on 2026-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0009_alter_comentarioaula_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={},
        ),
        migrations.AddField(
            model_name='aula',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Aula'),
        ),
    ]
