# Generated by Django 5.2.4 on 2026-05-01 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0010_alter_aula_options_aula_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='cursovideoapp.curso_video')),
            ],
            options={
                'verbose_name': 'Aviso do Curso',
                'verbose_name_plural': 'Avisos do Curso',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome do Recurso')),
                ('arquivo', models.FileField(upload_to='cursos/materiais/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar', 'txt', 'docx', 'pptx'])], verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='cursovideoapp.aula')),
            ],
            options={
                'verbose_name': 'Material de Aula',
                'verbose_name_plural': 'Materiais de Aula',
            },
        ),
    ]
