# Generated by Django 5.2.4 on 2026-05-06 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0011_avisocurso_materialaula'),
        ('usuarios', '0012_alter_notificacaoaluno_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='nota_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nota Final'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='total_exercicios_concluidos',
            field=models.IntegerField(default=0, verbose_name='Total de Exercícios Concluídos'),
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Exercício de Fixação', max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercicio', to='cursovideoapp.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('explicacao', models.TextField(blank=True, help_text='Explicada após responder', null=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='cursovideoapp.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('is_correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='cursovideoapp.questao')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.DecimalField(decimal_places=2, help_text='Percentagem de acerto (0-100)', max_digits=5)),
                ('acertos', models.PositiveIntegerField(default=0)),
                ('total_questoes', models.PositiveIntegerField(default=0)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_exercicios', to='usuarios.aluno')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='cursovideoapp.exercicio')),
            ],
            options={
                'unique_together': {('aluno', 'exercicio')},
            },
        ),
        migrations.CreateModel(
            name='RespostaEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False)),
                ('alternativa_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursovideoapp.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursovideoapp.questao')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cursovideoapp.resultadoexercicio')),
            ],
        ),
    ]
