# Generated by Django 5.2.4 on 2026-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0012_certificado_nota_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='resumo_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo da IA'),
        ),
    ]
