# Generated by Django 5.2.4 on 2026-05-06 16:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0013_aula_resumo_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome do Recurso')),
                ('arquivo', models.FileField(upload_to='cursos/materiais_gerais/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar', 'txt', 'docx', 'pptx'])], verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_gerais', to='cursovideoapp.curso_video')),
            ],
            options={
                'verbose_name': 'Material do Curso',
                'verbose_name_plural': 'Materiais do Curso',
            },
        ),
    ]
