# Generated by Django 5.2.4 on 2026-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0014_materialcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='analise_ia_competencias',
            field=models.TextField(blank=True, null=True, verbose_name='Perfil de Competências (IA)'),
        ),
    ]
