# Generated by Django 5.2.4 on 2026-05-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0015_certificado_analise_ia_competencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='ordem',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='aula',
            name='visualizacoes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='curso_video',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='curso_video',
            name='destaque',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='curso_video',
            name='is_pago',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Curso Pago?'),
        ),
        migrations.AlterField(
            model_name='progressoaula',
            name='concluida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='progressoaula',
            name='data_ultimo_acesso',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
