# Generated by Django 6.0.5 on 2026-06-14 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0019_remove_curso_filial_curso_filiais_turma_filial'),
        ('cursovideoapp', '0016_alter_aula_ordem_alter_aula_visualizacoes_and_more'),
        ('gestoreduka', '0016_alter_notificacaogestor_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EMITIDO', 'Emitido'), ('REJEITADO', 'Rejeitado')], default='EMITIDO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='curso_video',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_video_centro', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AlterField(
            model_name='curso_video',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_video', to='cursos_app.instrutor'),
        ),
    ]
