# Generated by Django 5.2.4 on 2026-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0017_certificado_aprovado_por_certificado_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso_video',
            name='is_original_edukangola',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se o vídeo-curso foi produzido pela própria plataforma EdukAngola.', verbose_name='Original EdukAngola?'),
        ),
    ]
