# Generated by Django 5.2.4 on 2026-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursovideoapp', '0019_turmavideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioaula',
            name='resolvida',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
