# Generated by Django 5.2.4 on 2026-08-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cursovideoapp', '0021_catalogo_video_exclusivo_edukangola'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSubscricaoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do plano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço mensal')),
                ('moeda', models.CharField(default='AOA', max_length=3, verbose_name='Moeda')),
                ('periodo_dias', models.PositiveIntegerField(default=30, verbose_name='Duração em dias')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Disponível para novas subscrições')),
                ('destaque', models.BooleanField(default=False, verbose_name='Plano em destaque')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de apresentação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Plano de subscrição de vídeo', 'verbose_name_plural': 'Planos de subscrição de vídeo', 'ordering': ['ordem', 'preco', 'id']},
        ),
        migrations.CreateModel(
            name='AssinaturaVideoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de pagamento'), ('ATIVA', 'Activa'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=12, verbose_name='Estado')),
                ('data_inicio', models.DateTimeField(verbose_name='Início da subscrição')),
                ('data_fim', models.DateTimeField(db_index=True, verbose_name='Fim da subscrição')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor cobrado')),
                ('moeda', models.CharField(default='AOA', max_length=3, verbose_name='Moeda')),
                ('referencia_pagamento', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Referência do pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscricoes_video', to='usuarios.aluno')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscricoes', to='cursovideoapp.planosubscricaovideo')),
            ],
            options={'verbose_name': 'Subscrição de vídeo do aluno', 'verbose_name_plural': 'Subscrições de vídeo dos alunos', 'ordering': ['-data_fim', '-id']},
        ),
    ]
