import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, ExternalLink, Hash, Play, Radio, Video } from "lucide-react";
import { newsCover } from "../lib/news-covers";

function getVideoId(url = "") { const match = url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([^?&/]+)/i); return match?.[1] || ""; }
function formatDate(value) { try { return new Intl.DateTimeFormat("pt-AO", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(value)); } catch { return value?.slice(0, 10) || ""; } }
function overlap(post, current) { const sameCategory = post.categoria?.slug && post.categoria.slug === current.categoria?.slug ? 3 : 0; const currentTags = new Set((current.tags || []).map((tag) => tag.slug)); const sharedTags = (post.tags || []).filter((tag) => currentTags.has(tag.slug)).length * 2; return sameCategory + sharedTags; }

export default function BlogPostPage({ slug, onNavigate }) {
  const [post, setPost] = useState(null);
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; Promise.all([fetch(`/api/v1/blog/${encodeURIComponent(slug)}/`).then((response) => response.ok ? response.json() : Promise.reject(new Error("not-found"))), fetch("/api/v1/blog/").then((response) => response.ok ? response.json() : [])]).then(([current, list]) => { if (active) { setPost(current); setPosts(Array.isArray(list) ? list : list.results || []); } }).catch(() => active && setPost(null)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [slug]);
  const related = useMemo(() => post ? posts.filter((item) => item.slug !== post.slug).sort((a, b) => overlap(b, post) - overlap(a, post)).slice(0, 3) : [], [post, posts]);
  if (loading) return <main className="page-width blog-detail-loading"><p className="page-empty">A carregar notícia.</p></main>;
  if (!post) return <main className="page-width"><div className="page-empty"><strong>Notícia não encontrada.</strong><button className="primary-action" onClick={() => onNavigate("/blog")}>Voltar ao blog</button></div></main>;
  const videoId = getVideoId(post.video_url);
  return <main className="blog-detail"><div className="page-width"><button className="back-link" onClick={() => onNavigate("/blog")}><ArrowLeft size={16} /> Voltar às notícias</button><article className="blog-article"><div className="blog-article-head"><span className="eyebrow"><Radio size={15} /> {post.tipo_conteudo === "video" ? "Edukangola Agora" : "Blog e notícias"}</span><h1>{post.titulo}</h1><div className="blog-meta"><CalendarDays size={14} /> {formatDate(post.publicado_em)} {post.categoria?.nome && <><span>·</span>{post.categoria.nome}</>} {post.tipo_conteudo === "video" && <><Video size={14} /> {post.duracao_video || "Vídeo"}</>}</div>{(post.categoria || (post.tags || []).length > 0) && <div className="blog-article-tags">{post.categoria && <span><Hash size={12} /> {post.categoria.nome}</span>}{(post.tags || []).map((tag) => <span key={tag.slug}><Hash size={12} /> {tag.nome}</span>)}</div>}</div>{post.tipo_conteudo === "video" && videoId ? <div className="blog-video-frame"><iframe title={post.titulo} src={`https://www.youtube.com/embed/${videoId}`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div> : post.tipo_conteudo === "video" && post.video_url ? <a className="blog-external-video" href={post.video_url} target="_blank" rel="noreferrer"><Play size={18} /> Abrir vídeo da notícia <ExternalLink size={15} /></a> : <img className="blog-article-cover" src={newsCover(post)} alt="" />}<div className="blog-article-content">{post.resumo && <p className="blog-article-summary">{post.resumo}</p>}<div className="blog-article-text">{post.conteudo}</div></div></article>{related.length > 0 && <section className="blog-related"><div className="news-section-heading"><div><span className="eyebrow muted">Continue a explorar</span><h2>Notícias relacionadas</h2></div><button className="text-action" onClick={() => onNavigate("/blog")}>Ver todas <ArrowRight size={15} /></button></div><div className="blog-related-grid">{related.map((item) => <button key={item.id} className="related-card" onClick={() => onNavigate(`/blog/${item.slug}`)}><img className="related-image" src={newsCover(item)} alt="" /><span><small>{item.categoria?.nome || "Notícia"}</small><strong>{item.titulo}</strong><em>{formatDate(item.publicado_em)}</em></span><ArrowRight size={16} /></button>)}</div></section>}</div></main>;
}
