import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, MoreHorizontal, SlidersHorizontal } from "lucide-react";
import CatalogFilters from "../components/CatalogFilters";
import CourseCard from "../components/CourseCard";
import { backendUrl } from "../lib/backend-url";
import { useI18n } from "../lib/i18n";
import { etiquetaProduto, isVideoCurso, rotaDetalheProduto, textoRodapeProduto, tipoProduto } from "../lib/product-type";
import "./public-pages.css";
import "./catalog-page.css";

const PAGE_SIZE = 9;
const normalize = (text) => (text || "").toLocaleLowerCase("pt-PT").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
const makeFilters = (source = {}) => ({ q: source.q || "", tipo: source.tipo || "", categoria: source.categoria || "", provincia: source.provincia || "", pagamento: source.pagamento || "", turma: source.turma || "", ordenar: source.ordenar || "recentes", pagina: Math.max(1, Number(source.pagina) || 1) });
const formatCentre = (name) => name?.replace(/Eduka-Angola/gi, "Edukangola") ?? "Centro de formação";
const paginationItems = (currentPage, totalPages) => { if (totalPages <= 7) return Array.from({ length: totalPages }, (_, index) => index + 1); const items = [1]; if (currentPage > 4) items.push("start-gap"); for (let page = Math.max(2, currentPage - 1); page <= Math.min(totalPages - 1, currentPage + 1); page += 1) items.push(page); if (currentPage < totalPages - 3) items.push("end-gap"); items.push(totalPages); return items; };

export default function CoursesPage({ data, loading, initialFilters, onNavigate, onAnnounce }) {
  const { t } = useI18n();
  const [filters, setFilters] = useState(() => makeFilters(initialFilters));
  useEffect(() => setFilters(makeFilters(initialFilters)), [initialFilters.q, initialFilters.tipo, initialFilters.categoria, initialFilters.provincia, initialFilters.pagamento, initialFilters.turma, initialFilters.ordenar, initialFilters.pagina]);
  const courses = data?.cursos || [];
  const turmaPorCurso = useMemo(() => { const result = new Map(); (data?.turmas_abertas || []).forEach((turma) => { const current = result.get(turma.id); if (!current || turma.inicio < current.inicio) result.set(turma.id, turma); }); return result; }, [data]);
  const options = useMemo(() => ({ categorias: [...new Set(courses.map((course) => course.categoria).filter(Boolean))].sort(), provincias: [...new Set(courses.filter((course) => !isVideoCurso(course)).map((course) => course.provincia).filter(Boolean))].sort() }), [courses]);
  const cards = useMemo(() => courses.map((course) => { const turma = isVideoCurso(course) ? null : turmaPorCurso.get(course.id); return { ...course, productType: tipoProduto(course), productLabel: etiquetaProduto(course), centre: formatCentre(course.centro), title: course.titulo, category: course.categoria, mode: course.modalidade, imageUrl: course.imagem_url, detailUrl: rotaDetalheProduto(course), inscricaoUrl: backendUrl(course.inscricao_url), schedule: textoRodapeProduto(course, turma), turma }; }), [courses, turmaPorCurso]);
  const totalDoTipo = filters.tipo === "video" ? cards.filter((course) => course.productType === "video").length : filters.tipo === "formacao" ? cards.filter((course) => course.productType !== "video").length : cards.length;
  const filtered = useMemo(() => cards.filter((course) => { const search = !filters.q || normalize(`${course.title} ${course.category} ${course.centre} ${course.mode}`).includes(normalize(filters.q)); const product = !filters.tipo || (filters.tipo === "video" ? course.productType === "video" : course.productType !== "video"); const category = !filters.categoria || course.category === filters.categoria; const province = !filters.provincia || course.provincia === filters.provincia; const initialValue = course.pagamento?.valor_inicial || 0; const payment = !filters.pagamento || (filters.pagamento === "gratuito" && course.is_gratuito) || (filters.pagamento === "sem-pagamento-agora" && !course.is_gratuito && initialValue === 0) || (filters.pagamento === "com-pagamento-agora" && initialValue > 0); const classOpen = !filters.turma || (course.productType !== "video" && Boolean(course.turma)); return search && product && category && province && payment && classOpen; }).sort((a, b) => { if (filters.ordenar === "alfabetica") return a.title.localeCompare(b.title, "pt-PT"); if (filters.ordenar === "proxima-turma") return (a.turma?.inicio || "9999-12-31").localeCompare(b.turma?.inicio || "9999-12-31"); if (filters.ordenar === "valor-inicial") return (a.pagamento?.valor_inicial || 0) - (b.pagamento?.valor_inicial || 0); return new Date(b.data_publicacao) - new Date(a.data_publicacao); }), [cards, filters]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const currentPage = Math.min(Math.max(filters.pagina, 1), totalPages); const startIndex = (currentPage - 1) * PAGE_SIZE; const visibleCourses = filtered.slice(startIndex, startIndex + PAGE_SIZE);
  const navigateWithFilters = (next) => { const params = new URLSearchParams(); Object.entries(next).forEach(([key, item]) => { if (item && !(key === "ordenar" && item === "recentes") && !(key === "pagina" && Number(item) === 1)) params.set(key, item); }); onNavigate(`/cursos${params.size ? `?${params.toString()}` : ""}`, false); };
  const updateFilters = (field, value) => { const next = { ...filters, [field]: value, pagina: 1 }; if (field === "tipo" && value === "video") { next.provincia = ""; next.turma = ""; } setFilters(next); navigateWithFilters(next); };
  const resetFilters = () => { const empty = makeFilters(); setFilters(empty); onNavigate("/cursos", false); };
  const goToPage = (page) => { const next = { ...filters, pagina: Math.min(Math.max(page, 1), totalPages) }; setFilters(next); navigateWithFilters(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const pageTitle = filters.q ? `${t("catalog.results")} “${filters.q}”` : filters.tipo === "video" ? t("catalog.videoTitle") : filters.tipo === "formacao" ? t("catalog.classTitle") : t("catalog.allTitle");
  return <main><section className="subpage-hero catalog-page-hero"><div className="page-width"><span className="eyebrow"><SlidersHorizontal size={15} /> {t("catalog.eyebrow")}</span><h1>{t("catalog.hero")}</h1><p>{t("catalog.heroCopy")}</p></div></section><section className="page-width catalog-results"><div className="catalog-shell"><CatalogFilters filters={filters} options={options} resultCount={filtered.length} totalCount={totalDoTipo} onChange={updateFilters} onReset={resetFilters} /><div className="catalog-results-main"><div className="catalog-results-head"><div><span className="eyebrow muted">{t("catalog.results")}</span><h2>{pageTitle}</h2><div className="catalog-result-meta">{filters.tipo && <span>{filters.tipo === "video" ? t("catalog.video") : t("catalog.class")}</span>}{filters.categoria && <span>{filters.categoria}</span>}{filters.provincia && <span>{filters.provincia}</span>}{filters.turma && <span>{t("catalog.openClass")}</span>}</div></div><span className="catalog-results-count">{filtered.length} {t("catalog.of")} {totalDoTipo} {t("catalog.products")}</span></div>{loading ? <p className="page-empty">{t("catalog.results")}</p> : filtered.length ? <><div className="catalog-grid">{visibleCourses.map((course) => <CourseCard key={course.id} course={course} onSave={(message) => onAnnounce(message === "AUTH_REQUIRED" ? "Os cursos guardados estarão disponíveis após o login." : message)} />)}</div>{totalPages > 1 && <nav className="catalog-pagination" aria-label={t("catalog.eyebrow")}><p>{t("catalog.range")} <strong>{startIndex + 1}–{Math.min(startIndex + PAGE_SIZE, filtered.length)}</strong> {t("catalog.of")} <strong>{filtered.length}</strong> {t("catalog.products")}</p><div><button type="button" onClick={() => goToPage(currentPage - 1)} disabled={currentPage === 1} aria-label={t("catalog.previous")}><ChevronLeft size={17} /> <span>{t("catalog.previous")}</span></button>{paginationItems(currentPage, totalPages).map((item) => typeof item === "string" ? <span key={item} className="catalog-pagination-gap" aria-hidden="true"><MoreHorizontal size={17} /></span> : <button key={item} type="button" className={item === currentPage ? "is-current" : ""} onClick={() => goToPage(item)} aria-label={`${t("catalog.eyebrow")} ${item}`} aria-current={item === currentPage ? "page" : undefined}>{item}</button>)}<button type="button" onClick={() => goToPage(currentPage + 1)} disabled={currentPage === totalPages} aria-label={t("catalog.next")}><span>{t("catalog.next")}</span> <ChevronRight size={17} /></button></div></nav>}</> : <div className="catalog-empty"><span className="eyebrow muted">{t("catalog.emptyEyebrow")}</span><h2>{t("catalog.emptyTitle")}</h2><p>{t("catalog.emptyCopy")}</p><button className="primary-action" onClick={resetFilters}>{t("catalog.reset")} <ArrowRight size={16} /></button></div>}</div></div></section></main>;
}
