import { ArrowRight, BookOpen, CircleHelp, Search, Ticket } from "lucide-react";
import { useMemo, useState } from "react";
import { useI18n } from "../lib/i18n";
import "./faq-page.css";

const content = {
  pt: {
    eyebrow: "Ajuda Edukangola", title: "Perguntas frequentes", intro: "Respostas claras para começar, estudar, ler, comprar um bilhete e acompanhar a sua área de aluno.", placeholder: "Pesquisar uma dúvida", noResults: "Não encontrámos uma resposta para essa pesquisa.", help: "Ainda precisa de ajuda?", helpCopy: "Explore os cursos publicados ou veja como a plataforma funciona antes de avançar.", courses: "Explorar cursos", how: "Como funciona", sections: [
      ["Cursos e inscrições", [["Como me inscrevo num curso presencial?", "Abra a ficha do curso, confirme a turma e as condições de inscrição. A plataforma mostra o que é pago agora e o que será tratado pelo centro."], ["Como compro um curso em vídeo?", "Os cursos em vídeo são comprados uma única vez quando existe valor. Depois da confirmação do pagamento, ficam disponíveis na área de aprendizagem."]]],
      ["Biblioteca", [["Os livros da Biblioteca são gratuitos?", "Nesta primeira fase, as obras próprias da Edukangola têm leitura gratuita. Cada obra informa claramente as condições de acesso."], ["Posso retomar a leitura onde parei?", "Sim. Ao voltar ao livro, pode continuar na página guardada ou começar novamente. Também pode usar a leitura em voz alta quando o navegador disponibilizar uma voz compatível."]]],
      ["Eventos e bilhetes", [["Como compro um bilhete para um evento?", "Abra o evento, escolha o lote de bilhete disponível e avance para o pagamento. A confirmação fica associada ao seu pedido."], ["Onde encontro os meus bilhetes?", "Os bilhetes confirmados ficam disponíveis na sua área de aluno, separados dos cursos e dos livros guardados."]]],
      ["Conta e segurança", [["Preciso de criar conta para explorar?", "Não. Pode pesquisar cursos, centros, eventos e livros sem conta. A conta é necessária para guardar conteúdos, comprar e acompanhar acessos."], ["O GestorEduka é público?", "Não. O GestorEduka é a área privada de gestão dos centros. Os alunos utilizam a experiência pública da Edukangola."]]],
    ]
  },
  en: { eyebrow: "Edukangola help", title: "Frequently asked questions", intro: "Clear answers to help you start, study, read, buy tickets and manage your student area.", placeholder: "Search a question", noResults: "We could not find an answer for that search.", help: "Still need help?", helpCopy: "Explore published courses or see how the platform works before continuing.", courses: "Explore courses", how: "How it works", sections: [["Courses and enrolment", [["How do I enrol in an in-person course?", "Open the course page, confirm the class and enrolment conditions. The platform shows what is paid now and what the centre will handle."], ["How do I buy a video course?", "Video courses are bought once when a price applies. Once payment is confirmed, they become available in the learning area."]]], ["Library", [["Are Library books free?", "At this first stage, Edukangola's own books are free to read. Each book clearly states its access terms."], ["Can I resume where I stopped?", "Yes. When you return, you can continue at the saved page or restart. You can also use read aloud when the browser provides a compatible voice."]]], ["Events and tickets", [["How do I buy an event ticket?", "Open the event, choose an available ticket tier and continue to payment. Confirmation is linked to your order."], ["Where are my tickets?", "Confirmed tickets are available in your student area, separate from saved courses and books."]]], ["Account and safety", [["Do I need an account to explore?", "No. You can browse courses, centres, events and books without an account. You need one to save content, buy and track access."], ["Is GestorEduka public?", "No. GestorEduka is the private management area for centres. Students use the public Edukangola experience."]]] ] },
  fr: { eyebrow: "Aide Edukangola", title: "Questions fréquentes", intro: "Des réponses claires pour commencer, étudier, lire, acheter un billet et gérer votre espace étudiant.", placeholder: "Rechercher une question", noResults: "Nous n'avons pas trouvé de réponse pour cette recherche.", help: "Besoin d'aide supplémentaire ?", helpCopy: "Explorez les cours publiés ou découvrez le fonctionnement de la plateforme avant de continuer.", courses: "Explorer les cours", how: "Comment ça marche", sections: [["Cours et inscriptions", [["Comment m'inscrire à un cours en présentiel ?", "Ouvrez la fiche du cours, confirmez le groupe et les conditions. La plateforme montre ce qui est payé maintenant et ce que le centre traite."], ["Comment acheter un cours vidéo ?", "Les cours vidéo sont achetés une fois lorsqu'un prix est appliqué. Après confirmation du paiement, ils deviennent disponibles dans l'espace d'apprentissage."]]], ["Bibliothèque", [["Les livres sont-ils gratuits ?", "À cette première étape, les œuvres propres à Edukangola sont gratuites à lire. Chaque livre indique clairement ses conditions d'accès."], ["Puis-je reprendre ma lecture ?", "Oui. Vous pouvez continuer à la page enregistrée ou recommencer. La lecture à voix haute est aussi disponible si le navigateur propose une voix compatible."]]], ["Événements et billets", [["Comment acheter un billet ?", "Ouvrez l'événement, choisissez une catégorie de billet et continuez vers le paiement. La confirmation est liée à votre commande."], ["Où sont mes billets ?", "Les billets confirmés sont disponibles dans votre espace étudiant, séparés des cours et livres enregistrés."]]], ["Compte et sécurité", [["Faut-il un compte pour explorer ?", "Non. Vous pouvez parcourir les cours, centres, événements et livres sans compte. Un compte est nécessaire pour enregistrer, acheter et suivre les accès."], ["GestorEduka est-il public ?", "Non. GestorEduka est l'espace de gestion privé des centres. Les étudiants utilisent l'expérience publique Edukangola."]]] ] },
  zh: { eyebrow: "Edukangola 帮助", title: "常见问题", intro: "帮助您开始学习、阅读、购买门票和管理学习空间的清晰答案。", placeholder: "搜索问题", noResults: "没有找到与该搜索匹配的答案。", help: "还需要帮助？", helpCopy: "继续前可先浏览已发布课程或了解平台使用方式。", courses: "探索课程", how: "使用方式", sections: [["课程与报名", [["如何报名线下课程？", "打开课程详情，确认班级和报名条件。平台会说明当前支付内容以及由中心处理的事项。"], ["如何购买视频课程？", "视频课程在需要付费时一次购买。付款确认后，可在学习空间内使用。"]]], ["图书馆", [["图书馆的书免费吗？", "在第一阶段，Edukangola 自有作品可免费阅读。每本书会明确说明访问条件。"], ["可以从上次阅读位置继续吗？", "可以。返回图书时，可继续已保存页面或重新开始。若浏览器提供兼容语音，也可使用朗读功能。"]]], ["活动与门票", [["如何购买活动门票？", "打开活动，选择可用票种，然后继续付款。确认信息会关联到您的订单。"], ["在哪里查看我的门票？", "确认后的门票会显示在学习空间中，与已保存课程和图书分开。"]]], ["账户与安全", [["探索时需要账户吗？", "不需要。无需账户即可浏览课程、中心、活动和图书。保存内容、购买和跟踪访问时需要账户。"], ["GestorEduka 对外公开吗？", "不公开。GestorEduka 是培训中心的私有管理区。学生使用 Edukangola 公共体验。"]]] ] }
};

export default function FAQPage({ onNavigate }) {
  const { language } = useI18n();
  const copy = content[language] || content.pt;
  const [query, setQuery] = useState("");
  const visibleSections = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase();
    if (!needle) return copy.sections;
    return copy.sections.map(([title, items]) => [title, items.filter(([question, answer]) => `${question} ${answer}`.toLocaleLowerCase().includes(needle))]).filter(([, items]) => items.length);
  }, [copy.sections, query]);
  return <main className="faq-page"><section className="subpage-hero faq-hero"><div className="page-width"><span className="eyebrow"><CircleHelp size={15} /> {copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p><label className="subpage-search faq-search"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.placeholder} aria-label={copy.placeholder} /></label></div></section><section className="page-width faq-content"><div className="faq-list">{visibleSections.map(([title, items]) => <section className="faq-topic" key={title}><h2>{title}</h2>{items.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</section>)}{!visibleSections.length && <p className="faq-empty">{copy.noResults}</p>}</div><aside className="faq-help"><span><Ticket size={19} /></span><h2>{copy.help}</h2><p>{copy.helpCopy}</p><button type="button" onClick={() => onNavigate("/cursos")}>{copy.courses} <ArrowRight size={16} /></button><button type="button" className="faq-secondary" onClick={() => onNavigate("/como-funciona")}>{copy.how}</button></aside></section></main>;
}
