import { ArrowRight, CircleHelp, Search, Ticket } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useI18n } from "../lib/i18n";
import "./faq-page.css";

const labels = {
  pt: { eyebrow: "Ajuda Edukangola", title: "Perguntas frequentes", intro: "Respostas claras para começar, estudar, ler, comprar um bilhete e acompanhar a sua área de aluno.", placeholder: "Pesquisar uma dúvida", loading: "A carregar perguntas frequentes…", empty: "Ainda não existem perguntas publicadas neste idioma.", error: "Não foi possível carregar as perguntas neste momento.", help: "Ainda precisa de ajuda?", helpCopy: "Explore os cursos publicados ou veja como a plataforma funciona antes de avançar.", courses: "Explorar cursos", how: "Como funciona" },
  en: { eyebrow: "Edukangola help", title: "Frequently asked questions", intro: "Clear answers to help you start, study, read, buy tickets and manage your student area.", placeholder: "Search a question", loading: "Loading frequently asked questions…", empty: "There are no published questions in this language yet.", error: "We could not load the questions right now.", help: "Still need help?", helpCopy: "Explore published courses or see how the platform works before continuing.", courses: "Explore courses", how: "How it works" },
  fr: { eyebrow: "Aide Edukangola", title: "Questions fréquentes", intro: "Des réponses claires pour commencer, étudier, lire, acheter un billet et gérer votre espace étudiant.", placeholder: "Rechercher une question", loading: "Chargement des questions fréquentes…", empty: "Aucune question n’est encore publiée dans cette langue.", error: "Impossible de charger les questions pour le moment.", help: "Besoin d’aide supplémentaire ?", helpCopy: "Explorez les cours publiés ou découvrez le fonctionnement de la plateforme avant de continuer.", courses: "Explorer les cours", how: "Comment ça marche" },
  zh: { eyebrow: "Edukangola 帮助", title: "常见问题", intro: "帮助您开始学习、阅读、购买门票和管理学习空间的清晰答案。", placeholder: "搜索问题", loading: "正在加载常见问题…", empty: "此语言暂时没有已发布的问题。", error: "目前无法加载问题。", help: "还需要帮助？", helpCopy: "继续前可先浏览已发布课程或了解平台使用方式。", courses: "探索课程", how: "使用方式" },
};

export default function FAQPage({ onNavigate }) {
  const { language } = useI18n();
  const copy = labels[language] || labels.pt;
  const [query, setQuery] = useState("");
  const [questions, setQuestions] = useState([]);
  const [state, setState] = useState("loading");
  useEffect(() => { let active = true; setState("loading"); fetch(`/api/public/faq/?idioma=${encodeURIComponent(language)}`, { headers: { Accept: "application/json" } }).then((response) => response.ok ? response.json() : Promise.reject(new Error())).then((data) => { if (active) { setQuestions(data.perguntas || []); setState("ready"); } }).catch(() => active && setState("error")); return () => { active = false; }; }, [language]);
  const sections = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return questions.filter((item) => !needle || `${item.categoria} ${item.pergunta} ${item.resposta}`.toLocaleLowerCase().includes(needle)).reduce((groups, item) => ({ ...groups, [item.categoria]: [...(groups[item.categoria] || []), item] }), {}); }, [questions, query]);
  return <main className="faq-page"><section className="subpage-hero faq-hero"><div className="page-width"><span className="eyebrow"><CircleHelp size={15} /> {copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p><label className="subpage-search faq-search"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.placeholder} aria-label={copy.placeholder} /></label></div></section><section className="page-width faq-content"><div className="faq-list">{state === "loading" && <p className="faq-empty">{copy.loading}</p>}{state === "error" && <p className="faq-empty" role="alert">{copy.error}</p>}{state === "ready" && !Object.keys(sections).length && <p className="faq-empty">{copy.empty}</p>}{Object.entries(sections).map(([category, items]) => <section className="faq-topic" key={category}><h2>{category}</h2>{items.map((item) => <details key={item.id}><summary>{item.pergunta}<span aria-hidden="true">+</span></summary><p>{item.resposta}</p></details>)}</section>)}</div><aside className="faq-help"><span><Ticket size={19} /></span><h2>{copy.help}</h2><p>{copy.helpCopy}</p><button type="button" onClick={() => onNavigate("/cursos")}>{copy.courses} <ArrowRight size={16} /></button><button type="button" className="faq-secondary" onClick={() => onNavigate("/como-funciona")}>{copy.how}</button></aside></section></main>;
}
