import { BarChart3, BookOpen, LogIn, Moon, Pencil, Sun, Trash2, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import ManagerClassesPanel from "../components/ManagerClassesPanel";
import ManagerCourseForm from "../components/ManagerCourseForm";
import ManagerEnrollmentsPanel from "../components/ManagerEnrollmentsPanel";
import ManagerGalleryPanel from "../components/ManagerGalleryPanel";
import ManagerInstructorsPanel from "../components/ManagerInstructorsPanel";
import ManagerProfilePanel from "../components/ManagerProfilePanel";
import "./manager-portal-page.css";

const money = new Intl.NumberFormat("pt-AO", { maximumFractionDigits: 0 });

export default function ManagerPortalPage() {
  const [theme, setTheme] = useState(() => localStorage.getItem("gestor-theme") || "light");
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [creating, setCreating] = useState(false); const [editingCourseId, setEditingCourseId] = useState(null);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("gestor-theme", theme); }, [theme]);
  const load = () => fetch("/backend/gestoreduka/api/react/dashboard/", { credentials: "same-origin" }).then(async (response) => { const contentType = response.headers.get("content-type") || ""; if (response.redirected || !contentType.includes("application/json")) throw Object.assign(new Error("A sua sessão de gestor terminou."), { status: 401 }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw Object.assign(new Error(payload.detail || "Não foi possível abrir o GestorEduka."), { status: response.status }); return payload; }).then(setData).catch((reason) => setError(reason));
  useEffect(() => { load(); }, []);
  const changePublication = async (course) => { const token = document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || ""; const response = await fetch(`/backend/gestoreduka/api/react/cursos/${course.id}/publicacao/`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": token }, body: JSON.stringify({ publicado: !course.publicado }) }); if (response.ok) load(); else setError("Não foi possível actualizar a publicação do curso."); };
  const deleteCourse = async (course) => { if (!window.confirm(`Pretende remover definitivamente o curso “${course.titulo}”?`)) return; const token = document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("csrftoken="))?.split("=")[1] || ""; const response = await fetch(`/backend/gestoreduka/api/react/cursos/${course.id}/remover/`, { method: "POST", credentials: "same-origin", headers: { "X-CSRFToken": token } }); if (response.ok) load(); else setError("Não foi possível remover o curso."); };
  if (error && error.status === 401) return <main className="manager-auth"><span className="manager-mark">E</span><h1>GestorEduka</h1><p>Entre com a conta do seu centro para gerir a formação, as inscrições e a presença pública.</p><a href="/backend/gestoreduka/login_gestor/">Entrar no GestorEduka <LogIn size={17} /></a></main>;
  if (error) return <main className="manager-auth"><h1>Não foi possível abrir a gestão.</h1><p>{error.message}</p><button onClick={() => { setError(""); load(); }}>Tentar novamente</button></main>;
  if (!data) return <main className="manager-auth"><span className="manager-mark">E</span><p>A preparar o GestorEduka…</p></main>;
  const cards = [[BookOpen, "Cursos", data.metricas.cursos], [BarChart3, "Publicados", data.metricas.cursos_publicados], [UsersRound, "Inscrições", data.metricas.inscricoes], [BarChart3, "Receita confirmada", `${money.format(data.metricas.receita_confirmada)} Kz`]];
  return <main className="manager-shell"><header><a className="manager-brand" href="/gestoreduka/">Edukangola <b>Gestor</b></a><div><span>{data.centro.nome}</span><button onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label="Alternar tema">{theme === "light" ? <Moon size={18} /> : <Sun size={18} />}</button></div></header><aside><strong>Gestão do centro</strong><a className="active" href="#visao-geral">Visão geral</a><a href="#cursos">Cursos</a><a href="#inscricoes">Inscrições</a><a href="#turmas">Turmas</a><a href="#formadores">Formadores</a><a href="#perfil">Perfil público</a></aside><section className="manager-content" id="visao-geral"><span className="manager-eyebrow">{data.gestor.tipo}</span><h1>Bom trabalho, {data.gestor.nome.split(" ")[0]}.</h1><p>Acompanhe a actividade do seu centro e actue sobre os cursos publicados.</p><div className="manager-metrics">{cards.map(([Icon, label, value]) => <article key={label}><Icon size={19}/><small>{label}</small><strong>{value}</strong></article>)}</div><section id="cursos" className="manager-courses"><div><span className="manager-eyebrow">Catálogo do centro</span><h2>Os seus cursos</h2></div><button className="manager-create-course" onClick={()=>setCreating(true)}>Criar curso</button><div className="manager-course-list">{data.cursos.map((course) => <article key={course.id}><div><strong>{course.titulo}</strong><span>{course.categoria}</span></div><span className={course.publicado ? "published" : "draft"}>{course.publicado ? "Publicado" : "Rascunho"}</span><button onClick={() => changePublication(course)}>{course.publicado ? "Retirar" : "Publicar"}</button><button onClick={() => setEditingCourseId(course.id)} aria-label={`Editar ${course.titulo}`}><Pencil size={16}/></button><button className="manager-course-delete" onClick={() => deleteCourse(course)} aria-label={`Remover ${course.titulo}`}><Trash2 size={16}/></button></article>)}</div></section><ManagerEnrollmentsPanel /><ManagerClassesPanel /><ManagerInstructorsPanel /><ManagerProfilePanel /><ManagerGalleryPanel /></section>{creating && <ManagerCourseForm onClose={()=>setCreating(false)} onCreated={()=>{setCreating(false);load();}}/>}{editingCourseId && <ManagerCourseForm courseId={editingCourseId} onClose={()=>setEditingCourseId(null)} onUpdated={()=>{setEditingCourseId(null);load();}}/>}</main>;
}
