import { useEffect, useMemo, useState } from "react";
import { ArrowRight, MapPin, PackageCheck, Search, ShieldCheck, Store } from "lucide-react";
import "./marketplace-page.css";

const formatarKz = (valor) => new Intl.NumberFormat("pt-PT", { maximumFractionDigits: 0 }).format(Number(valor || 0)).replace(/,/g, " ") + " Kz";

export default function MarketplacePage({ onNavigate }) {
  const [data, setData] = useState({ produtos: [] });
  const [status, setStatus] = useState("loading");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("");
  useEffect(() => { let active = true; fetch("/api/public/mercado/").then((res) => { if (!res.ok) throw new Error(); return res.json(); }).then((payload) => { if (active) { setData(payload); setStatus("ready"); } }).catch(() => active && setStatus("error")); return () => { active = false; }; }, []);
  const categories = useMemo(() => [...new Map(data.produtos.map((item) => [item.categoria_slug, item.categoria])).entries()], [data.produtos]);
  const products = data.produtos.filter((item) => (!category || item.categoria_slug === category) && (!query || `${item.titulo} ${item.categoria} ${item.loja?.nome}`.toLowerCase().includes(query.toLowerCase())));
  return <main className="marketplace-page"><section className="marketplace-hero"><div className="page-width"><span className="eyebrow"><PackageCheck size={15} /> Mercado Edukangola</span><h1>O que precisa para<br /><i>aprender melhor.</i></h1><p>Produtos seleccionados em lojas parceiras, pagos na Edukangola e entregues em Luanda pela nossa operação.</p><div className="marketplace-promises"><span><ShieldCheck size={16} /> Pagamento seguro</span><span><Store size={16} /> Lojas verificadas</span><span><MapPin size={16} /> Entrega em Luanda</span></div></div></section><section className="page-width marketplace-catalog"><div className="marketplace-catalog-header"><div><span className="eyebrow muted">Produtos educativos</span><h2>Encontre os seus essenciais.</h2></div><button className="marketplace-orders-link" onClick={() => onNavigate("/mercado/pedidos")}>Acompanhar pedidos <ArrowRight size={16} /></button></div><div className="marketplace-filterbar"><label><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Procurar computador, livro, mochila..." /></label><div>{[["", "Tudo"], ...categories].map(([value, label]) => <button className={category === value ? "active" : ""} onClick={() => setCategory(value)} key={value || "all"}>{label}</button>)}</div></div>{status === "loading" && <div className="marketplace-state">A preparar o Mercado Edukangola…</div>}{status === "error" && <div className="marketplace-state">Não foi possível carregar produtos agora. Tente novamente mais tarde.</div>}{status === "ready" && !products.length && <div className="marketplace-state"><PackageCheck size={30} /><strong>A vitrina está a ser preparada.</strong><p>Os primeiros produtos de lojas parceiras aparecerão aqui após validação pela equipa Edukangola.</p></div>}{status === "ready" && products.length > 0 && <div className="marketplace-product-grid">{products.map((product) => <button className="marketplace-product-card" onClick={() => onNavigate(product.detalhe_url)} key={product.id}><span className="marketplace-product-photo">{product.imagem_url ? <img src={product.imagem_url} alt="" /> : <PackageCheck size={35} />}{product.loja?.verificada && <em><ShieldCheck size={12} /> Verificada</em>}</span><span className="marketplace-product-info"><small>{product.categoria}</small><strong>{product.titulo}</strong><p>{product.resumo}</p><b>{product.preco_formatado || formatarKz(product.preco)}</b><i><Store size={13} /> {product.loja?.nome}</i></span></button>)}</div>}</section></main>;
}
