import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, MapPin, PackageCheck, ShieldCheck, ShoppingBag, Store } from "lucide-react";
import { authRequest } from "../lib/auth-api";
import "./marketplace-page.css";

export default function MarketProductPage({ slug, student, onNavigate }) {
  const [product, setProduct] = useState(null); const [status, setStatus] = useState("loading"); const [quantity, setQuantity] = useState(1); const [form, setForm] = useState({ telefone: "", endereco_entrega: "", bairro: "", referencia_endereco: "", observacao: "" }); const [feedback, setFeedback] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; fetch(`/api/public/mercado/produtos/${encodeURIComponent(slug)}/`).then((res) => { if (!res.ok) throw new Error(); return res.json(); }).then((payload) => { if (active) { setProduct(payload); setStatus("ready"); } }).catch(() => active && setStatus("error")); return () => { active = false; }; }, [slug]);
  const update = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const order = async (event) => { event.preventDefault(); if (!student) { onNavigate(`/entrar?next=${encodeURIComponent(`/mercado/produtos/${slug}`)}`); return; } setSaving(true); setFeedback(""); try { const result = await authRequest("/api/react/mercado/pedidos/", { produto_id: product.id, quantidade: quantity, ...form }); setFeedback(result.message || "Pedido criado. A equipa confirmará a disponibilidade antes do pagamento."); } catch (error) { setFeedback(error?.data?.message || error.message || "Não foi possível criar o pedido."); } finally { setSaving(false); } };
  if (status === "loading") return <main className="marketplace-state marketplace-page">A preparar o produto…</main>;
  if (status === "error" || !product) return <main className="marketplace-state marketplace-page">Este produto não está disponível neste momento.<button onClick={() => onNavigate("/mercado")}>Voltar ao Mercado</button></main>;
  return <main className="marketplace-page"><div className="page-width market-detail"><button className="market-back" onClick={() => onNavigate("/mercado")}><ArrowLeft size={16} /> Mercado</button><div className="market-detail-layout"><section className="market-detail-media">{product.imagem_url ? <img src={product.imagem_url} alt={product.titulo} /> : <PackageCheck size={65} />}</section><section className="market-detail-copy"><span className="eyebrow muted">{product.categoria}</span><h1>{product.titulo}</h1><p className="market-detail-summary">{product.resumo}</p><strong className="market-detail-price">{product.preco_formatado}</strong><div className="market-detail-facts"><span><Store size={17} /> {product.loja?.nome} <b>{product.loja?.verificada ? "Loja verificada" : ""}</b></span><span><Clock3 size={17} /> Entrega estimada em até {product.prazo_entrega_dias} dias úteis</span><span><ShieldCheck size={17} /> {product.garantia || product.loja?.politica_garantia || "Garantia confirmada no pedido"}</span><span><MapPin size={17} /> Entrega disponível em Luanda</span></div><div className="market-description"><h2>Sobre este produto</h2><p>{product.descricao}</p>{Object.keys(product.especificacoes || {}).length > 0 && <dl>{Object.entries(product.especificacoes).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}</div></section><aside className="market-order-panel"><span><ShoppingBag size={17} /> Pedido com entrega</span><h2>Receba onde estiver.</h2><p>O pagamento é feito na Edukangola. Depois recolhemos o produto na loja e entregamos em Luanda.</p><form onSubmit={order}><label>Quantidade<select value={quantity} onChange={(event) => setQuantity(Number(event.target.value))}>{[1, 2, 3, 4, 5].map((item) => <option value={item} key={item}>{item}</option>)}</select></label>{student && <div className="market-session-note"><CheckCircle2 size={16} /><span><b>Dados da sua conta</b>{student.nome || "Aluno Edukangola"}<small>O nome e e-mail da sessão serão usados no pedido.</small></span></div>}<label>Telefone / WhatsApp<input required value={form.telefone} onChange={update("telefone")} placeholder="+244 923 000 000" autoComplete="tel" /></label><label>Endereço de entrega<input required value={form.endereco_entrega} onChange={update("endereco_entrega")} placeholder="Rua, número ou referência principal" autoComplete="street-address" /></label><label>Bairro<input required value={form.bairro} onChange={update("bairro")} placeholder="Ex.: Talatona" /></label><label>Referência adicional <small>opcional</small><input value={form.referencia_endereco} onChange={update("referencia_endereco")} placeholder="Perto de..." /></label>{feedback && <p className="market-form-feedback">{feedback}</p>}<button className="market-primary" disabled={saving || !product.disponivel}>{saving ? "A criar pedido…" : !student ? "Entrar para pedir" : product.disponivel ? "Pedir e confirmar disponibilidade" : "Indisponível"}</button></form></aside></div></div></main>;
}
