import { useEffect, useState } from "react";
import { ArrowRight, PackageCheck, ReceiptText, Truck } from "lucide-react";
import { authRequest } from "../lib/auth-api";
import "./marketplace-page.css";

export default function MarketOrdersPage({ student, onNavigate }) {
  const [data, setData] = useState({ pedidos: [] }); const [status, setStatus] = useState(student ? "loading" : "signin"); const [feedback, setFeedback] = useState("");
  const load = () => fetch("/api/react/mercado/pedidos/meus/", { credentials: "include" }).then((res) => { if (!res.ok) throw new Error(); return res.json(); }).then((payload) => { setData(payload); setStatus("ready"); }).catch(() => setStatus("error"));
  useEffect(() => { if (!student) return undefined; load(); const retornoPago = new URLSearchParams(window.location.search).get("pagamento") === "sucesso"; if (!retornoPago) return undefined; setFeedback("A confirmar o pagamento…"); const interval = window.setInterval(load, 2500); const timeout = window.setTimeout(() => { window.clearInterval(interval); }, 30000); return () => { window.clearInterval(interval); window.clearTimeout(timeout); }; }, [student]);
  const pay = async (reference) => { setFeedback(""); try { const data = await authRequest(`/api/react/mercado/pedidos/${reference}/pagar/`); if (data.url_pagamento) window.location.assign(data.url_pagamento); else setFeedback("O pagamento ainda não está disponível."); } catch (error) { setFeedback(error?.data?.message || error.message); } };
  if (status === "signin") return <main className="marketplace-state marketplace-page"><ReceiptText size={32} /><strong>Entre para acompanhar pedidos.</strong><button className="market-primary" onClick={() => onNavigate("/entrar?next=/mercado/pedidos")}>Entrar</button></main>;
  return <main className="marketplace-page"><section className="page-width market-orders"><span className="eyebrow"><ReceiptText size={15} /> Mercado Edukangola</span><h1>Os seus pedidos.</h1><p>Veja a confirmação, recolha e entrega dos seus produtos em Luanda.</p>{feedback && <p className="market-form-feedback">{feedback}</p>}{status === "loading" && <div className="marketplace-state">A consultar os seus pedidos…</div>}{status === "error" && <div className="marketplace-state">Não foi possível abrir os pedidos. Tente novamente.</div>}{status === "ready" && !data.pedidos.length && <div className="marketplace-state"><PackageCheck size={32} /><strong>Ainda não fez pedidos no Mercado.</strong><button className="market-primary" onClick={() => onNavigate("/mercado")}>Explorar produtos</button></div>}{status === "ready" && data.pedidos.map((order) => <article className="market-order" key={order.referencia}><header><span><ReceiptText size={17} /> Pedido {order.referencia}</span><b>{order.status_label}</b></header><div className="market-order-body"><div>{order.itens.map((item) => <button className="market-order-item" key={`${order.referencia}-${item.titulo}`} onClick={() => onNavigate(item.produto_url)}>{item.imagem_url ? <img src={item.imagem_url} alt="" /> : <PackageCheck size={18} />}<span><strong>{item.titulo}</strong><small>{item.quantidade} unidade(s)</small></span></button>)}</div><aside><strong>{order.total_formatado}</strong>{order.codigo_entrega && <small><Truck size={14} /> Código de entrega: {order.codigo_entrega}</small>}{order.pode_pagar ? <button className="market-primary" onClick={() => pay(order.referencia)}>Ir para pagamento <ArrowRight size={16} /></button> : <small>Pagamento: {order.referencia_pagamento || "a confirmar"}</small>}</aside></div></article>)}</section></main>;
}
