import { CalendarDays, CheckCircle2, ChevronRight, Clipboard, MapPin, ReceiptText, TicketCheck } from "lucide-react";
import { useEffect, useState } from "react";
import "./my-tickets-page.css";

function copyCode(code) { return navigator.clipboard?.writeText(code); }

export default function MyTicketsPage({ onNavigate }) {
  const [state, setState] = useState("loading");
  const [tickets, setTickets] = useState([]);
  const [copied, setCopied] = useState("");
  useEffect(() => { let active = true; fetch('/api/public/eventos/meus-bilhetes/', { credentials: 'include', headers: { Accept: 'application/json' } }).then((response) => response.ok ? response.json() : Promise.reject(new Error())).then((data) => { if (active) { setTickets(data.bilhetes || []); setState('ready'); } }).catch(() => active && setState('error')); return () => { active = false; }; }, []);
  const handleCopy = (code) => { copyCode(code)?.then(() => { setCopied(code); window.setTimeout(() => setCopied(''), 1800); }); };
  return <main className="my-tickets-page"><section className="subpage-hero tickets-hero"><div className="page-width"><span className="eyebrow"><TicketCheck size={15} /> Bilhetes de eventos</span><h1>Os meus bilhetes</h1><p>Os seus bilhetes confirmados ficam reunidos aqui. Apresente o código de validação na entrada quando o organizador o solicitar.</p></div></section><section className="page-width tickets-content">{state === 'loading' && <p className="tickets-message">A carregar os seus bilhetes…</p>}{state === 'error' && <div className="tickets-empty"><ReceiptText size={28} /><h2>Não foi possível abrir os seus bilhetes.</h2><p>Actualize a página ou volte a tentar dentro de alguns instantes.</p></div>}{state === 'ready' && !tickets.length && <div className="tickets-empty"><TicketCheck size={30} /><h2>Ainda não tem bilhetes confirmados.</h2><p>Quando concluir a compra de um evento, o seu bilhete aparecerá aqui.</p><button type="button" className="primary-action" onClick={() => onNavigate('/eventos')}>Explorar eventos <ChevronRight size={17} /></button></div>}{state === 'ready' && tickets.length > 0 && <div className="tickets-list">{tickets.map((ticket) => <article className={`personal-ticket ${ticket.status.toLowerCase()}`} key={ticket.id} style={{ '--ticket-primary': ticket.lote.cor_primaria || '#0F6B8A', '--ticket-soft': ticket.lote.cor_secundaria || '#EAF8FA' }}><div className="ticket-main"><div className="ticket-art">{ticket.evento.imagem_url ? <img src={ticket.evento.imagem_url} alt="" /> : <TicketCheck size={40} />}<span>{ticket.evento.modalidade}</span></div><div className="ticket-copy"><div className="ticket-status"><CheckCircle2 size={15} /> {ticket.status_label}</div><p className="ticket-organiser">{ticket.evento.organizador}</p><h2>{ticket.evento.titulo}</h2><p className="ticket-lot">{ticket.lote.nome}{ticket.lote.texto_ingresso ? ` · ${ticket.lote.texto_ingresso}` : ''}</p><div className="ticket-meta"><span><CalendarDays size={15} /> {ticket.evento.data_inicio_formatada}</span>{ticket.evento.local && <span><MapPin size={15} /> {ticket.evento.local}{ticket.evento.cidade ? ` · ${ticket.evento.cidade}` : ''}</span>}</div><button className="ticket-detail-link" type="button" onClick={() => onNavigate(ticket.detalhe_url)}>Ver evento <ChevronRight size={15} /></button></div></div><aside className="ticket-validation"><span className="ticket-label">Código de validação</span><strong>{ticket.codigo.slice(0, 8).toUpperCase()}</strong><small>{ticket.codigo}</small><button type="button" onClick={() => handleCopy(ticket.codigo)}><Clipboard size={14} /> {copied === ticket.codigo ? 'Código copiado' : 'Copiar código'}</button><p>Pedido {ticket.referencia_pedido}</p></aside></article>)}</div>}</section></main>;
}
