import { Database, FileText, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { useI18n } from "../lib/i18n";
import "./privacy-policy-page.css";

const content = {
  pt: { eyebrow: "Transparência e segurança", title: "Política de privacidade", intro: "Esta página explica, de forma simples, como a Edukangola trata os dados necessários para disponibilizar cursos, Biblioteca, eventos e a área de aluno.", updated: "Última actualização: 16 de Agosto de 2026", email: "privacidade@edukangola.ao", sections: [[ShieldCheck, "Dados que tratamos", "Podemos tratar dados de identificação e contacto, dados de acesso, informações necessárias para inscrições, compras e conteúdos guardados. Pedimos apenas os dados necessários para cada funcionalidade."], [Database, "Como utilizamos os dados", "Utilizamos os dados para criar e proteger a sua conta, processar inscrições e pedidos, disponibilizar cursos e livros, confirmar pagamentos e melhorar a experiência de utilização."], [LockKeyhole, "Partilha e segurança", "Os dados não são vendidos. Podem ser partilhados apenas com centros de formação, organizadores de eventos e prestadores necessários para concluir um serviço solicitado por si, sempre no contexto dessa operação."], [FileText, "Os seus controlos", "Pode actualizar os dados da sua conta e pedir esclarecimentos sobre o tratamento dos seus dados. Algumas informações precisam de ser mantidas quando forem necessárias para segurança, pagamentos ou obrigações aplicáveis."]], contact: "Questões sobre privacidade" },
  en: { eyebrow: "Transparency and security", title: "Privacy policy", intro: "This page explains, in clear terms, how Edukangola handles the data needed to offer courses, the Library, events and the student area.", updated: "Last updated: 16 August 2026", email: "privacidade@edukangola.ao", sections: [[ShieldCheck, "Data we handle", "We may handle identification and contact data, access data and information needed for enrolment, purchases and saved content. We request only what each feature needs."], [Database, "How we use data", "We use data to create and protect your account, process enrolments and orders, provide courses and books, confirm payments and improve the experience."], [LockKeyhole, "Sharing and security", "Data is not sold. It may only be shared with training centres, event organisers and providers necessary to complete a service you requested, within that operation."], [FileText, "Your controls", "You can update your account data and request information about how it is handled. Some records may be retained where necessary for security, payments or applicable obligations."]], contact: "Privacy questions" },
  fr: { eyebrow: "Transparence et sécurité", title: "Politique de confidentialité", intro: "Cette page explique clairement comment Edukangola traite les données nécessaires aux cours, à la Bibliothèque, aux événements et à l'espace étudiant.", updated: "Dernière mise à jour : 16 août 2026", email: "privacidade@edukangola.ao", sections: [[ShieldCheck, "Données traitées", "Nous pouvons traiter les données d'identification, de contact, d'accès et les informations nécessaires aux inscriptions, achats et contenus enregistrés. Nous ne demandons que ce dont chaque fonctionnalité a besoin."], [Database, "Utilisation des données", "Nous utilisons les données pour créer et protéger votre compte, traiter les inscriptions et commandes, donner accès aux cours et livres, confirmer les paiements et améliorer l'expérience."], [LockKeyhole, "Partage et sécurité", "Les données ne sont pas vendues. Elles peuvent être partagées uniquement avec les centres, organisateurs et prestataires nécessaires au service demandé, dans le cadre de cette opération."], [FileText, "Vos contrôles", "Vous pouvez mettre à jour les données de votre compte et demander des informations sur leur traitement. Certains dossiers peuvent être conservés pour la sécurité, les paiements ou les obligations applicables."]], contact: "Questions sur la confidentialité" },
  zh: { eyebrow: "透明与安全", title: "隐私政策", intro: "本页面以清晰方式说明 Edukangola 如何处理提供课程、图书馆、活动和学习空间所需的数据。", updated: "最后更新：2026年8月16日", email: "privacidade@edukangola.ao", sections: [[ShieldCheck, "我们处理的数据", "我们可能处理身份、联系方式、访问数据，以及报名、购买和保存内容所需的信息。每项功能只请求必要的数据。"], [Database, "数据如何使用", "我们使用数据来创建和保护账户、处理报名和订单、提供课程和图书、确认付款并改善体验。"], [LockKeyhole, "共享与安全", "我们不会出售数据。仅会在完成您请求的服务所需范围内，与培训中心、活动组织者和服务商共享数据。"], [FileText, "您的控制权", "您可以更新账户数据并询问数据处理方式。出于安全、付款或适用义务的需要，部分记录可能需要保留。"]], contact: "隐私问题" }
};

export default function PrivacyPolicyPage() {
  const { language } = useI18n();
  const copy = content[language] || content.pt;
  return <main className="privacy-page"><section className="subpage-hero privacy-hero"><div className="page-width"><span className="eyebrow"><ShieldCheck size={15} /> {copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p><small>{copy.updated}</small></div></section><section className="page-width privacy-content"><div className="privacy-intro"><h2>Edu<span>kangola</span></h2><p>{copy.intro}</p></div><div className="privacy-grid">{copy.sections.map(([Icon, title, text]) => <article key={title}><span><Icon size={20} /></span><h2>{title}</h2><p>{text}</p></article>)}</div><section className="privacy-contact"><Mail size={20} /><div><strong>{copy.contact}</strong><p>Contacte-nos em <a href={`mailto:${copy.email}`}>{copy.email}</a>.</p></div></section></section></main>;
}
