import { Building2, CheckCircle2, GraduationCap, MapPin, Search, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import "./opportunities-pages.css";

const api = (path) => fetch(`/backend${path}`, { credentials: "include", cache: "no-store" }).then(async (response) => { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "Não foi possível carregar esta informação."); return data; });

function SchoolCard({ school, onNavigate }) { return <article className="opportunity-card"><div className="opportunity-card-logo">{school.logo_url ? <img src={school.logo_url} alt="" /> : <Building2 size={24} />}</div><div className="opportunity-card-main"><div className="opportunity-meta"><span>{school.tipo_rede}</span>{school.verificada && <span><ShieldCheck size={14}/> Verificada</span>}</div><h2>{school.nome}</h2><p><MapPin size={15}/>{school.municipio}, {school.provincia}</p><small>{school.cursos.length} curso(s) · {school.inscricoes_abertas ? "Inscrições abertas" : "Consulte disponibilidade"}</small></div><button onClick={() => onNavigate(school.detalhe_url)}>Ver escola</button></article>; }

export function SchoolsPage({ onNavigate }) { const [data, setData] = useState(null); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [province, setProvince] = useState(""); const load = () => { const search = new URLSearchParams(); if (query) search.set("q", query); if (province) search.set("provincia", province); api(`/api/react/escolas/?${search}`).then(setData).catch((reason) => setError(reason.message)); }; useEffect(() => { load(); }, [province]); if (error) return <main className="opportunities page-width"><section className="opportunity-feedback"><h1>Escolas</h1><p>{error}</p><button onClick={load}>Tentar novamente</button></section></main>; if (!data) return <main className="opportunities page-width"><p>A carregar escolas…</p></main>; return <main className="opportunities page-width"><section className="opportunity-hero"><span><GraduationCap size={18}/> Ensino e futuro</span><h1>Encontre a escola certa para o próximo passo.</h1><p>Compare opções de ensino geral e técnico, cursos, localização e condições de inscrição.</p><form onSubmit={(event) => { event.preventDefault(); load(); }}><label><Search size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, curso, município ou província" /></label><select value={province} onChange={(event) => setProvince(event.target.value)}><option value="">Todas as províncias</option>{data.provincias.map((item) => <option key={item}>{item}</option>)}</select><button>Pesquisar</button></form></section><section className="opportunity-list"><div className="opportunity-heading"><div><span>Directório de escolas</span><h1>{data.escolas.length} escola(s) encontradas</h1></div></div>{data.escolas.length ? data.escolas.map((school) => <SchoolCard key={school.id} school={school} onNavigate={onNavigate} />) : <p className="opportunity-empty">Ainda não encontrámos escolas com estes critérios.</p>}</section></main>; }

export function SchoolProfilePage({ schoolId, onNavigate }) { const [school, setSchool] = useState(null); const [error, setError] = useState(""); useEffect(() => { api(`/api/react/escolas/${schoolId}/`).then((data) => setSchool(data.escola)).catch((reason) => setError(reason.message)); }, [schoolId]); if (error) return <main className="opportunities page-width"><section className="opportunity-feedback"><h1>Escola</h1><p>{error}</p><button onClick={() => onNavigate("/escolas")}>Ver escolas</button></section></main>; if (!school) return <main className="opportunities page-width"><p>A carregar escola…</p></main>; return <main className="opportunities page-width"><section className="profile-hero">{school.banner_url && <img src={school.banner_url} alt="" />}<div className="profile-hero-overlay"><div className="opportunity-card-logo">{school.logo_url ? <img src={school.logo_url} alt="" /> : <Building2 />}</div><span>{school.tipo_rede}{school.verificada ? " · Escola verificada" : ""}</span><h1>{school.nome}</h1><p><MapPin size={16}/>{school.endereco || `${school.municipio}, ${school.provincia}`}</p></div></section><section className="profile-layout"><div className="profile-main"><article className="profile-section"><h2>Sobre a escola</h2><p>{school.descricao || "Esta escola ainda não publicou uma apresentação detalhada."}</p>{school.missao && <><h3>Missão</h3><p>{school.missao}</p></>}{school.visao && <><h3>Visão</h3><p>{school.visao}</p></>}</article><article className="profile-section"><h2>Cursos e programas</h2><div className="school-courses">{school.cursos.map((course) => <div key={course.id}><h3>{course.nome}</h3><p>{course.descricao || course.classes}</p><small>{course.classes} · {course.duracao_anos} ano(s){course.periodos ? ` · ${course.periodos}` : ""}</small><strong>{course.mensalidade ? `${course.mensalidade.toLocaleString("pt-AO")} Kz/mês` : "Consulte condições"}</strong></div>) || <p>A escola ainda não publicou cursos.</p>}</div></article>{school.infraestruturas?.length > 0 && <article className="profile-section"><h2>Infraestruturas</h2><div className="tag-list">{school.infraestruturas.map((item) => <span key={item}>{item}</span>)}</div></article>}</div><aside className="profile-aside"><span>{school.inscricoes_abertas ? "Inscrições abertas" : "Informação de inscrição"}</span><h2>Quer estudar aqui?</h2><p>{school.requisitos_inscricao || "Contacte a escola para confirmar requisitos, vagas e datas de inscrição."}</p>{school.prazo_inscricoes && <p><b>Prazo:</b> {new Date(school.prazo_inscricoes).toLocaleDateString("pt-AO")}</p>}<a href={school.whatsapp ? `https://wa.me/${school.whatsapp.replace(/\D/g, "")}` : `mailto:${school.email}`}>{school.whatsapp ? "Falar no WhatsApp" : "Contactar a escola"}</a></aside></section></main>; }
