import { useEffect, useState } from "react";
import { ArrowLeft, Check, CircleAlert, SlidersHorizontal } from "lucide-react";
import { backendUrl } from "../lib/backend-url";
import WebPushPreferenceCard from "../components/WebPushPreferenceCard";
import "./student-preferences-page.css";

const INITIAL = { categoria_ids: [], modalidades: [], objectivos: [], disponibilidades: [], provincias: [], faixa_preco: "QUALQUER", quer_certificado: null };

function csrfToken() {
  return document.cookie.split(";").map((item) => item.trim()).find((item) => item.startsWith("csrftoken="))?.split("=").slice(1).join("=") || "";
}

function ToggleGroup({ title, options, selected, onChange, multiple = true }) {
  const toggle = (value) => {
    if (multiple) onChange(selected.includes(value) ? selected.filter((item) => item !== value) : [...selected, value]);
    else onChange([value]);
  };
  return <fieldset className="preferences-fieldset"><legend>{title}</legend><div className="preference-options">{options.map((option) => { const value = option.value ?? option.id ?? option; const label = option.label ?? option.nome ?? option; const active = selected.includes(value); return <button key={value} type="button" className={`preference-chip${active ? " is-active" : ""}`} onClick={() => toggle(value)} aria-pressed={active}>{active && <Check size={14} />}{label}</button>; })}</div></fieldset>;
}

export default function StudentPreferencesPage({ onNavigate }) {
  const [state, setState] = useState({ loading: true, saving: false, error: "", message: "", categorias: [], opcoes: {}, preferencias: INITIAL });
  useEffect(() => {
    let active = true;
    fetch(backendUrl("/auth/api/react/aluno/preferencias/"), { credentials: "same-origin", headers: { Accept: "application/json" } }).then(async (response) => { const data = await response.json().catch(() => ({})); if (response.status === 401) throw new Error("login"); if (!response.ok) throw new Error(data.detail || "Não foi possível carregar as preferências."); return data; }).then((data) => active && setState((current) => ({ ...current, loading: false, categorias: data.categorias || [], opcoes: data.opcoes || {}, preferencias: { ...INITIAL, ...(data.preferencias || {}) } }))).catch((error) => active && setState((current) => ({ ...current, loading: false, error: error.message }))); return () => { active = false; };
  }, []);
  const setPreference = (field, value) => setState((current) => ({ ...current, preferencias: { ...current.preferencias, [field]: value }, message: "", error: "" }));
  const save = async (event) => { event.preventDefault(); setState((current) => ({ ...current, saving: true, message: "", error: "" })); try { const response = await fetch(backendUrl("/auth/api/react/aluno/preferencias/actualizar/"), { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", Accept: "application/json", "X-CSRFToken": csrfToken() }, body: JSON.stringify(state.preferencias) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "Não foi possível guardar as preferências."); setState((current) => ({ ...current, saving: false, message: "Preferências guardadas. As recomendações serão actualizadas." })); } catch (error) { setState((current) => ({ ...current, saving: false, error: error.message })); } };
  if (state.loading) return <main className="preferences-page"><div className="page-width preferences-loading">A carregar as suas preferências…</div></main>;
  if (state.error === "login") return <main className="preferences-page"><section className="page-width preferences-gate"><h1>Entre para definir as suas preferências.</h1><button className="primary-action" onClick={() => onNavigate("/entrar?next=/aluno/preferencias")}>Entrar</button></section></main>;
  if (state.error && !state.categorias.length) return <main className="preferences-page"><section className="page-width preferences-gate"><CircleAlert size={24} /><h1>Não foi possível carregar as preferências.</h1><p>{state.error}</p><button className="primary-action" onClick={() => window.location.reload()}>Tentar novamente</button></section></main>;
  return <main className="preferences-page"><section className="preferences-hero"><div className="page-width"><button className="preferences-back" type="button" onClick={() => onNavigate("/aluno")}><ArrowLeft size={17} /> Voltar à área do aluno</button><span className="eyebrow"><SlidersHorizontal size={15} /> Personalização</span><h1>Escolha o que quer aprender.</h1><p>Estas escolhas ajudam-nos a mostrar cursos mais relevantes. Pode alterá-las quando quiser.</p></div></section><form className="page-width preferences-form" onSubmit={save}><section className="preferences-card"><ToggleGroup title="Áreas de interesse" options={state.categorias} selected={state.preferencias.categoria_ids} onChange={(value) => setPreference("categoria_ids", value)} /><ToggleGroup title="Como prefere aprender?" options={state.opcoes.modalidades || []} selected={state.preferencias.modalidades} onChange={(value) => setPreference("modalidades", value)} /><ToggleGroup title="O que quer alcançar?" options={state.opcoes.objectivos || []} selected={state.preferencias.objectivos} onChange={(value) => setPreference("objectivos", value)} /><ToggleGroup title="Quando tem disponibilidade?" options={state.opcoes.disponibilidades || []} selected={state.preferencias.disponibilidades} onChange={(value) => setPreference("disponibilidades", value)} /><ToggleGroup title="Onde prefere estudar?" options={state.opcoes.provincias || []} selected={state.preferencias.provincias} onChange={(value) => setPreference("provincias", value)} /><ToggleGroup title="Faixa de preço" multiple={false} options={[{ value: "QUALQUER", label: "Qualquer valor" }, { value: "GRATUITOS", label: "Apenas gratuitos" }, { value: "ATE_25000", label: "Até 25 000 Kz" }, { value: "ATE_50000", label: "Até 50 000 Kz" }]} selected={[state.preferencias.faixa_preco]} onChange={(value) => setPreference("faixa_preco", value[0])} /><ToggleGroup title="Certificado" multiple={false} options={[{ value: "yes", label: "Quero certificado" }, { value: "no", label: "Não é essencial" }]} selected={state.preferencias.quer_certificado === true ? ["yes"] : state.preferencias.quer_certificado === false ? ["no"] : []} onChange={(value) => setPreference("quer_certificado", value[0] === "yes" ? true : value[0] === "no" ? false : null)} /></section><WebPushPreferenceCard />{state.error && <p className="preferences-feedback error" role="alert">{state.error}</p>}{state.message && <p className="preferences-feedback success" role="status">{state.message}</p>}<div className="preferences-actions"><button className="primary-action" type="submit" disabled={state.saving}>{state.saving ? "A guardar…" : "Guardar preferências"}</button><button className="preferences-skip" type="button" onClick={() => onNavigate("/aluno")}>Agora não</button></div></form></main>;
}
