import { ArrowRight, BookOpen, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Layers3, PlayCircle, Sparkles, UsersRound } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import "./video-courses-page.css";
import "./video-editorial-feature.css";
import "./video-row-controls.css";

function VideoCard({ course, onNavigate }) {
  return <article className="video-show-card"><button type="button" onClick={() => onNavigate(`/video-cursos/${course.video_slug}`)}><div className="video-show-art">{course.imagem_url && <img src={course.imagem_url} alt="" />}<div className="video-show-overlay"><span><PlayCircle size={17} /> Curso em vídeo</span>{course.is_original_edukangola && <small>Original Edukangola</small>}</div><i aria-hidden="true"><PlayCircle size={25} /></i></div><div className="video-show-copy"><div className="video-show-meta"><span>{course.categoria}</span><span>{course.is_gratuito ? "Acesso gratuito" : course.pagamento?.agora}</span></div><h3>{course.titulo}</h3><p>{course.instrutor || course.centro}</p><div className="video-show-stats"><span><Layers3 size={14} /> {course.total_aulas || 0} aulas</span><span><Clock3 size={14} /> {course.duracao_total || "Ao seu ritmo"}</span></div><strong>Ver programa <ArrowRight size={14} /></strong></div></button></article>;
}

function VideoEditorialFeature({ categories, onNavigate }) {
  const [activeCategory, setActiveCategory] = useState("Todos");
  const currentCategory = categories.find(([category]) => category === activeCategory) || categories[0] || ["", []];
  const courses = currentCategory[1].slice(0, 3);
  if (!courses.length) return null;
  return <section className="video-editorial-feature" aria-labelledby="video-editorial-feature-title"><aside className="video-editorial-intro"><span className="eyebrow"><PlayCircle size={15} /> Biblioteca de cursos em vídeo</span><h2 id="video-editorial-feature-title">Escolha o seu próximo curso.</h2><p>Programas com aulas para assistir ao seu ritmo.</p><button type="button" onClick={() => document.getElementById("colecoes-video")?.scrollIntoView({ behavior: "smooth" })}>Ver todos <ArrowRight size={16} /></button></aside><div className="video-editorial-content"><div className="video-editorial-tabs" role="tablist" aria-label="Áreas dos cursos em vídeo">{categories.slice(0, 6).map(([category]) => <button key={category} type="button" role="tab" aria-selected={currentCategory[0] === category} className={currentCategory[0] === category ? "is-active" : ""} onClick={() => setActiveCategory(category)}>{category}</button>)}</div><div className="video-editorial-cards">{courses.map((course) => <button type="button" className="video-editorial-card" key={course.id} onClick={() => onNavigate(`/video-cursos/${course.video_slug}`)}><div className="video-editorial-art">{course.imagem_url && <img src={course.imagem_url} alt="" />}<span><PlayCircle size={17} /> Ver programa</span></div><div className="video-editorial-copy"><small>{course.is_original_edukangola ? "Original Edukangola" : course.centro || "Edukangola"}</small><h3>{course.titulo}</h3><p><span><Layers3 size={13} /> {course.total_aulas || 0} aulas</span><span><Clock3 size={13} /> {course.duracao_total || "Ao seu ritmo"}</span></p></div></button>)}</div></div></section>;
}

function VideoRow({ title, eyebrow, courses, onNavigate, featured = false }) {
  const railRef = useRef(null);
  if (!courses.length) return null;
  const scrollRail = (direction) => railRef.current?.scrollBy({ left: direction * Math.max(260, railRef.current.clientWidth * .78), behavior: "smooth" });
  return <section className={`video-row ${featured ? "is-featured" : ""}`}><div className="video-row-heading"><div><span className="eyebrow muted">{eyebrow}</span><h2>{title}</h2></div><div className="video-row-tools"><span>{courses.length} {courses.length === 1 ? "curso" : "cursos"}</span>{courses.length > 1 && <div className="video-rail-controls" aria-label={`Navegar cursos em ${title}`}><button type="button" onClick={() => scrollRail(-1)} aria-label="Ver cursos anteriores"><ChevronLeft size={18} /></button><button type="button" onClick={() => scrollRail(1)} aria-label="Ver próximos cursos"><ChevronRight size={18} /></button></div>}</div></div><div ref={railRef} className="video-rail" aria-label={title}>{courses.map((course) => <VideoCard key={course.id} course={course} onNavigate={onNavigate} />)}</div></section>;
}

export default function VideoCoursesPage({ data, loading, onNavigate }) {
  const courses = data?.video_cursos || [];
  const featured = courses.filter((course) => course.destaque);
  const originals = courses.filter((course) => course.is_original_edukangola);
  const withMentor = courses.filter((course) => course.tem_turmas);
  const freeCourses = courses.filter((course) => course.is_gratuito);
  const compactCourses = courses.filter((course) => (course.total_aulas || 0) > 0 && (course.total_aulas || 0) <= 8);
  const recent = [...courses].sort((a, b) => new Date(b.data_publicacao) - new Date(a.data_publicacao));
  const categories = useMemo(() => Object.entries(courses.reduce((groups, course) => ({ ...groups, [course.categoria || "Outras áreas"]: [...(groups[course.categoria || "Outras áreas"] || []), course] }), {})).filter(([, items]) => items.length > 0), [courses]);
  const editorialCategories = useMemo(() => [["Todos", courses], ...categories], [categories, courses]);
  const wallCourses = useMemo(() => courses.length ? Array.from({ length: Math.max(48, courses.length * 18) }, (_, index) => courses[index % courses.length]) : [], [courses]);
  if (loading) return <main className="video-hub"><div className="page-width video-hub-loading">A preparar os cursos em vídeo…</div></main>;
  return <main className="video-hub"><section className="video-hub-hero video-hub-landing"><div className="video-mosaic" aria-hidden="true">{wallCourses.map((course, index) => <img key={`${course.id}-${index}`} src={course.imagem_url} alt="" />)}</div><div className="video-hub-veil" /><div className="video-hub-landing-copy"><span className="eyebrow"><Sparkles size={15} /> Edukangola vídeo</span><h1>Aprenda no seu ritmo.<br />Avance no seu futuro.</h1><p>Cursos em vídeo para desenvolver competências, rever quando quiser e continuar de onde parou.</p><div className="video-landing-actions"><button className="video-landing-primary" onClick={() => document.getElementById("catalogo-video")?.scrollIntoView({ behavior: "smooth" })}>Explorar cursos <ArrowRight size={18} /></button><button className="video-landing-secondary" onClick={() => onNavigate("/cursos")}>Ver cursos presenciais</button></div></div></section><section id="catalogo-video" className="page-width video-hub-content">{courses.length ? <><section className="video-value-strip"><div><PlayCircle size={19} /><strong>Aceda quando quiser</strong><span>Aprenda sem depender de uma turma.</span></div><div><CheckCircle2 size={19} /><strong>Retome o seu progresso</strong><span>Continue exactamente na aula onde parou.</span></div><div><UsersRound size={19} /><strong>Aprenda com especialistas</strong><span>Conteúdo criado por centros e formadores.</span></div></section><VideoEditorialFeature categories={editorialCategories} onNavigate={onNavigate} /><div id="colecoes-video"><VideoRow eyebrow="Comece aqui" title="Em destaque para si." courses={featured.length ? featured : recent} onNavigate={onNavigate} featured /><VideoRow eyebrow="Séries Edukangola" title="Originais para construir competências." courses={originals} onNavigate={onNavigate} /><VideoRow eyebrow="Curadoria" title="Cursos com acompanhamento disponível." courses={withMentor} onNavigate={onNavigate} /><VideoRow eyebrow="Estude esta semana" title="Cursos compactos para avançar agora." courses={compactCourses} onNavigate={onNavigate} /><VideoRow eyebrow="Comece sem pagar" title="Acesso gratuito para explorar." courses={freeCourses} onNavigate={onNavigate} /><VideoRow eyebrow="Recém-adicionados" title="Novidades na biblioteca." courses={recent} onNavigate={onNavigate} />{categories.map(([category, items]) => <VideoRow key={category} eyebrow={`Área · ${category}`} title={`Aprender ${category}.`} courses={items} onNavigate={onNavigate} />)}</div></> : <div className="video-hub-empty"><BookOpen size={33} /><h2>Os cursos em vídeo chegam em breve.</h2><p>Enquanto preparamos esta biblioteca, explore as formações presenciais publicadas pelos centros.</p><button className="primary-action" onClick={() => onNavigate("/cursos")}>Cursos presenciais <ArrowRight size={16} /></button></div>}</section></main>;
}
