# Generated by Django 5.2.4 on 2026-05-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('icone', models.CharField(blank=True, help_text='Ex: feather-book', max_length=50, verbose_name='Ícone (FontAwesome/Feather)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Escola',
                'verbose_name_plural': 'Categorias de Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('tipo_rede', models.CharField(choices=[('PUBLICA', 'Pública / Estatal'), ('PRIVADA', 'Privada'), ('COMPARTICIPADA', 'Comparticipada')], default='PUBLICA', max_length=20, verbose_name='Tipo de Rede')),
                ('provincia', models.CharField(max_length=100, verbose_name='Província')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço Completo')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('mensalidade_base', models.DecimalField(decimal_places=2, default=0, help_text='0 para escolas públicas', max_digits=12, verbose_name='Mensalidade Base (Kz)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='escolas', to='escolas.categoriaescola')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='CursoEnsinoMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Curso')),
                ('duracao_anos', models.PositiveIntegerField(default=3, verbose_name='Duração (Anos)')),
                ('periodos', models.CharField(blank=True, max_length=100, verbose_name='Períodos (Manhã, Tarde, Noite)')),
                ('vagas_anuais', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vagas Anuais Estimadas')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Curso do Ensino Médio',
                'verbose_name_plural': 'Cursos do Ensino Médio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='escolas/galeria/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria (Escola)',
                'verbose_name_plural': 'Galeria de Imagens (Escola)',
            },
        ),
        migrations.CreateModel(
            name='PerfilEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escolas/logos/', verbose_name='Logotipo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='escolas/banners/', verbose_name='Banner/Capa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / História')),
                ('missao', models.TextField(blank=True, verbose_name='Missão')),
                ('visao', models.TextField(blank=True, verbose_name='Visão')),
                ('ano_fundacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fundação')),
                ('diretor', models.CharField(blank=True, max_length=150, verbose_name='Diretor(a)')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('verificada', models.BooleanField(default=False, verbose_name='Escola Verificada')),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='escolas.escola')),
            ],
        ),
    ]
