# Generated by Django 5.2.4 on 2026-05-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_areaformacao_cursoensinomedio_area_formacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Infraestrutura')),
                ('icone', models.CharField(default='feather-check-circle', help_text='Ex: feather-monitor, feather-book', max_length=50, verbose_name='Ícone (Feather)')),
            ],
            options={
                'verbose_name': 'Infraestrutura',
                'verbose_name_plural': 'Infraestruturas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cursoensinomedio',
            name='classes_lecionadas',
            field=models.CharField(default='10ª à 12ª Classe', help_text='Ex: 10ª à 12ª Classe, 10ª à 13ª Classe', max_length=100, verbose_name='Classes Lecionadas'),
        ),
        migrations.AddField(
            model_name='cursoensinomedio',
            name='disciplinas_exame',
            field=models.CharField(blank=True, help_text='Ex: Matemática e Física', max_length=255, verbose_name='Disciplinas do Exame'),
        ),
        migrations.AddField(
            model_name='cursoensinomedio',
            name='exige_exame',
            field=models.BooleanField(default=False, verbose_name='Exige Exame de Admissão?'),
        ),
        migrations.AddField(
            model_name='perfilescola',
            name='infraestruturas',
            field=models.ManyToManyField(blank=True, related_name='escolas_com_infraestrutura', to='escolas.infraestrutura'),
        ),
        migrations.CreateModel(
            name='ParceriaEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=150, verbose_name='Nome da Empresa/Parceiro')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escolas/parcerias/', verbose_name='Logotipo do Parceiro')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Parceria (Ex: Estágios para Mecânica)')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Parceria de Estágio',
                'verbose_name_plural': 'Parcerias de Estágios',
                'ordering': ['nome_empresa'],
            },
        ),
    ]
