# Generated by Django 5.2.4 on 2026-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_infraestrutura_cursoensinomedio_classes_lecionadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoensinomedio',
            name='mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se vazio, usa a mensalidade base da escola.', max_digits=12, null=True, verbose_name='Mensalidade Específica (Kz)'),
        ),
        migrations.AddField(
            model_name='cursoensinomedio',
            name='taxa_inscricao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Taxa de Inscrição/Matrícula (Kz)'),
        ),
    ]
