# Generated by Django 5.2.4 on 2026-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_cursoensinomedio_mensalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaescola',
            name='categoria',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('SALAS', 'Salas de Aula'), ('LABS', 'Laboratórios e Infraestruturas'), ('EVENTOS', 'Eventos'), ('DESPORTO', 'Desporto')], default='GERAL', max_length=20, verbose_name='Categoria'),
        ),
    ]
