# Generated by Django 5.2.4 on 2026-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_galeriaescola_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilescola',
            name='inscricoes_abertas',
            field=models.BooleanField(default=False, help_text='Marque se a escola está atualmente a aceitar inscrições.', verbose_name='Inscrições Abertas?'),
        ),
        migrations.AddField(
            model_name='perfilescola',
            name='prazo_inscricoes',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo das Inscrições'),
        ),
        migrations.AddField(
            model_name='perfilescola',
            name='requisitos_inscricao',
            field=models.TextField(blank=True, help_text='Ex: Cópia do BI, 4 Fotografias, Certificado de Habilitações, etc.', verbose_name='Requisitos e Documentos'),
        ),
    ]
