# Generated by Django 6.0.5 on 2026-06-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_perfilescola_inscricoes_abertas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentanteEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('diretor', 'Diretor/Diretora'), ('diretor_adjunto', 'Diretor/Diretora Adjunto'), ('secretario', 'Secretário/Secretária'), ('coordenador', 'Coordenador/Coordenadora'), ('gestor_admin', 'Gestor Administrativo'), ('outro', 'Outro')], default='gestor_admin', max_length=50, verbose_name='Cargo')),
                ('data_associacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Associação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='escolas.escola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representante_escolas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Representante de Escola',
                'verbose_name_plural': 'Representantes de Escolas',
                'ordering': ['-data_associacao'],
                'unique_together': {('user', 'escola')},
            },
        ),
    ]
