# Generated by Django 6.0.5 on 2026-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_representanteescola'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilescola',
            name='video_banner',
            field=models.FileField(blank=True, help_text='Vídeo institucional em formato MP4 para rodar em loop no fundo do banner (sem áudio).', null=True, upload_to='escolas/videos/', verbose_name='Vídeo de Fundo (MP4)'),
        ),
        migrations.AddField(
            model_name='perfilescola',
            name='video_banner_url',
            field=models.URLField(blank=True, help_text='URL direta para um vídeo MP4 hospedado (ex: no Cloudinary ou outro servidor).', null=True, verbose_name='URL do Vídeo de Fundo (MP4)'),
        ),
    ]
