# Generated by Django 6.0.5 on 2026-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0008_perfilescola_video_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilescola',
            name='foto_historia',
            field=models.ImageField(blank=True, help_text='Imagem ilustrativa para a seção de História / Quem Somos.', null=True, upload_to='escolas/sobre/', verbose_name='Imagem de Quem Somos / História'),
        ),
        migrations.AddField(
            model_name='perfilescola',
            name='foto_missao',
            field=models.ImageField(blank=True, help_text='Imagem ilustrativa para a seção de Missão.', null=True, upload_to='escolas/sobre/', verbose_name='Imagem da Missão'),
        ),
        migrations.AddField(
            model_name='perfilescola',
            name='foto_visao',
            field=models.ImageField(blank=True, help_text='Imagem ilustrativa para a seção de Visão.', null=True, upload_to='escolas/sobre/', verbose_name='Imagem da Visão'),
        ),
    ]
