# Generated by Django 5.2 on 2025-04-18 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('biografia', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instrutores/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area_especializacao', models.CharField(choices=[('TECNOLOGIA_INFORMACAO', 'tecnologia de informacao'), ('NEGOCIO', 'negocio'), ('LINGUAS', 'linguas'), ('ESPECIALIZADA', 'especializada'), ('CIENCIAS', 'ciencias'), ('ARTES', 'artes'), ('ENGENHARIA', 'engenharia'), ('SAUDE', 'saude'), ('OUTRO', 'outro')], max_length=100)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título do Curso')),
                ('descricao', models.TextField(verbose_name='Descrição Completa')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1, verbose_name='Nível')),
                ('idioma', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('OUTRO', 'Outro')], default='PT', max_length=5, verbose_name='Idioma do Curso')),
                ('certificado', models.BooleanField(default=True, verbose_name='Fornece Certificado')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Valor do Curso')),
                ('vagas', models.PositiveIntegerField(verbose_name='Número de Vagas')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Curso Ativo')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagem do Curso')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.centrodeformacao', verbose_name='Centro de Formação')),
                ('instrutores', models.ManyToManyField(related_name='cursos', to='cursos_app.instrutor', verbose_name='Instrutores')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='cursos/materiais/')),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('SLIDE', 'Apresentação de Slides'), ('PLANILHA', 'Planilha'), ('CODIGO', 'Código-fonte'), ('OUTRO', 'Outro')], default='PDF', max_length=50)),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('disponivel', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_apoio', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Material de Apoio',
                'verbose_name_plural': 'Materiais de Apoio',
                'ordering': ['-data_adicao'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Tópico')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem no Curso')),
                ('duracao', models.PositiveIntegerField(default=60, verbose_name='Duração (minutos)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='cursos/videos/')),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('liberado', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos_app.modulo')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inscrição')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Aprovado'), ('REJ', 'Rejeitado'), ('CAN', 'Cancelado')], default='PEN', max_length=3, verbose_name='Status')),
                ('certificado_emitido', models.BooleanField(default=False, verbose_name='Certificado Emitido')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno', verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_app.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('aluno', 'curso')},
            },
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['titulo', 'centro'], name='cursos_titulo_1c1d44_idx'),
        ),
    ]
