# Generated by Django 5.2.4 on 2025-07-23 11:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestoreduka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inscrição')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Aprovado'), ('REJ', 'Rejeitado'), ('CAN', 'Cancelado')], default='PEN', max_length=3, verbose_name='Status')),
                ('certificado_emitido', models.BooleanField(default=False, verbose_name='Certificado Emitido')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('biografia', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instrutores/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area_especializacao', models.CharField(choices=[('TECNOLOGIA_INFORMACAO', 'tecnologia de informacao'), ('NEGOCIO', 'negocio'), ('LINGUAS', 'linguas'), ('ESPECIALIZADA', 'especializada'), ('CIENCIAS', 'ciencias'), ('ARTES', 'artes'), ('ENGENHARIA', 'engenharia'), ('SAUDE', 'saude'), ('OUTRO', 'outro')], max_length=100)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='cursos/materiais/')),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('SLIDE', 'Apresentação de Slides'), ('PLANILHA', 'Planilha'), ('CODIGO', 'Código-fonte'), ('OUTRO', 'Outro')], default='PDF', max_length=50)),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('disponivel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Material de Apoio',
                'verbose_name_plural': 'Materiais de Apoio',
                'ordering': ['-data_adicao'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PerfilInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='instrutores/capas/')),
                ('biografia_completa', models.TextField()),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('total_alunos', models.PositiveIntegerField(default=0)),
                ('total_cursos', models.PositiveIntegerField(default=0)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('nota_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='cursos/videos/')),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('liberado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título do Curso')),
                ('descricao', models.TextField(verbose_name='Descrição Completa')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1, verbose_name='Nível')),
                ('idioma', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('OUTRO', 'Outro')], default='PT', max_length=5, verbose_name='Idioma do Curso')),
                ('certificado', models.BooleanField(default=True, verbose_name='Fornece Certificado')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas)')),
                ('preco', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do Curso')),
                ('vagas', models.PositiveIntegerField(verbose_name='Número de Vagas')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Curso Ativo')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagem do Curso')),
                ('destaque', models.BooleanField(default=False, verbose_name='Curso em Destaque')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso', to='cursos_app.categoria')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
