# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('mensagem_destaque', models.CharField(blank=True, help_text='Mensagem personalizada para exibir acima dos cursos desta categoria', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-data_adicao'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('SALAS', 'Salas de Aula'), ('LABS', 'Laboratórios'), ('EVENTOS', 'Eventos')], max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inscrição')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceita'), ('N', 'Negada'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Status')),
                ('tipo_inscricao', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], default='ONLINE', max_length=10, verbose_name='Tipo de Inscrição')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('DEPOSITO', 'Depósito'), ('SIMULADO', 'Pagamento Simulado'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Forma de Pagamento')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante de Pagamento')),
                ('pagamento_simulado', models.BooleanField(default=False, verbose_name='Pagamento Simulado')),
                ('codigo_simulacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Simulação')),
                ('data_simulacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Simulação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('biografia', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instrutores/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area_especializacao', models.CharField(choices=[('TECNOLOGIA_INFORMACAO', 'Tecnologia de Informação'), ('NEGOCIO', 'Negócio'), ('LINGUAS', 'Línguas'), ('ESPECIALIZADA', 'Especializada'), ('CIENCIAS', 'Ciências'), ('ARTES', 'Artes'), ('ENGENHARIA', 'Engenharia'), ('SAUDE', 'Saúde'), ('OUTRO', 'Outro')], max_length=100)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='cursos/materiais/')),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('SLIDE', 'Apresentação de Slides'), ('PLANILHA', 'Planilha'), ('CODIGO', 'Código-fonte'), ('OUTRO', 'Outro')], default='PDF', max_length=50)),
                ('data_adicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('disponivel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Material de Apoio',
                'verbose_name_plural': 'Materiais de Apoio',
                'ordering': ['-data_adicao'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PerfilInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='instrutores/capas/')),
                ('biografia_completa', models.TextField()),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('total_alunos', models.PositiveIntegerField(default=0)),
                ('total_cursos', models.PositiveIntegerField(default=0)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('nota_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Turma')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='MANHA', max_length=10, verbose_name='Turno')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('dias_semana', models.CharField(help_text='Ex: SEG,QUA,SEX ou TER,QUI', max_length=100, verbose_name='Dias da Semana')),
                ('vagas_totais', models.PositiveIntegerField(verbose_name='Vagas Totais')),
                ('vagas_ocupadas', models.PositiveIntegerField(default=0, verbose_name='Vagas Ocupadas')),
                ('vagas_disponiveis', models.PositiveIntegerField(default=0, verbose_name='Vagas Disponíveis')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local das Aulas')),
                ('sala', models.CharField(blank=True, max_length=50, verbose_name='Sala')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['data_inicio', 'turno'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='cursos/videos/')),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('liberado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título do Curso')),
                ('descricao', models.TextField(verbose_name='Descrição Completa')),
                ('descricao_curta', models.CharField(blank=True, help_text='Descrição resumida para cards e listagens', max_length=300, verbose_name='Descrição Curta')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1, verbose_name='Nível')),
                ('idioma', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('OUTRO', 'Outro')], default='PT', max_length=5, verbose_name='Idioma do Curso')),
                ('certificado', models.BooleanField(default=True, verbose_name='Fornece Certificado')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas)')),
                ('is_gratuito', models.BooleanField(default=False, help_text='Define se o curso é gratuito ou pago', verbose_name='Curso Gratuito')),
                ('preco', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço do Curso')),
                ('preco_inscricao', models.DecimalField(decimal_places=3, default=0, help_text='Valor da taxa de inscrição (pode ser diferente do preço do curso)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Inscrição')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=3, help_text='Preço com desconto (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Promocional')),
                ('data_inicio_promocao', models.DateTimeField(blank=True, null=True, verbose_name='Início da Promoção')),
                ('data_fim_promocao', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Promoção')),
                ('vagas_minimas', models.PositiveIntegerField(default=1, help_text='Número mínimo de alunos para uma turma acontecer', verbose_name='Vagas Mínimas por Turma')),
                ('data_inicio_inscricoes', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início das Inscrições')),
                ('data_fim_inscricoes', models.DateTimeField(blank=True, null=True, verbose_name='Fim das Inscrições')),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=10, verbose_name='Modalidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Curso Ativo')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagem do Curso')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Pré-requisitos')),
                ('objetivo_geral', models.TextField(blank=True, verbose_name='Objetivo Geral')),
                ('publico_alvo', models.TextField(blank=True, verbose_name='Público-Alvo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Curso em Destaque')),
                ('permite_parcelamento', models.BooleanField(default=False, verbose_name='Permite Parcelamento')),
                ('max_parcelas', models.PositiveIntegerField(default=1, verbose_name='Máximo de Parcelas')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável (preenchido automaticamente)', unique=True, verbose_name='Slug')),
                ('tags', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=500, verbose_name='Tags')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso', to='cursos_app.categoria')),
            ],
        ),
    ]
