# Generated by Django 5.2.4 on 2025-07-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_app.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='instrutores',
            field=models.ManyToManyField(related_name='cursos', to='cursos_app.instrutor', verbose_name='Instrutores'),
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_apoio', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='perfilinstrutor',
            name='instrutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='cursos_app.instrutor'),
        ),
        migrations.AddField(
            model_name='video',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos_app.modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('aluno', 'curso')},
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['titulo', 'centro'], name='cursos_titulo_1c1d44_idx'),
        ),
    ]
