# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0001_initial'),
        ('gestoreduka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação'),
        ),
    ]
