# Generated by Django 5.2.4 on 2025-07-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, null=True, verbose_name='Pré-requisitos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='video_apresentacao',
            field=models.URLField(blank=True, null=True, verbose_name='Vídeo de Apresentação'),
        ),
    ]
