# Generated by Django 5.2 on 2025-04-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0002_alter_curso_preco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
