# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0002_initial'),
        ('gestoreduka', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='centro_de_formacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação'),
        ),
        migrations.AddField(
            model_name='curso',
            name='instrutores',
            field=models.ManyToManyField(related_name='cursos', to='cursos_app.instrutor', verbose_name='Instrutores'),
        ),
        migrations.AddField(
            model_name='materialapoio',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_apoio', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='perfilinstrutor',
            name='instrutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='cursos_app.instrutor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='instrutor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos_app.instrutor', verbose_name='Instrutor Principal'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='turma_escolhida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_turma', to='cursos_app.turma', verbose_name='Turma Escolhida'),
        ),
        migrations.AddField(
            model_name='video',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos_app.modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('aluno', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('curso', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('aluno', 'curso')},
        ),
    ]
