# Generated by Django 5.2.4 on 2025-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0003_curso_requisitos_curso_video_apresentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('I', 'Integral')], default='M', max_length=1, verbose_name='Turno'),
        ),
    ]
