# Generated by Django 5.2.4 on 2026-02-02 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video_previa_url',
            field=models.URLField(blank=True, help_text='Link do vídeo de apresentação (YouTube, Vimeo, etc.)', null=True, verbose_name='Vídeo de Prévia do Curso'),
        ),
        migrations.CreateModel(
            name='TopicoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Tópico / O que será aprendido')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Tópico do Curso',
                'verbose_name_plural': 'Tópicos do Curso',
                'ordering': ['ordem'],
            },
        ),
    ]
