# Generated by Django 5.2 on 2025-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0003_delete_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Curso em Destaque'),
        ),
    ]
