# Generated by Django 5.2.4 on 2025-07-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0004_curso_turno'),
        ('gestoreduka', '0002_areaformacao_certificacao_depoimento_diferencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mensagem_destaque',
            field=models.CharField(blank=True, help_text='Mensagem personalizada para exibir acima dos cursos desta categoria', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('SALAS', 'Salas de Aula'), ('LABS', 'Laboratórios'), ('EVENTOS', 'Eventos')], max_length=50, verbose_name='Categoria')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='gestoreduka.centrodeformacao')),
            ],
        ),
    ]
