# Generated by Django 5.2.4 on 2026-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0004_curso_video_previa_url_topicocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='instrutores/capas/'),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='nota_media',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='total_alunos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='total_avaliacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='total_cursos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PerfilInstrutor',
        ),
    ]
