# Generated by Django 5.2.4 on 2026-02-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0005_instrutor_facebook_instrutor_foto_capa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
