# Generated by Django 5.2 on 2025-04-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0006_categoria_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='instrutores/capas/')),
                ('biografia_completa', models.TextField()),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('total_alunos', models.PositiveIntegerField(default=0)),
                ('total_cursos', models.PositiveIntegerField(default=0)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('nota_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('instrutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='cursos_app.instrutor')),
            ],
        ),
    ]
