# Generated by Django 5.2.4 on 2025-08-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0006_favorito'),
        ('usuarios', '0002_centroseguimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='certificado_emitido',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='nota_final',
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='usuarios.aluno'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='cursos_app.curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceita'), ('N', 'Negada')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
