# Generated by Django 5.2.4 on 2026-02-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0006_delete_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRequisitoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Pré-requisito')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisitos', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Pré-requisito do Curso',
                'verbose_name_plural': 'Pré-requisitos do Curso',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PublicoAlvoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Público-Alvo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publico_alvo_items', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Público-Alvo do Curso',
                'verbose_name_plural': 'Públicos-Alvo do Curso',
                'ordering': ['ordem'],
            },
        ),
    ]
