# Generated by Django 5.2.4 on 2025-09-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0007_remove_inscricao_certificado_emitido_and_more'),
        ('gestoreduka', '0002_areaformacao_certificacao_depoimento_diferencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='centro_de_formacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='area_especializacao',
            field=models.CharField(choices=[('TECNOLOGIA_INFORMACAO', 'Tecnologia de Informação'), ('NEGOCIO', 'Negócio'), ('LINGUAS', 'Línguas'), ('ESPECIALIZADA', 'Especializada'), ('CIENCIAS', 'Ciências'), ('ARTES', 'Artes'), ('ENGENHARIA', 'Engenharia'), ('SAUDE', 'Saúde'), ('OUTRO', 'Outro')], max_length=100),
        ),
    ]
