# Generated by Django 5.2.4 on 2026-03-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0007_prerequisitocurso_publicoalvocurso'),
        ('gestoreduka', '0005_alter_filial_options_filial_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gestoreduka.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='gestoreduka.filial', verbose_name='Filial'),
        ),
    ]
