# Generated by Django 5.2 on 2025-04-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0007_perfilinstrutor'),
        ('usuarios', '0004_perfilaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='usuarios.centrodeformacao', verbose_name='Centro de Formação'),
        ),
    ]
