# Generated by Django 5.2.4 on 2025-07-12 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0008_alter_curso_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do Curso'),
        ),
    ]
