# Generated by Django 5.2.7 on 2025-11-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0008_instrutor_centro_de_formacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='video_apresentacao',
        ),
    ]
