# Generated by Django 5.2.4 on 2026-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0008_curso_filial_instrutor_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='publico_alvo',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.CharField(blank=True, choices=[('1_SEMANA', '1 Semana'), ('2_SEMANAS', '2 Semanas'), ('3_SEMANAS', '3 Semanas'), ('1_MES', '1 Mês'), ('2_MESES', '2 Meses'), ('3_MESES', '3 Meses'), ('4_MESES', '4 Meses'), ('5_MESES', '5 Meses'), ('6_MESES', '6 Meses'), ('7_MESES', '7 Meses'), ('8_MESES', '8 Meses'), ('9_MESES', '9 Meses'), ('10_MESES', '10 Meses'), ('11_MESES', '11 Meses'), ('1_ANO', '1 Ano')], max_length=20, null=True, verbose_name='Duração'),
        ),
        migrations.DeleteModel(
            name='PublicoAlvoCurso',
        ),
    ]
