# Generated by Django 5.2.7 on 2025-11-07 21:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0009_remove_curso_video_apresentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Turma')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='MANHA', max_length=10, verbose_name='Turno')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('dias_semana', models.CharField(help_text='Ex: SEG,QUA,SEX ou TER,QUI', max_length=100, verbose_name='Dias da Semana')),
                ('vagas_totais', models.PositiveIntegerField(verbose_name='Vagas Totais')),
                ('vagas_ocupadas', models.PositiveIntegerField(default=0, verbose_name='Vagas Ocupadas')),
                ('vagas_disponiveis', models.PositiveIntegerField(default=0, verbose_name='Vagas Disponíveis')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local das Aulas')),
                ('sala', models.CharField(blank=True, max_length=50, verbose_name='Sala')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['data_inicio', 'turno'],
            },
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='curso',
            name='cursos_titulo_1c1d44_idx',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_termino',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='vagas',
        ),
        migrations.AddField(
            model_name='curso',
            name='avaliacao',
            field=models.TextField(blank=True, verbose_name='Sistema de Avaliação'),
        ),
        migrations.AddField(
            model_name='curso',
            name='bibliografia',
            field=models.TextField(blank=True, verbose_name='Bibliografia Recomendada'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='data_fim_inscricoes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_fim_promocao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Promoção'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio_inscricoes',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início das Inscrições'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio_promocao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Promoção'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao_curta',
            field=models.CharField(blank=True, help_text='Descrição resumida para cards e listagens', max_length=300, verbose_name='Descrição Curta'),
        ),
        migrations.AddField(
            model_name='curso',
            name='material_incluso',
            field=models.TextField(blank=True, verbose_name='Material Incluso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='max_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Máximo de Parcelas'),
        ),
        migrations.AddField(
            model_name='curso',
            name='metodologia',
            field=models.TextField(blank=True, verbose_name='Metodologia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=10, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AddField(
            model_name='curso',
            name='permite_parcelamento',
            field=models.BooleanField(default=False, verbose_name='Permite Parcelamento'),
        ),
        migrations.AddField(
            model_name='curso',
            name='preco_inscricao',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Valor da taxa de inscrição (pode ser diferente do preço do curso)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Inscrição'),
        ),
        migrations.AddField(
            model_name='curso',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Preço com desconto (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Promocional'),
        ),
        migrations.AddField(
            model_name='curso',
            name='publico_alvo',
            field=models.TextField(blank=True, verbose_name='Público-Alvo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável (preenchido automaticamente)', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tags',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=500, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='curso',
            name='vagas_minimas',
            field=models.PositiveIntegerField(default=1, help_text='Número mínimo de alunos para uma turma acontecer', verbose_name='Vagas Mínimas por Turma'),
        ),
        migrations.AddField(
            model_name='curso',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('DEPOSITO', 'Depósito'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='tipo_inscricao',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], default='ONLINE', max_length=10, verbose_name='Tipo de Inscrição'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço do Curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceita'), ('N', 'Negada'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterModelTable(
            name='curso',
            table=None,
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos_app.curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='instrutor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos_app.instrutor', verbose_name='Instrutor Principal'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='turma_escolhida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_turma', to='cursos_app.turma', verbose_name='Turma Escolhida'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('curso', 'codigo')},
        ),
    ]
