# Generated by Django 5.2.4 on 2026-04-19 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0009_remove_curso_publico_alvo_curso_duracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='moeda',
            field=models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar (USD)')], default='AOA', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço do Curso'),
        ),
    ]
