# Generated by Django 5.2.4 on 2026-04-20 14:34

import cursos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0010_curso_moeda_alter_curso_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video_preview_file',
            field=models.FileField(blank=True, help_text='Carregue um vídeo curto de apresentação (Máx: 50MB)', null=True, upload_to='cursos/previews/', validators=[cursos_app.models.validate_video_size], verbose_name='Ficheiro de Vídeo de Prévia'),
        ),
    ]
