# Generated by Django 5.2.7 on 2025-11-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0010_turma_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável (preenchido automaticamente)', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
