# Generated by Django 5.2.4 on 2026-05-01 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0011_curso_video_preview_file'),
        ('gestoreduka', '0011_notificacaogestor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='titulo',
            field=models.CharField(blank=True, help_text='Ex: Especialista em Django, Mestre em Economia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='centro_de_formacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='gestoreduka.centrodeformacao', verbose_name='Centro de Formação'),
        ),
    ]
