# Generated by Django 5.2.7 on 2025-11-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0011_alter_curso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, default=1, help_text='URL amigável (preenchido automaticamente)', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
