# Generated by Django 5.2.7 on 2025-11-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0012_alter_curso_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='bibliografia',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='material_incluso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='metodologia',
        ),
    ]
