# Generated by Django 5.2.4 on 2026-05-15 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0013_alter_curso_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Curso Ativo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='destaque',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Curso em Destaque'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idioma',
            field=models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('OUTRO', 'Outro')], db_index=True, default='PT', max_length=5, verbose_name='Idioma do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='is_gratuito',
            field=models.BooleanField(db_index=True, default=False, help_text='Define se o curso é gratuito ou pago', verbose_name='Curso Gratuito'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Híbrido')], db_index=True, default='PRESENCIAL', max_length=10, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], db_index=True, default='B', max_length=1, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='publicado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='visualizacoes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_inscricao',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceita'), ('N', 'Negada'), ('C', 'Cancelada')], db_index=True, default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='tipo_inscricao',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], db_index=True, default='ONLINE', max_length=10, verbose_name='Tipo de Inscrição'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=20, verbose_name='Status'),
        ),
    ]
