# Generated by Django 6.0 on 2026-01-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0013_remove_curso_avaliacao_remove_curso_bibliografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_inicio_curso',
            field=models.DateTimeField(blank=True, help_text='Data em que o curso realmente começa', null=True, verbose_name='Início do Curso'),
        ),
    ]
