# Generated by Django 5.2.4 on 2026-05-20 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0014_alter_curso_ativo_alter_curso_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoCurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código de Verificação')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_emitido', to='cursos_app.inscricao')),
            ],
            options={
                'verbose_name': 'Certificado de Curso',
                'verbose_name_plural': 'Certificados de Cursos',
            },
        ),
    ]
