# Generated by Django 6.0 on 2026-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0014_curso_data_inicio_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='data_inicio_curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
