# Generated by Django 6.0.5 on 2026-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0015_certificadocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='documento_requerido',
            field=models.CharField(choices=[('BI', 'Bilhete de Identidade (BI)'), ('PASSAPORTE', 'Passaporte'), ('DIPLOMA', 'Diploma / Certificado de Habilitações'), ('NENHUM', 'Nenhum (Inscrição Direta)')], default='NENHUM', help_text='Defina se o aluno precisa de enviar algum documento para se inscrever neste curso', max_length=20, verbose_name='Documento Obrigatório para Inscrição'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='documento_inscricao',
            field=models.FileField(blank=True, help_text='Cópia do documento enviado pelo aluno durante a inscrição', null=True, upload_to='documentos_inscricao/', verbose_name='Documento de Inscrição'),
        ),
    ]
