# Generated by Django 6.0 on 2026-01-15 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0015_remove_curso_data_inicio_curso_curso_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='data_fim_inscricoes',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_inicio_inscricoes',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='max_parcelas',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='objetivo_geral',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='permite_parcelamento',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='publico_alvo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='requisitos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='vagas_minimas',
        ),
        migrations.AddField(
            model_name='curso',
            name='is_gratuito',
            field=models.BooleanField(default=False, verbose_name='Curso Gratuito'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='cursos_app.categoria'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_fim_promocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio_promocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idioma',
            field=models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('OUTRO', 'Outro')], default='PT', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco_inscricao',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Inscrição'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
