# Generated by Django 6.0 on 2026-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0016_remove_curso_data_fim_inscricoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
