# Generated by Django 6.0.5 on 2026-06-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0016_curso_documento_requerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='codigo_inscricao',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Código de Inscrição'),
        ),
    ]
