# Generated by Django 6.0 on 2026-01-15 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0017_curso_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_fim_inscricoes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio_inscricoes',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início das Inscrições'),
        ),
        migrations.AddField(
            model_name='curso',
            name='max_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Máximo de Parcelas'),
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AddField(
            model_name='curso',
            name='permite_parcelamento',
            field=models.BooleanField(default=False, verbose_name='Permite Parcelamento'),
        ),
        migrations.AddField(
            model_name='curso',
            name='publico_alvo',
            field=models.TextField(blank=True, verbose_name='Público-Alvo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, null=True, verbose_name='Pré-requisitos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tags',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=500, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='curso',
            name='vagas_minimas',
            field=models.PositiveIntegerField(default=1, help_text='Número mínimo de alunos para uma turma acontecer', verbose_name='Vagas Mínimas por Turma'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Curso Ativo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso', to='cursos_app.categoria'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_fim_promocao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Promoção'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio_promocao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Promoção'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao_curta',
            field=models.CharField(blank=True, help_text='Descrição resumida para cards e listagens', max_length=300, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Curso em Destaque'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idioma',
            field=models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('OUTRO', 'Outro')], default='PT', max_length=5, verbose_name='Idioma do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagem do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='is_gratuito',
            field=models.BooleanField(default=False, help_text='Define se o curso é gratuito ou pago', verbose_name='Curso Gratuito'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco_inscricao',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Valor da taxa de inscrição (pode ser diferente do preço do curso)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Inscrição'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Preço com desconto (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável (preenchido automaticamente)', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
