# Generated by Django 6.0.5 on 2026-06-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0017_inscricao_codigo_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='mensalidade',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Valor da mensalidade (opcional, aplicável se o curso tiver pagamentos mensais)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da Mensalidade'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_cobranca_inscricao',
            field=models.CharField(choices=[('APENAS_TAXA', 'Apenas Taxa de Inscrição'), ('TAXA_E_MENSALIDADE', 'Taxa de Inscrição + 1ª Mensalidade'), ('CURSO_COMPLETO', 'Preço Total do Curso')], default='APENAS_TAXA', help_text='Define o valor exato a ser cobrado ao aluno pelo portal na hora da inscrição.', max_length=25, verbose_name='O que cobrar na Inscrição Online?'),
        ),
    ]
