# Generated by Django 6.0.5 on 2026-06-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0018_curso_mensalidade_curso_tipo_cobranca_inscricao'),
        ('gestoreduka', '0016_alter_notificacaogestor_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='filial',
        ),
        migrations.AddField(
            model_name='curso',
            name='filiais',
            field=models.ManyToManyField(blank=True, related_name='cursos_disponiveis', to='gestoreduka.filial', verbose_name='Filiais onde o curso está disponível'),
        ),
        migrations.AddField(
            model_name='turma',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Se não for especificado, a turma pertence à Sede (Centro Principal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='gestoreduka.filial', verbose_name='Filial'),
        ),
    ]
