# Generated by Django 5.2.4 on 2026-08-13 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0025_seed_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da Aula')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('ATRASO', 'Atraso'), ('JUSTIFICADA', 'Falta justificada')], default='PRESENTE', max_length=12, verbose_name='Estado')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('registada_em', models.DateTimeField(auto_now=True, verbose_name='Registada em')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='cursos_app.inscricao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='cursos_app.turma')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-data', 'inscricao__aluno__nome'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'inscricao', 'data'), name='unique_presenca_turma_inscricao_data')],
            },
        ),
    ]
