# Generated by Django 5.2.4 on 2026-08-13 21:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0026_presencas_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(default='Nota Final', max_length=100, verbose_name='Avaliação')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Nota')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('registada_em', models.DateTimeField(auto_now=True, verbose_name='Registada em')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='cursos_app.inscricao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='cursos_app.turma')),
            ],
            options={
                'verbose_name': 'Nota do Aluno',
                'verbose_name_plural': 'Notas dos Alunos',
                'ordering': ['inscricao__aluno__nome', 'avaliacao'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'inscricao', 'avaliacao'), name='unique_nota_turma_inscricao_avaliacao')],
            },
        ),
    ]
