# Generated by Django 5.2.4 on 2026-08-14 06:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0027_notas_alunos'),
        ('usuarios', '0015_create_muquissi_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_matricula', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Código da Matrícula')),
                ('origem', models.CharField(choices=[('EDUKA_ANGOLA', 'Eduka-Angola'), ('PRESENCIAL', 'Atendimento presencial'), ('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('IMPORTACAO', 'Importação')], db_index=True, default='PRESENCIAL', max_length=20, verbose_name='Origem')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVA', 'Ativa'), ('SUSPENSA', 'Suspensa'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('TRANSFERIDA', 'Transferida')], db_index=True, default='ATIVA', max_length=16, verbose_name='Estado')),
                ('valor_acordado', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Acordado')),
                ('desconto', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto')),
                ('data_matricula', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da Matrícula')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='usuarios.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='cursos_app.curso')),
                ('inscricao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula_confirmada', to='cursos_app.inscricao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_registadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='cursos_app.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_matricula'],
                'indexes': [models.Index(fields=['curso', 'estado'], name='cursos_app__curso_i_508ee9_idx'), models.Index(fields=['origem', 'data_matricula'], name='cursos_app__origem_e76bf8_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'turma'), name='unique_matricula_aluno_turma')],
            },
        ),
    ]
