# Generated by Django 5.2.4 on 2026-08-14 06:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0028_matricula_operacional'),
        ('pagamentos', '0009_recebimentos_centro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('descricao', models.CharField(blank=True, max_length=120, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Estado')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cursos_app.matricula')),
                ('recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_pagas', to='pagamentos.recebimentocentro')),
            ],
            options={
                'verbose_name': 'Parcela de Matrícula',
                'verbose_name_plural': 'Parcelas de Matrícula',
                'ordering': ['matricula', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('matricula', 'numero'), name='unique_parcela_matricula_numero')],
            },
        ),
    ]
