# Generated by Django 5.2.4 on 2026-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0029_parcelas_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_cobranca_inscricao',
            field=models.CharField(choices=[('SEM_PAGAMENTO', 'Inscrição direta — sem pagamento no ato'), ('APENAS_TAXA', 'Cobrar apenas a taxa de inscrição'), ('TAXA_E_MENSALIDADE', 'Cobrar taxa de inscrição + 1ª mensalidade'), ('CURSO_COMPLETO', 'Cobrar o preço total do curso')], default='APENAS_TAXA', help_text='Define o valor exato a ser cobrado ao aluno pelo portal na hora da inscrição.', max_length=25, verbose_name='O que cobrar na Inscrição Online?'),
        ),
    ]
