# Generated by Django 5.2.4 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cursos_app', '0037_corrigir_vagas_turma_teste_zango'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='comprovativo_enviado_em',
            field=models.DateTimeField(
                blank=True,
                help_text='Momento em que o comprovativo oficial foi enviado ao aluno por e-mail.',
                null=True,
                verbose_name='Comprovativo enviado em',
            ),
        ),
    ]
