# Generated by Django 5.2.4 on 2026-08-23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0038_inscricao_comprovativo_enviado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='moeda',
            field=models.CharField(
                choices=[
                    ('AOA', 'Kwanza (AOA)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dólar (USD)'),
                    ('MZN', 'Metical moçambicano (MZN)'), ('XOF', 'Franco CFA da África Ocidental (XOF)'),
                    ('CVE', 'Escudo cabo-verdiano (CVE)'), ('BRL', 'Real brasileiro (BRL)'),
                    ('STN', 'Dobra são-tomense (STN)'),
                ],
                default='AOA',
                max_length=3,
                verbose_name='Moeda',
            ),
        ),
    ]
