# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoNavegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('modulo', models.CharField(blank=True, max_length=50)),
                ('data_acesso', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Histórico de Navegação',
                'verbose_name_plural': 'Históricos de Navegação',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.CreateModel(
            name='PontuacaoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=0.0)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pontuação de Interesse',
                'verbose_name_plural': 'Pontuações de Interesses',
            },
        ),
        migrations.CreateModel(
            name='VisualizacaoInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('CURSO_PRESENCIAL', 'Curso Presencial'), ('CURSO_VIDEO', 'Curso de Vídeo'), ('CENTRO', 'Centro de Formação')], max_length=20)),
                ('data_visualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracao_segundos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visualização Inteligente',
                'verbose_name_plural': 'Visualizações Inteligentes',
            },
        ),
    ]
