# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0003_initial'),
        ('inteligencia', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiconavegacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navegacao', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='pontuacaointeresse',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='pontuacaointeresse',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_app.categoria'),
        ),
        migrations.AddField(
            model_name='visualizacaointeligente',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes_ia', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='visualizacaointeligente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos_app.categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='pontuacaointeresse',
            unique_together={('aluno', 'categoria')},
        ),
    ]
