# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestoreduka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mensal')),
                ('limite_cursos', models.PositiveIntegerField(default=5, verbose_name='Limite de Cursos')),
                ('alcance_km', models.PositiveIntegerField(default=10, verbose_name='Alcance Geográfico (km)')),
                ('selo_verificacao', models.BooleanField(default=False, verbose_name='Selo de Verificação')),
                ('prioridade_busca', models.PositiveIntegerField(default=0, verbose_name='Prioridade na Busca')),
                ('destaque_home', models.BooleanField(default=False, verbose_name='Destaque na Página Principal')),
                ('acesso_relatorios', models.BooleanField(default=False, verbose_name='Acesso a Relatórios')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['preco'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente de Pagamento')], default='PENDENTE', max_length=20)),
                ('renovacao_automatica', models.BooleanField(default=True)),
                ('centro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='gestoreduka.centrodeformacao')),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planos.plano')),
            ],
            options={
                'verbose_name': 'Assinatura de Membro',
                'verbose_name_plural': 'Assinaturas de Membros',
            },
        ),
    ]
