# Generated by Django 5.2.4 on 2026-05-20 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0013_alter_anunciocentro_options_anunciocentro_importante'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Ativação')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='gestoreduka.centrodeformacao')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='planos.plano')),
            ],
            options={
                'verbose_name': 'Voucher de Plano',
                'verbose_name_plural': 'Vouchers de Planos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
