# Generated by Django 5.2.4 on 2026-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_voucherplano'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='permite_gerar_certificado',
            field=models.BooleanField(default=False, verbose_name='Permite Gerar Certificados'),
        ),
        migrations.AddField(
            model_name='plano',
            name='permite_inscricao_manual',
            field=models.BooleanField(default=False, verbose_name='Permite Inscrição Manual'),
        ),
    ]
