# Generated by Django 5.2.4 on 2026-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_plano_permite_gerar_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='limite_cursos_video',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade máxima de vídeo-cursos permitida no plano.', verbose_name='Limite de Vídeo-Cursos'),
        ),
        migrations.AddField(
            model_name='plano',
            name='permite_cursos_video',
            field=models.BooleanField(default=False, help_text='Permite ao centro publicar cursos em vídeo sem comissão.', verbose_name='Permite Publicar Vídeo-Cursos'),
        ),
    ]
