# Generated by Django 5.2.4 on 2026-05-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos_app', '0013_alter_curso_preco'),
        ('usuarios', '0011_perfilaluno_interesses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Empresa')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor de Atuação')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('descricao', models.TextField(verbose_name='Sobre a Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa Parceira',
                'verbose_name_plural': 'Empresas Parceiras',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Competência')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('NEGOCIOS', 'Negócios'), ('SAUDE', 'Saúde'), ('ENGENHARIA', 'Engenharia'), ('ARTES', 'Artes'), ('OUTRO', 'Outro')], default='TECNOLOGIA', max_length=20, verbose_name='Categoria')),
                ('nivel_demanda', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Nível de Demanda no Mercado')),
                ('icone', models.CharField(default='feather-activity', max_length=50, verbose_name='Ícone (Feather)')),
                ('cursos_relacionados', models.ManyToManyField(blank=True, related_name='skills', to='cursos_app.curso')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Vaga')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição da Vaga')),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário Mínimo (Opcional)')),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário Máximo (Opcional)')),
                ('localizacao', models.CharField(help_text='Ex: Luanda, Talatona', max_length=150, verbose_name='Localização')),
                ('tipo', models.CharField(choices=[('FULLTIME', 'Tempo Inteiro'), ('PARTTIME', 'Meio Período'), ('CONTRATO', 'Contrato / Projecto'), ('ESTAGIO', 'Estágio'), ('REMOTO', 'Remoto')], default='FULLTIME', max_length=10, verbose_name='Tipo de Vaga')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data Limite (Opcional)')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('SUSPENSA', 'Suspensa')], default='ABERTA', max_length=10)),
                ('destaque', models.BooleanField(default=False)),
                ('competencias_exigidas', models.ManyToManyField(related_name='vagas', to='carreira.skill', verbose_name='Competências Exigidas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='carreira.empresa')),
            ],
            options={
                'verbose_name': 'Vaga de Emprego',
                'verbose_name_plural': 'Vagas de Emprego',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='CandidaturaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('curriculo_atualizado', models.FileField(blank=True, null=True, upload_to='vagas/curriculos/')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem para a Empresa (Opcional)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREVISTA', 'Entrevista'), ('ACEITE', 'Aceite'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_candidaturas', to='usuarios.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='carreira.vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'unique_together': {('vaga', 'aluno')},
            },
        ),
    ]
