# Generated by Django 5.2.4 on 2026-05-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreira', '0001_initial'),
        ('cursovideoapp', '0011_avisocurso_materialaula'),
        ('usuarios', '0011_perfilaluno_interesses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='cursos_video_relacionados',
            field=models.ManyToManyField(blank=True, related_name='skills', to='cursovideoapp.curso_video'),
        ),
        migrations.CreateModel(
            name='AlunoSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisicao', models.DateTimeField(auto_now_add=True)),
                ('comprovada', models.BooleanField(default=False, help_text='Se a skill foi comprovada por conclusão de curso')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_skills', to='usuarios.aluno')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_com_esta_skill', to='carreira.skill')),
            ],
            options={
                'verbose_name': 'Competência do Aluno',
                'verbose_name_plural': 'Competências dos Alunos',
                'unique_together': {('aluno', 'skill')},
            },
        ),
    ]
