# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Área')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Área de Formação',
                'verbose_name_plural': 'Áreas de Formação',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='CentroDeFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Centro')),
                ('nif', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='NIF')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Província')),
                ('localizacao', models.CharField(blank=True, help_text='Usado como fallback quando PostGIS não está disponível', max_length=100, null=True, verbose_name='Localização (Fallback)')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Centro de Formação',
                'verbose_name_plural': 'Centros de Formação',
            },
        ),
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Certificação')),
                ('orgao_emissor', models.CharField(max_length=100, verbose_name='Órgão Emissor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, upload_to='certificacoes/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
            },
        ),
        migrations.CreateModel(
            name='ComentarioReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500, verbose_name='Comentário')),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=True, verbose_name='Aprovado')),
            ],
            options={
                'verbose_name': 'Comentário de Reel',
                'verbose_name_plural': 'Comentários de Reels',
                'ordering': ['-data_comentario'],
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_mensagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-ultima_mensagem'],
            },
        ),
        migrations.CreateModel(
            name='ConviteCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurtidaReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curtida de Reel',
                'verbose_name_plural': 'Curtidas de Reels',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('foto', models.ImageField(blank=True, upload_to='depoimentos/', verbose_name='Foto')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo/Curso')),
                ('texto', models.TextField(verbose_name='Depoimento')),
                ('nota', models.PositiveIntegerField(verbose_name='Nota (1-5)')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado?')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(help_text='Ex: feather-check', max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Diferencial',
                'verbose_name_plural': 'Diferenciais',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, upload_to='equipe/', verbose_name='Foto')),
                ('biografia', models.TextField(verbose_name='Biografia')),
                ('formacao', models.TextField(verbose_name='Formação Acadêmica')),
                ('experiencia', models.TextField(verbose_name='Experiência Profissional')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('icone', models.CharField(help_text='Ex: feather-users', max_length=50, verbose_name='Ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('tipo', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('PALESTRA', 'Palestra'), ('FEIRA', 'Feira de Carreiras'), ('AULA_ABERTA', 'Aula Aberta'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('link_inscricao', models.URLField(blank=True, verbose_name='Link de Inscrição')),
                ('imagem', models.ImageField(blank=True, upload_to='eventos/', verbose_name='Imagem')),
                ('destaque', models.BooleanField(default=False, verbose_name='Evento em Destaque')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Filial')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria de Imagens',
                'ordering': ['ordem', '-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('ARQUIVO', 'Arquivo'), ('IMAGEM', 'Imagem')], default='TEXTO', max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='chat/arquivos/')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('digitando', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa/Instituição')),
                ('logo', models.ImageField(blank=True, upload_to='parcerias/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('tipo_parceria', models.CharField(max_length=100, verbose_name='Tipo de Parceria')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Parceria',
                'verbose_name_plural': 'Parcerias',
            },
        ),
        migrations.CreateModel(
            name='PerfilCentroDeFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dono do Centro')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='centros/', verbose_name='Imagem ou Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='centros/banners/', verbose_name='Imagem de Capa')),
                ('video_apresentacao', models.FileField(blank=True, null=True, upload_to='centros_videos/', verbose_name='Vídeo de Apresentação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('missao', models.TextField(blank=True, null=True, verbose_name='Missão')),
                ('visao', models.TextField(blank=True, null=True, verbose_name='Visão')),
                ('valores', models.TextField(blank=True, null=True, verbose_name='Valores')),
                ('ano_fundacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fundação')),
                ('horario_funcionamento', models.TextField(blank=True, null=True, verbose_name='Horário de Funcionamento')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Centro')),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Híbrido', 'Híbrido')], default='Presencial', max_length=20, verbose_name='Modalidade')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('destaque', models.BooleanField(default=False, verbose_name='Centro em Destaque')),
                ('verificado', models.BooleanField(default=False, verbose_name='Centro Verificado')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('total_seguidores', models.PositiveIntegerField(default=0)),
                ('total_visualizacoes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='ReelCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('video', models.FileField(help_text='Vídeos curtos para engajamento', upload_to='reels/', verbose_name='Vídeo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de capa do vídeo (opcional)', upload_to='reels/thumbnails/', verbose_name='Thumbnail')),
                ('duracao', models.PositiveIntegerField(default=0, help_text='Duração do vídeo em segundos', verbose_name='Duração (segundos)')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('curtidas', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('comentarios', models.PositiveIntegerField(default=0, verbose_name='Comentários')),
                ('compartilhamentos', models.PositiveIntegerField(default=0, verbose_name='Compartilhamentos')),
                ('destaque', models.BooleanField(default=False, verbose_name='Reel em Destaque')),
                ('publico', models.BooleanField(default=True, verbose_name='Público')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['-destaque', '-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='VisualizacaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visualização de Perfil',
                'verbose_name_plural': 'Visualizações de Perfil',
            },
        ),
    ]
