# Generated by Django 5.2.4 on 2025-07-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Centro')),
                ('nif', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Filial')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('centro_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='gestoreduka.centrodeformacao', verbose_name='Centro Principal')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCentroDeFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dono do Centro')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='centros/', verbose_name='Imagem ou Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='centros/banners/', verbose_name='Imagem de Capa')),
                ('video_apresentacao', models.FileField(blank=True, null=True, upload_to='centros videos/', verbose_name='Vídeo de Apresentação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Centro')),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Híbrido', 'Híbrido')], default='Presencial', max_length=20, verbose_name='Modalidade')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('destaque', models.BooleanField(default=False, verbose_name='Centro em Destaque')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('centro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='gestoreduka.centrodeformacao')),
            ],
        ),
    ]
