# Generated by Django 5.2.4 on 2026-01-27 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestoreduka', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeformacao',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centro_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areaformacao',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_formacao', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='certificacao',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='comentarioreel',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='convitecentro',
            name='centro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convite', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='curtidareel',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='depoimento',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='diferencial',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferenciais', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='estatistica',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='filial',
            name='centro_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='gestoreduka.centrodeformacao', verbose_name='Centro Principal'),
        ),
        migrations.AddField(
            model_name='galeriaimagem',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagens', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='gestoreduka.conversa'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente_centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='centro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='reelcentro',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AddField(
            model_name='curtidareel',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_users', to='gestoreduka.reelcentro'),
        ),
        migrations.AddField(
            model_name='comentarioreel',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_lista', to='gestoreduka.reelcentro'),
        ),
        migrations.AddField(
            model_name='visualizacaoperfil',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='visualizacaoperfil',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AlterUniqueTogether(
            name='conversa',
            unique_together={('centro', 'aluno')},
        ),
        migrations.AlterUniqueTogether(
            name='curtidareel',
            unique_together={('reel', 'aluno')},
        ),
    ]
