# Generated by Django 5.2.4 on 2025-07-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Área')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_formacao', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Área de Formação',
                'verbose_name_plural': 'Áreas de Formação',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Certificação')),
                ('orgao_emissor', models.CharField(max_length=100, verbose_name='Órgão Emissor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, upload_to='certificacoes/', verbose_name='Logo')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('foto', models.ImageField(blank=True, upload_to='depoimentos/', verbose_name='Foto')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo/Curso')),
                ('texto', models.TextField(verbose_name='Depoimento')),
                ('nota', models.PositiveIntegerField(verbose_name='Nota (1-5)')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado?')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(help_text='Ex: feather-check', max_length=50, verbose_name='Ícone')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferenciais', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Diferencial',
                'verbose_name_plural': 'Diferenciais',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, upload_to='equipe/', verbose_name='Foto')),
                ('biografia', models.TextField(verbose_name='Biografia')),
                ('formacao', models.TextField(verbose_name='Formação Acadêmica')),
                ('experiencia', models.TextField(verbose_name='Experiência Profissional')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('icone', models.CharField(help_text='Ex: feather-users', max_length=50, verbose_name='Ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
