# Generated by Django 5.2.4 on 2026-02-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaimagem',
            name='categoria',
            field=models.CharField(choices=[('SALAS', 'Salas de Aula'), ('LABS', 'Laboratórios'), ('EVENTOS', 'Eventos'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='galeriaimagem',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
