# Generated by Django 5.2.4 on 2025-09-15 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0002_areaformacao_certificacao_depoimento_diferencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usado', models.BooleanField(default=False)),
                ('centro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convite', to='gestoreduka.centrodeformacao')),
            ],
        ),
    ]
