# Generated by Django 5.2.7 on 2025-10-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0003_convitecentro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrodeformacao',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='centrodeformacao',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='centrodeformacao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='centrodeformacao',
            name='site',
        ),
        migrations.RemoveField(
            model_name='centrodeformacao',
            name='telefone',
        ),
    ]
