# Generated by Django 5.2.7 on 2025-10-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0004_remove_centrodeformacao_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeformacao',
            name='endereco',
            field=models.CharField(default=1, max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='nif',
            field=models.CharField(default=1, max_length=18, unique=True, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='nome',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome do Centro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='telefone',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
