# Generated by Django 5.2.7 on 2025-10-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0005_centrodeformacao_endereco_centrodeformacao_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeformacao',
            name='senha_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha Hash'),
        ),
    ]
