# Generated by Django 5.2.4 on 2026-04-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0005_alter_filial_options_filial_usuario'),
        ('usuarios', '0006_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meus_depoimentos', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='depoimento',
            name='tipo',
            field=models.CharField(choices=[('PLATAFORMA', 'Sobre a Plataforma'), ('CENTRO', 'Sobre o Centro de Formação')], default='PLATAFORMA', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos', to='gestoreduka.centrodeformacao'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='nota',
            field=models.PositiveIntegerField(default=5, verbose_name='Nota (1-5)'),
        ),
    ]
