# Generated by Django 5.2.4 on 2026-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0006_depoimento_aluno_depoimento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeformacao',
            name='fuso_horario',
            field=models.CharField(default='Africa/Luanda', max_length=50, verbose_name='Fuso Horário'),
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='pais',
            field=models.CharField(choices=[('AO', 'Angola'), ('PT', 'Portugal'), ('BR', 'Brasil'), ('CV', 'Cabo Verde'), ('MZ', 'Moçambique'), ('ST', 'São Tomé e Príncipe'), ('GW', 'Guiné-Bissau'), ('TL', 'Timor-Leste')], default='AO', max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='centrodeformacao',
            name='provincia',
            field=models.CharField(blank=True, help_text='Província (Angola) ou Distrito/Região (Portugal)', max_length=100, null=True, verbose_name='Província'),
        ),
    ]
