# Generated by Django 5.2.7 on 2025-10-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0006_centrodeformacao_senha_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodeformacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='centrodeformacao',
            name='nif',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='centrodeformacao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Centro'),
        ),
        migrations.AlterField(
            model_name='centrodeformacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
