# Generated by Django 5.2.7 on 2025-11-05 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0007_alter_centrodeformacao_endereco_and_more'),
        ('usuarios', '0004_alter_usuario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_mensagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativa', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='usuarios.aluno')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'ordering': ['-ultima_mensagem'],
                'unique_together': {('centro', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('ARQUIVO', 'Arquivo'), ('IMAGEM', 'Imagem')], default='TEXTO', max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='chat/arquivos/')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('digitando', models.BooleanField(default=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='gestoreduka.conversa')),
                ('remetente_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('remetente_centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestoreduka.centrodeformacao')),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
    ]
