# Generated by Django 5.2.4 on 2026-04-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0007_centrodeformacao_fuso_horario_centrodeformacao_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='filial',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Longitude'),
        ),
    ]
