# Generated by Django 5.2.7 on 2025-11-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0008_conversa_mensagem'),
        ('usuarios', '0004_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='ano_fundacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fundação'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='horario_funcionamento',
            field=models.TextField(blank=True, null=True, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='missao',
            field=models.TextField(blank=True, null=True, verbose_name='Missão'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='total_seguidores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='total_visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='valores',
            field=models.TextField(blank=True, null=True, verbose_name='Valores'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Centro Verificado'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='visao',
            field=models.TextField(blank=True, null=True, verbose_name='Visão'),
        ),
        migrations.AddField(
            model_name='perfilcentrodeformacao',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='perfilcentrodeformacao',
            name='video_apresentacao',
            field=models.FileField(blank=True, null=True, upload_to='centros_videos/', verbose_name='Vídeo de Apresentação'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('tipo', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('PALESTRA', 'Palestra'), ('FEIRA', 'Feira de Carreiras'), ('AULA_ABERTA', 'Aula Aberta'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('link_inscricao', models.URLField(blank=True, verbose_name='Link de Inscrição')),
                ('imagem', models.ImageField(blank=True, upload_to='eventos/', verbose_name='Imagem')),
                ('destaque', models.BooleanField(default=False, verbose_name='Evento em Destaque')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagens', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria de Imagens',
                'ordering': ['ordem', '-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa/Instituição')),
                ('logo', models.ImageField(blank=True, upload_to='parcerias/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('tipo_parceria', models.CharField(max_length=100, verbose_name='Tipo de Parceria')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Parceria',
                'verbose_name_plural': 'Parcerias',
            },
        ),
        migrations.CreateModel(
            name='ReelCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('video', models.FileField(help_text='Vídeos curtos para engajamento', upload_to='reels/', verbose_name='Vídeo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de capa do vídeo (opcional)', upload_to='reels/thumbnails/', verbose_name='Thumbnail')),
                ('duracao', models.PositiveIntegerField(default=0, help_text='Duração do vídeo em segundos', verbose_name='Duração (segundos)')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('curtidas', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('comentarios', models.PositiveIntegerField(default=0, verbose_name='Comentários')),
                ('compartilhamentos', models.PositiveIntegerField(default=0, verbose_name='Compartilhamentos')),
                ('destaque', models.BooleanField(default=False, verbose_name='Reel em Destaque')),
                ('publico', models.BooleanField(default=True, verbose_name='Público')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['-destaque', '-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500, verbose_name='Comentário')),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_lista', to='gestoreduka.reelcentro')),
            ],
            options={
                'verbose_name': 'Comentário de Reel',
                'verbose_name_plural': 'Comentários de Reels',
                'ordering': ['-data_comentario'],
            },
        ),
        migrations.CreateModel(
            name='VisualizacaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.aluno')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Visualização de Perfil',
                'verbose_name_plural': 'Visualizações de Perfil',
            },
        ),
        migrations.CreateModel(
            name='CurtidaReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtida', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_users', to='gestoreduka.reelcentro')),
            ],
            options={
                'verbose_name': 'Curtida de Reel',
                'verbose_name_plural': 'Curtidas de Reels',
                'unique_together': {('reel', 'aluno')},
            },
        ),
    ]
