# Generated by Django 5.2.4 on 2026-04-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0008_filial_latitude_filial_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icone', models.CharField(default='feather-book', help_text='Ex: feather-monitor', max_length=50, verbose_name='Classe do Ícone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Centro',
                'verbose_name_plural': 'Categorias de Centros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AnuncioCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Anúncio')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='anuncios/', verbose_name='Imagem (opcional)')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False, verbose_name='Anúncio Urgente/Importante')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Anúncio do Centro',
                'verbose_name_plural': 'Anúncios dos Centros',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='centros', to='gestoreduka.categoriacentro'),
        ),
    ]
