# Generated by Django 5.2.4 on 2026-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0009_categoriacentro_anunciocentro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anunciocentro',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Anúncio de Centro', 'verbose_name_plural': 'Anúncios de Centros'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.RemoveField(
            model_name='anunciocentro',
            name='importante',
        ),
        migrations.AddField(
            model_name='anunciocentro',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='filial',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='filiais_centros', to='gestoreduka.categoriacentro', verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='filial',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AlterField(
            model_name='anunciocentro',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='anunciocentro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='anunciocentro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='categoriacentro',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='categoriacentro',
            name='icone',
            field=models.CharField(blank=True, help_text='Ex: feather-monitor', max_length=50, verbose_name='Ícone (FontAwesome/Feather)'),
        ),
        migrations.AlterField(
            model_name='categoriacentro',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoriacentro',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='centrodeformacao',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='centros_principais', to='gestoreduka.categoriacentro'),
        ),
    ]
