# Generated by Django 5.2.7 on 2025-11-10 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0009_perfilcentrodeformacao_ano_fundacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrodeformacao',
            options={'verbose_name': 'Centro de Formação', 'verbose_name_plural': 'Centros de Formação'},
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Localização Geográfica'),
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='centrodeformacao',
            name='nif',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='NIF'),
        ),
    ]
