# Generated by Django 5.2.4 on 2026-04-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0010_alter_anunciocentro_options_alter_mensagem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link (opcional)')),
                ('tipo', models.CharField(choices=[('COMENTARIO', 'Novo Comentário/Dúvida'), ('INSCRICAO', 'Nova Inscrição'), ('PAGAMENTO', 'Confirmação de Pagamento'), ('SISTEMA', 'Mensagem do Sistema')], default='SISTEMA', max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_gestor', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Notificação do Gestor',
                'verbose_name_plural': 'Notificações dos Gestores',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
