# Generated by Django 5.2.4 on 2026-05-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0011_notificacaogestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodeformacao',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='centrodeformacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='destaque',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Evento em Destaque'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('PALESTRA', 'Palestra'), ('FEIRA', 'Feira de Carreiras'), ('AULA_ABERTA', 'Aula Aberta'), ('OUTRO', 'Outro')], db_index=True, max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='perfilcentrodeformacao',
            name='destaque',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Centro em Destaque'),
        ),
        migrations.AlterField(
            model_name='perfilcentrodeformacao',
            name='verificado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Centro Verificado'),
        ),
        migrations.AlterField(
            model_name='reelcentro',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='reelcentro',
            name='destaque',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Reel em Destaque'),
        ),
        migrations.AlterField(
            model_name='reelcentro',
            name='publico',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Público'),
        ),
    ]
