# Generated by Django 5.2.4 on 2026-05-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0012_alter_centrodeformacao_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anunciocentro',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Anúncio do Centro', 'verbose_name_plural': 'Anúncios dos Centros'},
        ),
        migrations.AddField(
            model_name='anunciocentro',
            name='importante',
            field=models.BooleanField(default=False, verbose_name='Anúncio Urgente/Importante'),
        ),
    ]
