# Generated by Django 5.2.4 on 2026-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0013_alter_anunciocentro_options_anunciocentro_importante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_markup', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taxa de Markup (%)')),
                ('taxa_comissao', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taxa de Comissão (%)')),
            ],
            options={
                'verbose_name': 'Configuração da Plataforma',
                'verbose_name_plural': 'Configurações da Plataforma',
            },
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='metodo_precificacao',
            field=models.CharField(choices=[('MARKUP', 'Markup (Acréscimo no valor do curso)'), ('COMISSAO', 'Comissão (Desconto no repasse)')], default='MARKUP', max_length=10, verbose_name='Método de Precificação'),
        ),
    ]
