# Generated by Django 5.2.4 on 2026-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0014_configuracaoplataforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodeformacao',
            name='banco_iban',
            field=models.CharField(blank=True, help_text='AO06.0000.0000...', max_length=50, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='banco_nome',
            field=models.CharField(blank=True, help_text='Ex: BAI, BFA, BIC...', max_length=100, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AddField(
            model_name='centrodeformacao',
            name='banco_titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular da Conta'),
        ),
    ]
