# Generated by Django 6.0.5 on 2026-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0015_centrodeformacao_banco_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaogestor',
            name='tipo',
            field=models.CharField(choices=[('COMENTARIO', 'Novo Comentário/Dúvida'), ('INSCRICAO', 'Nova Inscrição'), ('PAGAMENTO', 'Confirmação de Pagamento'), ('SISTEMA', 'Mensagem do Sistema'), ('MENSAGEM', 'Nova Mensagem'), ('SEGUIMENTO', 'Novo Seguidor')], default='SISTEMA', max_length=20),
        ),
    ]
