# Generated by Django 5.2.4 on 2026-07-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0025_seed_categorias'),
        ('gestoreduka', '0016_alter_notificacaogestor_tipo'),
        ('usuarios', '0015_create_muquissi_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceria',
            name='aceita_candidaturas',
            field=models.BooleanField(default=False, verbose_name='Aceita Candidaturas'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='contacto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='parceiro_externo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Parceiro Externo'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='total_candidatos',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Candidatos'),
        ),
        migrations.CreateModel(
            name='CandidaturaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('bi', models.CharField(blank=True, max_length=30, verbose_name='BI/Nº Identificação')),
                ('documento_inscricao', models.FileField(blank=True, null=True, upload_to='candidaturas/documentos/', verbose_name='Documento de Inscrição')),
                ('comprovativo_pagamento', models.FileField(blank=True, null=True, upload_to='candidaturas/comprovantes/', verbose_name='Comprovativo de Pagamento')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Rejeitada'), ('C', 'Cancelada')], db_index=True, default='P', max_length=1, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('resposta_admin', models.TextField(blank=True, verbose_name='Resposta do Admin')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_externas', to='usuarios.aluno', verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_externas', to='cursos_app.curso', verbose_name='Curso')),
                ('parceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='gestoreduka.parceria', verbose_name='Parceria')),
            ],
            options={
                'verbose_name': 'Candidatura Externa',
                'verbose_name_plural': 'Candidaturas Externas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
