# Generated by Django 5.2.4 on 2026-08-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0017_parceria_aceita_candidaturas_parceria_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoplataforma',
            options={'verbose_name': 'Configuração de Taxas e Comissões', 'verbose_name_plural': 'Configurações de Taxas e Comissões'},
        ),
        migrations.AddField(
            model_name='configuracaoplataforma',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='configuracaoplataforma',
            name='taxa_comissao_ead',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Percentagem da plataforma em vendas de vídeo-cursos gravados.', max_digits=5, verbose_name='Comissão em Cursos Online EAD (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoplataforma',
            name='taxa_gestao_bolsas',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taxa retida na alocação de fundos de patrocínio corporativo.', max_digits=5, verbose_name='Taxa de Gestão do Fundo de Bolsas (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='taxa_comissao',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Percentagem retida pelo EdukAngola nas inscrições de cursos presenciais/centros. Ex: 15.00, 8.00 ou 5.00.', max_digits=5, verbose_name='Comissão Padrão de Inscrição em Cursos (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='taxa_markup',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taxa de Markup Padrão (%)'),
        ),
    ]
