# Generated by Django 5.2.4 on 2026-08-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0018_alter_configuracaoplataforma_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, verbose_name='ID Externo')),
                ('tipo', models.CharField(default='INSCRICAO', max_length=60, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Dados Recebidos')),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro')], db_index=True, default='RECEBIDO', max_length=12, verbose_name='Estado')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_integracao', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Evento de Integração',
                'verbose_name_plural': 'Eventos de Integração',
                'ordering': ['-recebido_em'],
                'constraints': [models.UniqueConstraint(fields=('centro', 'external_id', 'tipo'), name='unique_centro_external_event')],
            },
        ),
    ]
