# Generated by Django 5.2.4 on 2026-08-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0019_eventos_integracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('GESTOR', 'Gestor'), ('SECRETARIA', 'Secretaria'), ('CAIXA', 'Caixa'), ('COORDENACAO', 'Coordenação pedagógica'), ('CONSULTA', 'Consulta')], default='SECRETARIA', max_length=16, verbose_name='Função')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_operacionais', to='gestoreduka.centrodeformacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_centro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro Operacional do Centro',
                'verbose_name_plural': 'Membros Operacionais do Centro',
                'constraints': [models.UniqueConstraint(fields=('centro', 'usuario'), name='unique_membro_operacional_centro')],
            },
        ),
    ]
