# Generated by Django 5.2.4 on 2026-08-14 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0020_membros_operacionais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80, verbose_name='Ação')),
                ('entidade', models.CharField(max_length=80, verbose_name='Entidade')),
                ('objeto_id', models.CharField(blank=True, max_length=80, verbose_name='ID do Objeto')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='gestoreduka.centrodeformacao')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_centro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria do Centro',
                'verbose_name_plural': 'Auditorias do Centro',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['centro', 'entidade', 'criado_em'], name='gestoreduka_centro__ee4cf2_idx')],
            },
        ),
    ]
