# Generated by Django 5.2.4 on 2026-08-16 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0021_auditoria_centro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidaturaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('nif', models.CharField(db_index=True, max_length=18, verbose_name='NIF')),
                ('codigo_hash', models.CharField(max_length=128, verbose_name='Código de verificação')),
                ('codigo_criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Código criado em')),
                ('codigo_expira_em', models.DateTimeField(verbose_name='Código expira em')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VERIFICADA', 'Email verificado'), ('CONCLUIDA', 'Cadastro concluído'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=12, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('centro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatura_publica', to='gestoreduka.centrodeformacao')),
            ],
            options={
                'verbose_name': 'Candidatura de Centro',
                'verbose_name_plural': 'Candidaturas de Centros',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['email', 'nif', 'status'], name='gestoreduka_email_01e6c3_idx')],
            },
        ),
    ]
