# Generated by Django 5.2.4 on 2026-08-16 04:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0022_candidaturacentro'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturacentro',
            name='link_criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Link criado em'),
        ),
        migrations.AddField(
            model_name='candidaturacentro',
            name='link_expira_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Link expira em'),
        ),
        migrations.AddField(
            model_name='candidaturacentro',
            name='link_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token do link'),
        ),
        migrations.AddField(
            model_name='candidaturacentro',
            name='link_usado',
            field=models.BooleanField(default=False, verbose_name='Link usado'),
        ),
    ]
