# Generated by Django 5.2.4 on 2026-08-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0024_depoimento_consentimento_origem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curtidareel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='curtidareel',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='curtidareel',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='reelcentro',
            name='centro',
        ),
        migrations.DeleteModel(
            name='ComentarioReel',
        ),
        migrations.DeleteModel(
            name='CurtidaReel',
        ),
        migrations.DeleteModel(
            name='ReelCentro',
        ),
    ]
