# Generated by Django 6.1.1 on 2026-09-12 08:56

import core.upload_validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0028_modulos_escolas_estagios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcentrodeformacao',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='centros/banners/', validators=[core.upload_validators.validate_image_file], verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='perfilcentrodeformacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='centros/', validators=[core.upload_validators.validate_image_file], verbose_name='Imagem ou Logo'),
        ),
        migrations.CreateModel(
            name='ConviteEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Código')),
                ('nome_organizacao', models.CharField(max_length=200, verbose_name='Nome da Organização/Empresa')),
                ('email_gestor', models.EmailField(blank=True, max_length=254, verbose_name='Email do Gestor')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_eventos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de Eventos',
                'verbose_name_plural': 'Convites de Eventos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
