# Generated by Django 6.1.1 on 2026-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreduka', '0029_convite_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conviteeventos',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição da Organização'),
        ),
        migrations.AddField(
            model_name='conviteeventos',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='conviteeventos',
            name='logo',
            field=models.ImageField(blank=True, upload_to='convites_eventos/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='conviteeventos',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
