import { createContext, useContext, useEffect, useMemo } from "react";

export const LANGUAGES = [
  { code: "pt", short: "PT", label: "Português" },
  { code: "en", short: "EN", label: "English" },
  { code: "fr", short: "FR", label: "Français" },
  { code: "zh", short: "中文", label: "中文（简体）" },
];

const messages = {
  pt: {
    "nav.explore": "Explorar", "nav.classCourses": "Cursos presenciais", "nav.videoCourses": "Cursos em vídeo", "nav.library": "Biblioteca", "nav.news": "Notícias", "nav.events": "Eventos", "nav.centres": "Centros", "nav.how": "Como funciona", "nav.about": "Sobre", "nav.faq": "Perguntas frequentes", "nav.privacy": "Política de privacidade", "nav.menuDiscover": "Descobrir", "nav.menuPlatform": "Plataforma", "nav.forCentres": "Para centros", "nav.login": "Entrar", "nav.createAccount": "Criar conta", "nav.activeAccount": "Conta ativa", "nav.openStudent": "Abrir área de {name}", "nav.language": "Idioma", "nav.openSearch": "Abrir pesquisa", "nav.theme": "Alternar tema",
    "footer.tagline": "Formação acessível, informação clara e oportunidades reais para Angola.",
    "search.dialog": "Pesquisar cursos", "search.eyebrow": "Pesquisa rápida", "search.title": "O que quer aprender?", "search.close": "Fechar pesquisa", "search.placeholder": "Curso, centro ou competência", "search.submit": "Pesquisar", "search.try": "Experimente:", "search.escape": "para fechar",
    "home.trustCentres": "Cursos presenciais de centros", "home.trustVideos": "Cursos em vídeo para estudar ao seu ritmo", "home.trustClarity": "Informação clara antes de comprar ou inscrever", "home.eyebrow": "Explore por área", "home.title": "Comece pela área que lhe interessa.", "home.allAreas": "Ver todas as áreas", "home.centresTitle": "Conheça os centros de formação", "home.centresCopy": "Compare centros, localizações e cursos publicados.", "home.howTitle": "Entenda como funciona", "home.howCopy": "Veja o percurso da descoberta à inscrição.",
    "catalog.eyebrow": "Catálogo de cursos", "catalog.hero": "Escolha entre formação presencial e curso em vídeo.", "catalog.heroCopy": "As formações de centros acontecem presencialmente e usam turmas. Os cursos em vídeo são comprados para estudar ao seu ritmo, com acompanhamento de centro apenas quando indicado.", "catalog.results": "Resultados reais", "catalog.allTitle": "Formações presenciais e cursos em vídeo.", "catalog.videoTitle": "Cursos em vídeo disponíveis.", "catalog.classTitle": "Formações presenciais disponíveis.", "catalog.products": "produtos", "catalog.video": "Cursos em vídeo", "catalog.class": "Formações presenciais", "catalog.openClass": "Turma aberta", "catalog.range": "A mostrar", "catalog.of": "de", "catalog.previous": "Anterior", "catalog.next": "Próxima", "catalog.emptyEyebrow": "Sem correspondências", "catalog.emptyTitle": "Nenhum produto corresponde a estes filtros.", "catalog.emptyCopy": "Tente remover um filtro ou pesquisar uma área mais ampla. Só apresentamos formações presenciais e cursos em vídeo publicados no portal.", "catalog.reset": "Ver todo o catálogo",
    "filters.eyebrow": "Refinar cursos", "filters.title": "Filtros", "filters.clear": "Limpar", "filters.search": "Pesquisar por curso, centro ou competência", "filters.area": "Área de formação", "filters.allAreas": "Todas as áreas", "filters.product": "Produto", "filters.all": "Todos", "filters.class": "Cursos presenciais", "filters.video": "Cursos em vídeo", "filters.province": "Província", "filters.allF": "Todas", "filters.payment": "Pagamento", "filters.free": "Acesso gratuito", "filters.noneNow": "Sem pagamento no ato", "filters.payNow": "Com pagamento no ato", "filters.openClass": "Com turma aberta",
    "how.eyebrow": "Processo para estudantes", "how.hero": "Inscrever-se numa formação deve ser simples e transparente.", "how.heroCopy": "A Edukangola reúne a informação que ajuda a decidir antes de enviar uma inscrição.", "how.cta": "Explorar cursos publicados", "how.sectionEyebrow": "Do curso à confirmação", "how.title": "Um percurso claro, passo a passo.", "how.copy": "O centro continua responsável pelas suas regras, turmas e aprovações; a plataforma torna a descoberta e a inscrição mais simples.", "how.noteTitle": "Já sabe que curso quer fazer?", "how.noteCopy": "Abra a ficha do curso, confirme a turma e avance para a inscrição.", "how.noteLink": "Ir para o catálogo", "how.step1": "Descubra uma formação", "how.step1Copy": "Pesquise um curso ou explore os centros. Abra o detalhe para comparar modalidade, turma, local e vagas.", "how.step2": "Envie a inscrição", "how.step2Copy": "Escolha a turma e preencha os dados essenciais. A inscrição pode começar mesmo sem uma conta obrigatória.", "how.step3": "Veja o pagamento", "how.step3Copy": "Antes de avançar, veja se existe taxa, o que é cobrado agora e o que fica para depois.", "how.step4": "Acompanhe a confirmação", "how.step4Copy": "O centro processa a candidatura segundo as condições publicadas para aquele curso e turma.",
    "category.Technology": "Tecnologia", "category.Business": "Gestão e Negócios", "category.Languages": "Idiomas", "category.Design": "Design", "category.Construction": "Construção", "category.Health": "Saúde", "category.TechnologyCopy": "Informática, dados e desenvolvimento", "category.BusinessCopy": "Liderança e empreendedorismo", "category.LanguagesCopy": "Comunicação para novas oportunidades", "category.DesignCopy": "Criação e ferramentas digitais", "category.ConstructionCopy": "Ofícios e competências técnicas", "category.HealthCopy": "Cuidados e bem-estar",
  },
  en: {
    "nav.explore": "Explore", "nav.classCourses": "In-person courses", "nav.videoCourses": "Video courses", "nav.library": "Library", "nav.news": "News", "nav.events": "Events", "nav.centres": "Training centres", "nav.how": "How it works", "nav.about": "About", "nav.faq": "Frequently asked questions", "nav.privacy": "Privacy policy", "nav.menuDiscover": "Discover", "nav.menuPlatform": "Platform", "nav.forCentres": "For centres", "nav.login": "Log in", "nav.createAccount": "Create account", "nav.activeAccount": "Active account", "nav.openStudent": "Open {name}'s area", "nav.language": "Language", "nav.openSearch": "Open search", "nav.theme": "Toggle theme",
    "footer.tagline": "Accessible training, clear information and real opportunities for Angola.",
    "search.dialog": "Search courses", "search.eyebrow": "Quick search", "search.title": "What would you like to learn?", "search.close": "Close search", "search.placeholder": "Course, centre or skill", "search.submit": "Search", "search.try": "Try:", "search.escape": "to close",
    "home.trustCentres": "In-person courses from training centres", "home.trustVideos": "Video courses to study at your own pace", "home.trustClarity": "Clear information before buying or enrolling", "home.eyebrow": "Explore by area", "home.title": "Start with the area that interests you.", "home.allAreas": "View all areas", "home.centresTitle": "Discover training centres", "home.centresCopy": "Compare centres, locations and published courses.", "home.howTitle": "Understand how it works", "home.howCopy": "See the journey from discovery to enrolment.",
    "catalog.eyebrow": "Course catalogue", "catalog.hero": "Choose between in-person training and video courses.", "catalog.heroCopy": "Training-centre courses happen in person and use class groups. Video courses are purchased to study at your own pace, with centre support when stated.", "catalog.results": "Live results", "catalog.allTitle": "In-person training and video courses.", "catalog.videoTitle": "Available video courses.", "catalog.classTitle": "Available in-person training.", "catalog.products": "products", "catalog.video": "Video courses", "catalog.class": "In-person training", "catalog.openClass": "Open class", "catalog.range": "Showing", "catalog.of": "of", "catalog.previous": "Previous", "catalog.next": "Next", "catalog.emptyEyebrow": "No matches", "catalog.emptyTitle": "No product matches these filters.", "catalog.emptyCopy": "Try removing a filter or searching for a broader area. We only show in-person training and video courses published on the portal.", "catalog.reset": "View all courses",
    "filters.eyebrow": "Refine courses", "filters.title": "Filters", "filters.clear": "Clear", "filters.search": "Search by course, centre or skill", "filters.area": "Training area", "filters.allAreas": "All areas", "filters.product": "Product", "filters.all": "All", "filters.class": "In-person courses", "filters.video": "Video courses", "filters.province": "Province", "filters.allF": "All", "filters.payment": "Payment", "filters.free": "Free access", "filters.noneNow": "No payment now", "filters.payNow": "Payment now", "filters.openClass": "With open class",
    "how.eyebrow": "Student process", "how.hero": "Enrolling in training should be simple and transparent.", "how.heroCopy": "Edukangola brings together the information that helps you decide before submitting an enrolment.", "how.cta": "Explore published courses", "how.sectionEyebrow": "From course to confirmation", "how.title": "A clear journey, step by step.", "how.copy": "The centre remains responsible for its rules, classes and approvals; the platform makes discovery and enrolment simpler.", "how.noteTitle": "Already know which course you want?", "how.noteCopy": "Open the course page, confirm the class and continue to enrolment.", "how.noteLink": "Go to catalogue", "how.step1": "Discover training", "how.step1Copy": "Search for a course or explore centres. Open the details to compare format, class, location and vacancies.", "how.step2": "Submit enrolment", "how.step2Copy": "Choose a class and complete the essential details. Enrolment can start even without a mandatory account.", "how.step3": "Review payment", "how.step3Copy": "Before continuing, check whether there is a fee, what is charged now and what comes later.", "how.step4": "Track confirmation", "how.step4Copy": "The centre processes the application according to the conditions published for that course and class.",
    "category.Technology": "Technology", "category.Business": "Business", "category.Languages": "Languages", "category.Design": "Design", "category.Construction": "Construction", "category.Health": "Health", "category.TechnologyCopy": "Computing, data and development", "category.BusinessCopy": "Leadership and entrepreneurship", "category.LanguagesCopy": "Communication for new opportunities", "category.DesignCopy": "Creation and digital tools", "category.ConstructionCopy": "Trades and technical skills", "category.HealthCopy": "Care and wellbeing",
  },
  fr: {
    "nav.explore": "Explorer", "nav.classCourses": "Cours en présentiel", "nav.videoCourses": "Cours vidéo", "nav.library": "Bibliothèque", "nav.news": "Actualités", "nav.events": "Événements", "nav.centres": "Centres de formation", "nav.how": "Comment ça marche", "nav.about": "À propos", "nav.faq": "Questions fréquentes", "nav.privacy": "Politique de confidentialité", "nav.menuDiscover": "Découvrir", "nav.menuPlatform": "Plateforme", "nav.forCentres": "Pour les centres", "nav.login": "Se connecter", "nav.createAccount": "Créer un compte", "nav.activeAccount": "Compte actif", "nav.openStudent": "Ouvrir l'espace de {name}", "nav.language": "Langue", "nav.openSearch": "Ouvrir la recherche", "nav.theme": "Changer le thème",
    "footer.tagline": "Une formation accessible, des informations claires et de vraies opportunités pour l’Angola.",
    "search.dialog": "Rechercher des cours", "search.eyebrow": "Recherche rapide", "search.title": "Que souhaitez-vous apprendre ?", "search.close": "Fermer la recherche", "search.placeholder": "Cours, centre ou compétence", "search.submit": "Rechercher", "search.try": "Essayez :", "search.escape": "pour fermer",
    "home.trustCentres": "Cours en présentiel des centres", "home.trustVideos": "Cours vidéo à suivre à votre rythme", "home.trustClarity": "Des informations claires avant d’acheter ou de s’inscrire", "home.eyebrow": "Explorer par domaine", "home.title": "Commencez par le domaine qui vous intéresse.", "home.allAreas": "Voir tous les domaines", "home.centresTitle": "Découvrir les centres de formation", "home.centresCopy": "Comparez les centres, les lieux et les cours publiés.", "home.howTitle": "Comprendre le fonctionnement", "home.howCopy": "Suivez le parcours de la découverte à l’inscription.",
    "catalog.eyebrow": "Catalogue de cours", "catalog.hero": "Choisissez entre formation en présentiel et cours vidéo.", "catalog.heroCopy": "Les formations des centres se déroulent en présentiel avec des groupes. Les cours vidéo s’achètent pour étudier à votre rythme, avec l’accompagnement du centre lorsqu’il est indiqué.", "catalog.results": "Résultats réels", "catalog.allTitle": "Formations en présentiel et cours vidéo.", "catalog.videoTitle": "Cours vidéo disponibles.", "catalog.classTitle": "Formations en présentiel disponibles.", "catalog.products": "produits", "catalog.video": "Cours vidéo", "catalog.class": "Formations en présentiel", "catalog.openClass": "Groupe ouvert", "catalog.range": "Affichage", "catalog.of": "sur", "catalog.previous": "Précédent", "catalog.next": "Suivant", "catalog.emptyEyebrow": "Aucun résultat", "catalog.emptyTitle": "Aucun produit ne correspond à ces filtres.", "catalog.emptyCopy": "Essayez de supprimer un filtre ou de rechercher un domaine plus large. Nous affichons uniquement les formations en présentiel et les cours vidéo publiés sur le portail.", "catalog.reset": "Voir tout le catalogue",
    "filters.eyebrow": "Affiner les cours", "filters.title": "Filtres", "filters.clear": "Effacer", "filters.search": "Rechercher par cours, centre ou compétence", "filters.area": "Domaine de formation", "filters.allAreas": "Tous les domaines", "filters.product": "Produit", "filters.all": "Tous", "filters.class": "Cours en présentiel", "filters.video": "Cours vidéo", "filters.province": "Province", "filters.allF": "Toutes", "filters.payment": "Paiement", "filters.free": "Accès gratuit", "filters.noneNow": "Sans paiement immédiat", "filters.payNow": "Paiement immédiat", "filters.openClass": "Avec groupe ouvert",
    "how.eyebrow": "Processus étudiant", "how.hero": "S’inscrire à une formation doit être simple et transparent.", "how.heroCopy": "Edukangola réunit les informations qui vous aident à décider avant d’envoyer une inscription.", "how.cta": "Explorer les cours publiés", "how.sectionEyebrow": "Du cours à la confirmation", "how.title": "Un parcours clair, étape par étape.", "how.copy": "Le centre reste responsable de ses règles, groupes et validations ; la plateforme rend la découverte et l’inscription plus simples.", "how.noteTitle": "Vous savez déjà quel cours suivre ?", "how.noteCopy": "Ouvrez la fiche du cours, confirmez le groupe et poursuivez vers l’inscription.", "how.noteLink": "Aller au catalogue", "how.step1": "Découvrir une formation", "how.step1Copy": "Recherchez un cours ou explorez les centres. Ouvrez le détail pour comparer format, groupe, lieu et places.", "how.step2": "Envoyer l’inscription", "how.step2Copy": "Choisissez un groupe et complétez les informations essentielles. L’inscription peut commencer sans compte obligatoire.", "how.step3": "Voir le paiement", "how.step3Copy": "Avant de continuer, vérifiez s’il existe des frais, ce qui est facturé maintenant et ce qui vient ensuite.", "how.step4": "Suivre la confirmation", "how.step4Copy": "Le centre traite la candidature selon les conditions publiées pour ce cours et ce groupe.",
    "category.Technology": "Technologie", "category.Business": "Gestion et affaires", "category.Languages": "Langues", "category.Design": "Design", "category.Construction": "Construction", "category.Health": "Santé", "category.TechnologyCopy": "Informatique, données et développement", "category.BusinessCopy": "Leadership et entrepreneuriat", "category.LanguagesCopy": "Communication pour de nouvelles opportunités", "category.DesignCopy": "Création et outils numériques", "category.ConstructionCopy": "Métiers et compétences techniques", "category.HealthCopy": "Soins et bien-être",
  },
  zh: {
    "nav.explore": "探索", "nav.classCourses": "线下课程", "nav.videoCourses": "视频课程", "nav.library": "图书馆", "nav.news": "新闻", "nav.events": "活动", "nav.centres": "培训中心", "nav.how": "使用方式", "nav.about": "关于我们", "nav.faq": "常见问题", "nav.privacy": "隐私政策", "nav.menuDiscover": "探索", "nav.menuPlatform": "平台", "nav.forCentres": "培训中心入口", "nav.login": "登录", "nav.createAccount": "创建账户", "nav.activeAccount": "已登录", "nav.openStudent": "打开{name}的学习空间", "nav.language": "语言", "nav.openSearch": "打开搜索", "nav.theme": "切换主题",
    "footer.tagline": "为安哥拉提供易获得的培训、清晰的信息和真实的机会。",
    "search.dialog": "搜索课程", "search.eyebrow": "快速搜索", "search.title": "您想学习什么？", "search.close": "关闭搜索", "search.placeholder": "课程、中心或技能", "search.submit": "搜索", "search.try": "试试：", "search.escape": "关闭",
    "home.trustCentres": "培训中心的线下课程", "home.trustVideos": "按自己的节奏学习视频课程", "home.trustClarity": "购买或报名之前先了解清晰信息", "home.eyebrow": "按领域探索", "home.title": "从您感兴趣的领域开始。", "home.allAreas": "查看所有领域", "home.centresTitle": "了解培训中心", "home.centresCopy": "比较中心、地点和已发布课程。", "home.howTitle": "了解使用方式", "home.howCopy": "了解从发现课程到报名的过程。",
    "catalog.eyebrow": "课程目录", "catalog.hero": "在线下培训和视频课程之间选择。", "catalog.heroCopy": "培训中心的课程在线下进行并设有班级。视频课程购买后可按自己的节奏学习，并在注明时获得中心支持。", "catalog.results": "实时结果", "catalog.allTitle": "线下培训和视频课程。", "catalog.videoTitle": "可用视频课程。", "catalog.classTitle": "可用线下培训。", "catalog.products": "项课程", "catalog.video": "视频课程", "catalog.class": "线下培训", "catalog.openClass": "开放班级", "catalog.range": "显示", "catalog.of": "共", "catalog.previous": "上一页", "catalog.next": "下一页", "catalog.emptyEyebrow": "没有匹配结果", "catalog.emptyTitle": "没有课程符合这些筛选条件。", "catalog.emptyCopy": "请尝试移除筛选条件或搜索更广泛的领域。我们只展示门户中发布的线下培训和视频课程。", "catalog.reset": "查看全部课程",
    "filters.eyebrow": "筛选课程", "filters.title": "筛选", "filters.clear": "清除", "filters.search": "按课程、中心或技能搜索", "filters.area": "培训领域", "filters.allAreas": "所有领域", "filters.product": "产品", "filters.all": "全部", "filters.class": "线下课程", "filters.video": "视频课程", "filters.province": "省份", "filters.allF": "全部", "filters.payment": "付款", "filters.free": "免费访问", "filters.noneNow": "暂不付款", "filters.payNow": "立即付款", "filters.openClass": "有开放班级",
    "how.eyebrow": "学生流程", "how.hero": "报名培训应该简单而透明。", "how.heroCopy": "Edukangola 汇集了帮助您在提交报名之前作出决定的信息。", "how.cta": "探索已发布课程", "how.sectionEyebrow": "从课程到确认", "how.title": "清晰的分步流程。", "how.copy": "培训中心仍负责自己的规则、班级和审批；平台让发现和报名更简单。", "how.noteTitle": "已经知道想学什么课程？", "how.noteCopy": "打开课程页面，确认班级，然后继续报名。", "how.noteLink": "前往目录", "how.step1": "发现培训", "how.step1Copy": "搜索课程或探索培训中心。打开详情比较形式、班级、地点和名额。", "how.step2": "提交报名", "how.step2Copy": "选择班级并填写基本信息。即使没有强制账户，也可以开始报名。", "how.step3": "查看付款", "how.step3Copy": "继续之前，请查看是否有费用、现在收取什么以及之后需要支付什么。", "how.step4": "跟进确认", "how.step4Copy": "培训中心根据为该课程和班级发布的条件处理申请。",
    "category.Technology": "科技", "category.Business": "管理与商业", "category.Languages": "语言", "category.Design": "设计", "category.Construction": "建筑", "category.Health": "健康", "category.TechnologyCopy": "计算机、数据和开发", "category.BusinessCopy": "领导力和创业", "category.LanguagesCopy": "面向新机会的沟通", "category.DesignCopy": "创作和数字工具", "category.ConstructionCopy": "行业与技术技能", "category.HealthCopy": "护理与健康",
  },
};

const I18nContext = createContext(null);

export function I18nProvider({ language, onLanguageChange, children }) {
  const value = useMemo(() => ({
    language,
    setLanguage: onLanguageChange,
    t: (key, variables = {}) => {
      const phrase = messages[language]?.[key] ?? messages.pt[key] ?? key;
      return Object.entries(variables).reduce((current, [name, replacement]) => current.replaceAll(`{${name}}`, String(replacement)), phrase);
    },
  }), [language, onLanguageChange]);

  useEffect(() => {
    document.documentElement.lang = language === "zh" ? "zh-Hans" : language;
    document.documentElement.dataset.language = language;
  }, [language]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n deve ser usado dentro de I18nProvider.");
  return context;
}
